/**
 * Path → SEO metadata map for the AI Tools & Studios category.
 * Used by <RouteSEO /> to inject per-route title/description/canonical
 * without editing 24 individual page components.
 *
 * Each entry references an i18n key under `aiToolsSeo.<key>` (title/description).
 * EN fallbacks live inline so a missing locale never blanks the head.
 */

export interface AIToolSeo {
  /** i18n key prefix; resolves `${key}.title` and `${key}.description` */
  key: string;
  /** English fallback title (renders when i18n key is missing) */
  title: string;
  /** English fallback description (≤160 chars) */
  description: string;
}

export const AI_TOOLS_SEO: Record<string, AIToolSeo> = {
  "/ai-mentor": {
    key: "aiToolsSeo.aiMentor",
    title: "AI Mentor — personal coach for career, skills & life",
    description: "Get unstuck with an AI mentor trained for career, study and personal growth. Pay per session in credits — no subscription required.",
  },
  "/ai-mentor/hub": {
    key: "aiToolsSeo.aiMentorHub",
    title: "AI Mentor Hub — pick your coaching track",
    description: "Browse AI mentors across business, learning, fitness and creativity. Start a session in seconds.",
  },
  "/companions": {
    key: "aiToolsSeo.companions",
    title: "AI Companions — conversational characters that remember you",
    description: "Chat with custom AI companions that learn your style and grow with you. Persistent memory, credit-based, no waitlist.",
  },
  "/content-studio": {
    key: "aiToolsSeo.contentStudio",
    title: "AI Content Studio — generate posts, scripts, captions",
    description: "Spin up social-ready copy, hooks, SEO outlines and ad scripts in one studio. Pay only for what you generate.",
  },
  "/ai-experiences": {
    key: "aiToolsSeo.aiExperiences",
    title: "AI Experiences — virtual tours & age progression",
    description: "Plan dream trips and preview yourself decades later. Two AI experiences, transparent credit pricing.",
  },
  "/ai-tattoo": {
    key: "aiToolsSeo.aiTattoo",
    title: "AI Tattoo Designer — custom ink concepts in seconds",
    description: "Describe the vibe, get studio-quality tattoo concepts. Save your favorites and take them to your artist.",
  },
  "/beauty-studio": {
    key: "aiToolsSeo.beautyStudio",
    title: "AI Beauty Studio — hair, makeup & skin previews",
    description: "Try new looks before you commit. AI-rendered hairstyles, makeup and skincare routines tailored to you.",
  },
  "/wine-pairing": {
    key: "aiToolsSeo.winePairing",
    title: "AI Wine Pairing — perfect bottle for every dish",
    description: "Tell us what's for dinner. AI suggests the wine, region and price tier in seconds.",
  },
  "/brand-builder": {
    key: "aiToolsSeo.brandBuilder",
    title: "AI Brand Builder — logo, palette & voice in minutes",
    description: "Launch a brand identity with AI-generated logos, colors and tone guidelines. Export-ready assets.",
  },
  "/home-designer": {
    key: "aiToolsSeo.homeDesigner",
    title: "AI Home Designer — redesign any room from a photo",
    description: "Upload a room, pick a style, see the makeover. AI-powered interior design, credit-based.",
  },
  "/plant-care": {
    key: "aiToolsSeo.plantCare",
    title: "AI Plant Care — diagnose & save your plants",
    description: "Snap a leaf, get a diagnosis and care plan. Watering schedules, light needs, pest fixes — powered by AI.",
  },
  "/recipe-generator": {
    key: "aiToolsSeo.recipeGenerator",
    title: "AI Recipe Generator — cook with what's in your fridge",
    description: "List your ingredients, get a personalized recipe with steps and macros. No more 'what's for dinner'.",
  },
  "/meal-planner": {
    key: "aiToolsSeo.mealPlanner",
    title: "AI Meal Planner — weekly plans that fit your goals",
    description: "Weekly menus tailored to budget, diet and household size. Generated by AI, swappable any time.",
  },
  "/food-scanner": {
    key: "aiToolsSeo.foodScanner",
    title: "AI Food Scanner — instant nutrition from a photo",
    description: "Snap your plate, see calories and macros. Track meals without typing a single ingredient.",
  },
  "/restaurant-analyzer": {
    key: "aiToolsSeo.restaurantAnalyzer",
    title: "AI Restaurant Analyzer — menus, reviews & best picks",
    description: "Paste a menu link or upload a photo. AI ranks dishes by reviews, value and dietary fit.",
  },
  "/chef-chat": {
    key: "aiToolsSeo.chefChat",
    title: "AI Chef Chat — cooking coach on demand",
    description: "Ask an AI chef anything: substitutions, technique, plating. Credits-based, no subscription.",
  },
  "/cooking-ai": {
    key: "aiToolsSeo.cookingAi",
    title: "AI Cooking Hub — recipes, scanner, planner",
    description: "One hub for every AI cooking tool: recipe generator, food scanner, meal planner and chef chat.",
  },
  "/ai-generation": {
    key: "aiToolsSeo.aiGeneration",
    title: "AI Image Generation — turn prompts into art",
    description: "Premium AI image generation with style controls. Pay per image, own your output.",
  },
  "/lottery-ai": {
    key: "aiToolsSeo.lotteryAi",
    title: "AI Lottery Picker — data-driven number suggestions",
    description: "AI analyzes historical draws and suggests number combinations. Entertainment only — play responsibly.",
  },
  "/photo-restoration": {
    key: "aiToolsSeo.photoRestoration",
    title: "AI Photo Restoration — bring old memories back to life",
    description: "Restore scratched, faded or torn photos with AI. Original quality, downloadable in minutes.",
  },
  "/antique-appraisal": {
    key: "aiToolsSeo.antiqueAppraisal",
    title: "AI Antique Appraisal — estimate value from a photo",
    description: "Snap your antique, AI returns an estimated value range, era and authenticity signals.",
  },
  "/handwriting": {
    key: "aiToolsSeo.handwriting",
    title: "AI Handwriting Analyzer — personality from your script",
    description: "Upload a sample, get an AI personality and trait read. Entertainment-grade, fun to share.",
  },
  "/lie-detector": {
    key: "aiToolsSeo.lieDetector",
    title: "AI Lie Detector — entertainment-grade truth scanner",
    description: "Voice and text analysis returns a fun truth score. For entertainment only — not forensic.",
  },
  "/numerology": {
    key: "aiToolsSeo.numerology",
    title: "AI Numerology — your numbers, decoded",
    description: "AI-generated numerology reports based on your name and birth date. Instant, shareable.",
  },
};

/** Returns SEO entry for a route, or null if not registered. */
export function getAIToolSeo(pathname: string): AIToolSeo | null {
  return AI_TOOLS_SEO[pathname] ?? null;
}
