project_id = "jufrdzeonywluwutvyxz"

[functions.psychology-chat]
verify_jwt = false

[functions.tutoring-chat]
verify_jwt = false

[functions.import-recipes]
verify_jwt = false

[functions.import-jobs]
verify_jwt = false

[functions.generate-avatar]
verify_jwt = false
