project_id = "jufrdzeonywluwutvyxz"

[functions.psychology-chat]
verify_jwt = false

[functions.tutoring-chat]
verify_jwt = false

[functions.import-recipes]
verify_jwt = false

[functions.import-jobs]
verify_jwt = false

[functions.generate-avatar]
verify_jwt = false

[functions.apply-ai-effect]
verify_jwt = false

[functions.generate-course-content]
verify_jwt = false

[functions.best-friend-chat]
verify_jwt = false

[functions.ai-image-generation]
verify_jwt = false

[functions.convert-to-mp3]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.create-subscription-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-credits-payment]
verify_jwt = false

[functions.create-featured-payment]
verify_jwt = false

[functions.create-certificate-payment]
verify_jwt = false

[functions.create-job-listing-payment]
verify_jwt = false

[functions.create-influencer-tip-payment]
verify_jwt = false

[functions.send-platform-gift]
verify_jwt = false
