// Shared Unique brand styles for auth emails
export const brand = {
  primary: '#a855f7', // purple-500
  primaryDark: '#7c3aed',
  accent: '#ec4899', // pink-500
  gradient: 'linear-gradient(135deg, #a855f7 0%, #ec4899 100%)',
  text: '#1f1033',
  textMuted: '#6b6580',
  bg: '#ffffff',
  cardBg: '#faf7ff',
  border: '#ece4ff',
  radius: '14px',
  font: "'Inter', 'Helvetica Neue', Arial, sans-serif",
}

export const styles = {
  main: { backgroundColor: '#f4eeff', fontFamily: brand.font, margin: 0, padding: '24px 0' },
  container: {
    backgroundColor: brand.bg,
    borderRadius: '20px',
    maxWidth: '560px',
    margin: '0 auto',
    overflow: 'hidden' as const,
    boxShadow: '0 8px 32px rgba(168,85,247,0.18)',
  },
  header: {
    background: brand.gradient,
    padding: '36px 24px',
    textAlign: 'center' as const,
  },
  brandName: {
    fontFamily: "'Lobster Two', 'Georgia', serif",
    fontWeight: 700,
    fontSize: '44px',
    color: '#ffffff',
    margin: 0,
    letterSpacing: '0.5px',
    textShadow: '0 2px 8px rgba(0,0,0,0.15)',
  },
  tagline: {
    color: 'rgba(255,255,255,0.92)',
    fontSize: '13px',
    margin: '6px 0 0',
    letterSpacing: '2px',
    textTransform: 'uppercase' as const,
  },
  body: { padding: '32px 32px 24px' },
  h1: { fontSize: '24px', fontWeight: 700, color: brand.text, margin: '0 0 16px' },
  text: { fontSize: '15px', color: brand.text, lineHeight: '1.6', margin: '0 0 18px' },
  muted: { fontSize: '13px', color: brand.textMuted, lineHeight: '1.5', margin: '0 0 12px' },
  buttonWrap: { textAlign: 'center' as const, margin: '28px 0' },
  button: {
    background: brand.gradient,
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: 600,
    borderRadius: brand.radius,
    padding: '14px 32px',
    textDecoration: 'none',
    display: 'inline-block',
    boxShadow: '0 4px 14px rgba(168,85,247,0.4)',
  },
  link: { color: brand.primaryDark, textDecoration: 'underline' },
  codeBox: {
    background: brand.cardBg,
    border: `1px solid ${brand.border}`,
    borderRadius: brand.radius,
    padding: '20px',
    textAlign: 'center' as const,
    fontSize: '32px',
    fontWeight: 700,
    letterSpacing: '8px',
    color: brand.primaryDark,
    margin: '20px 0',
  },
  footer: {
    background: brand.cardBg,
    padding: '20px 32px',
    textAlign: 'center' as const,
    fontSize: '12px',
    color: brand.textMuted,
    borderTop: `1px solid ${brand.border}`,
  },
}
