import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
import { Loader2, FileText, Download, ArrowLeft, Palette, Type, Share2, Eye } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { FloatingHowItWorks } from "../common/FloatingHowItWorks";

interface BrandStyleGuidePDFProps {
  credits: number;
  onBack: () => void;
}

const BrandStyleGuidePDF = ({ credits, onBack }: BrandStyleGuidePDFProps) => {
  const { toast } = useToast();
  const [brandKits, setBrandKits] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadBrandKits();
  }, []);

  const loadBrandKits = async () => {
    setLoading(true);
    const { data } = await supabase
      .from("brand_kits")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(20);
    if (data) setBrandKits(data);
    setLoading(false);
  };

  const downloadPDF = (kit: any) => {
    const content = `
╔══════════════════════════════════════════════════════╗
║               BRAND STYLE GUIDE                       ║
║               ${kit.business_name?.toUpperCase() || "BRAND"}                    ║
╚══════════════════════════════════════════════════════╝

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  1. BRAND OVERVIEW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Business Name: ${kit.business_name || "N/A"}
Business Type: ${kit.business_type || "N/A"}
Slogan: "${kit.slogan || "N/A"}"
Tagline: "${kit.tagline || "N/A"}"

Mission Statement:
${kit.mission_statement || "Not specified"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  2. COLOR PALETTE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${kit.color_palette?.map((c: any) => `  ■ ${c.name}: ${c.hex} — ${c.usage || "General use"}`).join("\n") || "No colors defined"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  3. TYPOGRAPHY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${kit.visual_identity?.typography || "Not specified"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  4. BRAND TONE & VOICE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${kit.visual_identity?.tone || "Not specified"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  5. IMAGERY STYLE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${kit.visual_identity?.imagery || "Not specified"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  6. TAGLINES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${kit.taglines?.map((t: string, i: number) => `  ${i + 1}. "${t}"`).join("\n") || "No taglines"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  7. SOCIAL MEDIA STRATEGY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${Object.entries(kit.social_media_strategy || {}).map(([p, s]) => `  ${p.toUpperCase()}: ${s}`).join("\n\n") || "Not specified"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Generated by Brand Builder | ${new Date(kit.created_at).toLocaleDateString()}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    `.trim();

    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${kit.business_name?.replace(/\s+/g, "_") || "brand"}_style_guide.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({ title: "📄 Downloaded!", description: "Brand style guide exported." });
  };

  return (
    <>
      <FloatingHowItWorks title={"Brand Style Guide P D F - How it works"} steps={[{ title: 'Open', desc: 'Access the Brand Style Guide P D F section from its module.' }, { title: 'Explore', desc: 'Review the controls and content available in Brand Style Guide P D F.' }, { title: 'Interact', desc: 'Use the available actions - browse, select, or submit as needed.' }, { title: 'Review', desc: 'Check the results, updates, or feedback shown after your action.' }]} />
      <div className="space-y-6">
      <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }}>
        <Button variant="ghost" onClick={onBack} className="mb-4 gap-2">
          <ArrowLeft className="h-4 w-4" /> Back to Hub
        </Button>
      </motion.div>

      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center mb-6">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-emerald-500/10 border border-emerald-500/20 mb-3">
          <FileText className="h-4 w-4 text-emerald-500" />
          <span className="text-sm font-semibold text-emerald-500">Brand Style Guide</span>
        </div>
        <h2 className="text-2xl sm:text-3xl font-bold text-foreground">Export Your Brand Guidelines</h2>
        <p className="text-muted-foreground mt-2">Download professional brand style guides from your generated kits</p>
        <Badge variant="secondary" className="mt-2">Free — uses your existing brand kits</Badge>
      </motion.div>

      {loading ? (
        <div className="flex justify-center py-12">
          <Loader2 className="h-8 w-8 animate-spin text-primary" />
        </div>
      ) : brandKits.length === 0 ? (
        <Card>
          <CardContent className="pt-6 text-center text-muted-foreground">
            <FileText className="h-12 w-12 mx-auto mb-4 opacity-50" />
            <p>No brand kits yet. Create one first from the hub!</p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {brandKits.map((kit, i) => (
            <motion.div key={kit.id} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.05 }}>
              <Card className="hover:shadow-lg transition-shadow hover:border-primary/30">
                <CardHeader className="pb-3">
                  <div className="flex items-start justify-between">
                    <div>
                      <CardTitle className="text-lg">{kit.business_name}</CardTitle>
                      <p className="text-sm text-muted-foreground">{kit.business_type}</p>
                    </div>
                    <Badge variant="outline" className="text-xs">{new Date(kit.created_at).toLocaleDateString()}</Badge>
                  </div>
                </CardHeader>
                <CardContent className="space-y-3">
                  <div className="flex items-center gap-2">
                    {kit.color_palette?.slice(0, 5).map((c: any, idx: number) => (
                      <div key={idx} className="h-6 w-6 rounded-full border" style={{ backgroundColor: c.hex }} title={c.name} />
                    ))}
                  </div>
                  {kit.slogan && <p className="text-sm italic text-primary/80">"{kit.slogan}"</p>}
                  <div className="flex gap-2 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1"><Palette className="h-3 w-3" /> Colors</span>
                    <span className="flex items-center gap-1"><Type className="h-3 w-3" /> Typography</span>
                    <span className="flex items-center gap-1"><Share2 className="h-3 w-3" /> Social</span>
                    <span className="flex items-center gap-1"><Eye className="h-3 w-3" /> Visual</span>
                  </div>
                  <Button onClick={() => downloadPDF(kit)} className="w-full gap-2" variant="outline">
                    <Download className="h-4 w-4" /> Download Style Guide
                  </Button>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      )}
    </div>
    </>
  );
};

export default BrandStyleGuidePDF;
