export interface CrystalInfo {
  name: string;
  chakra: string;
  element: string;
  color: string;
  properties: string;
  origin: string;
  zodiac: string;
  hardness: string;
  rarity: string;
  mantra: string;
  region: string;
  lat: number;
  lng: number;
}

export const CRYSTAL_DATABASE: CrystalInfo[] = [
  { name: "Amethyst", chakra: "Crown/Third Eye", element: "Air", color: "Purple", properties: "Calming, intuition, spiritual growth, protection against negative energy", origin: "Brazil, Uruguay, Zambia", zodiac: "Pisces, Aquarius", hardness: "7", rarity: "Common", mantra: "I trust my inner wisdom and embrace spiritual clarity", region: "South America", lat: -15.8, lng: -47.9 },
  { name: "Rose Quartz", chakra: "Heart", element: "Water", color: "Pink", properties: "Unconditional love, compassion, emotional healing, self-love", origin: "Brazil, Madagascar, South Africa", zodiac: "Taurus, Libra", hardness: "7", rarity: "Common", mantra: "I am worthy of love and I radiate compassion to all", region: "Africa", lat: -18.9, lng: 47.5 },
  { name: "Clear Quartz", chakra: "Crown", element: "All", color: "Clear/White", properties: "Amplification, clarity, energy cleansing, manifestation", origin: "Brazil, Arkansas USA, Madagascar", zodiac: "All signs", hardness: "7", rarity: "Common", mantra: "I am a channel of pure light and unlimited potential", region: "North America", lat: 34.7, lng: -92.3 },
  { name: "Citrine", chakra: "Solar Plexus", element: "Fire", color: "Yellow/Gold", properties: "Abundance, confidence, creativity, joy, manifestation", origin: "Brazil, Spain, Russia", zodiac: "Gemini, Aries, Leo", hardness: "7", rarity: "Uncommon", mantra: "I attract abundance and radiate golden confidence", region: "South America", lat: -14.2, lng: -51.9 },
  { name: "Black Tourmaline", chakra: "Root", element: "Earth", color: "Black", properties: "Protection, grounding, EMF shielding, negativity absorption", origin: "Brazil, Africa, Pakistan", zodiac: "Capricorn, Scorpio", hardness: "7-7.5", rarity: "Common", mantra: "I am grounded, protected, and secure in my foundation", region: "Asia", lat: 30.4, lng: 69.3 },
  { name: "Lapis Lazuli", chakra: "Third Eye/Throat", element: "Water", color: "Deep Blue", properties: "Wisdom, truth, inner vision, communication, royalty", origin: "Afghanistan, Chile, Russia", zodiac: "Sagittarius, Libra", hardness: "5-6", rarity: "Uncommon", mantra: "I speak my truth with wisdom and see beyond illusion", region: "Asia", lat: 33.9, lng: 67.7 },
  { name: "Tiger's Eye", chakra: "Solar Plexus/Root", element: "Fire/Earth", color: "Gold/Brown", properties: "Courage, willpower, personal power, good luck", origin: "South Africa, Australia, India", zodiac: "Leo, Capricorn", hardness: "6.5-7", rarity: "Common", mantra: "I move through life with courage and confident determination", region: "Africa", lat: -30.6, lng: 22.9 },
  { name: "Moonstone", chakra: "Crown/Third Eye", element: "Water", color: "White/Iridescent", properties: "Intuition, feminine energy, new beginnings, emotional balance", origin: "Sri Lanka, India, Myanmar", zodiac: "Cancer, Libra", hardness: "6-6.5", rarity: "Uncommon", mantra: "I flow with lunar cycles and embrace divine feminine wisdom", region: "Asia", lat: 7.9, lng: 80.8 },
  { name: "Carnelian", chakra: "Sacral", element: "Fire", color: "Orange/Red", properties: "Vitality, creativity, motivation, passion, sexuality", origin: "India, Brazil, Uruguay", zodiac: "Leo, Virgo", hardness: "6.5-7", rarity: "Common", mantra: "I ignite my creative fire and embrace passionate living", region: "Asia", lat: 20.6, lng: 79.0 },
  { name: "Selenite", chakra: "Crown", element: "Air", color: "White/Clear", properties: "Purification, clarity, angelic connection, peace", origin: "Morocco, Mexico, Australia", zodiac: "Cancer, Taurus", hardness: "2", rarity: "Common", mantra: "I am purified by divine light and connected to higher realms", region: "Africa", lat: 31.8, lng: -7.1 },
  { name: "Labradorite", chakra: "Third Eye/Throat", element: "Water", color: "Gray/Iridescent", properties: "Transformation, magic, psychic protection, intuition", origin: "Canada, Finland, Madagascar", zodiac: "Leo, Scorpio, Sagittarius", hardness: "6-6.5", rarity: "Uncommon", mantra: "I embrace transformation and trust the magic within me", region: "North America", lat: 53.1, lng: -60.0 },
  { name: "Obsidian", chakra: "Root", element: "Earth/Fire", color: "Black", properties: "Truth, protection, grounding, shadow work, self-reflection", origin: "Mexico, Iceland, Japan", zodiac: "Scorpio, Sagittarius", hardness: "5-6", rarity: "Common", mantra: "I face my shadows with courage and embrace wholeness", region: "North America", lat: 23.6, lng: -102.6 },
  { name: "Jade", chakra: "Heart", element: "Earth", color: "Green", properties: "Luck, prosperity, harmony, longevity, wisdom", origin: "Myanmar, China, Guatemala", zodiac: "Aries, Taurus, Libra", hardness: "6-7", rarity: "Uncommon", mantra: "I attract prosperity and walk in harmony with all life", region: "Asia", lat: 21.9, lng: 96.0 },
  { name: "Fluorite", chakra: "Third Eye/Heart", element: "Air", color: "Purple/Green/Multi", properties: "Mental clarity, focus, decision-making, protection", origin: "China, Mexico, South Africa", zodiac: "Capricorn, Pisces", hardness: "4", rarity: "Common", mantra: "My mind is clear and focused on what truly matters", region: "Asia", lat: 35.9, lng: 104.2 },
  { name: "Malachite", chakra: "Heart/Solar Plexus", element: "Earth", color: "Green (banded)", properties: "Transformation, emotional healing, protection, leadership", origin: "Congo, Russia, Australia", zodiac: "Scorpio, Capricorn", hardness: "3.5-4", rarity: "Uncommon", mantra: "I transform pain into wisdom and lead with an open heart", region: "Africa", lat: -4.0, lng: 21.8 },
  { name: "Aquamarine", chakra: "Throat", element: "Water", color: "Light Blue", properties: "Communication, courage, calming, clarity of expression", origin: "Brazil, Pakistan, Nigeria", zodiac: "Pisces, Aries, Gemini", hardness: "7.5-8", rarity: "Uncommon", mantra: "I communicate with clarity and flow like peaceful water", region: "South America", lat: -14.2, lng: -51.9 },
  { name: "Rhodonite", chakra: "Heart", element: "Earth", color: "Pink/Black", properties: "Emotional healing, forgiveness, compassion, self-love", origin: "Russia, Australia, Peru", zodiac: "Taurus, Scorpio", hardness: "5.5-6.5", rarity: "Uncommon", mantra: "I forgive freely and nurture my heart with compassion", region: "South America", lat: -9.2, lng: -75.0 },
  { name: "Sodalite", chakra: "Third Eye/Throat", element: "Air/Water", color: "Dark Blue/White", properties: "Logic, truth, self-expression, intuition, meditation", origin: "Brazil, Canada, Namibia", zodiac: "Sagittarius, Virgo", hardness: "5.5-6", rarity: "Common", mantra: "I balance logic and intuition in perfect harmony", region: "Africa", lat: -22.6, lng: 17.1 },
  { name: "Amazonite", chakra: "Heart/Throat", element: "Water/Earth", color: "Turquoise/Green", properties: "Truth, harmony, communication, soothing, hope", origin: "Russia, Brazil, Madagascar", zodiac: "Virgo, Aquarius", hardness: "6-6.5", rarity: "Uncommon", mantra: "I speak truth with love and embrace hope for the future", region: "Europe", lat: 61.5, lng: 105.3 },
  { name: "Turquoise", chakra: "Throat/Third Eye", element: "Earth/Air", color: "Blue-Green", properties: "Protection, wisdom, communication, spiritual grounding", origin: "Iran, USA, Mexico", zodiac: "Sagittarius, Scorpio, Pisces", hardness: "5-6", rarity: "Rare", mantra: "I am protected by ancient wisdom and speak with authority", region: "North America", lat: 35.0, lng: -111.1 },
  { name: "Garnet", chakra: "Root/Heart", element: "Fire/Earth", color: "Deep Red", properties: "Passion, energy, courage, love, vitality", origin: "India, Brazil, Madagascar", zodiac: "Capricorn, Aquarius, Leo", hardness: "6.5-7.5", rarity: "Common", mantra: "I burn with passion and courage in everything I pursue", region: "Asia", lat: 20.6, lng: 79.0 },
  { name: "Smoky Quartz", chakra: "Root", element: "Earth", color: "Brown/Gray", properties: "Grounding, stress relief, detoxification, protection", origin: "Brazil, Scotland, Switzerland", zodiac: "Scorpio, Capricorn", hardness: "7", rarity: "Common", mantra: "I release all that no longer serves me and stand grounded", region: "Europe", lat: 56.5, lng: -4.2 },
  { name: "Aventurine", chakra: "Heart", element: "Earth", color: "Green", properties: "Luck, prosperity, confidence, emotional calm", origin: "India, Brazil, China", zodiac: "Aries, Leo", hardness: "6.5-7", rarity: "Common", mantra: "I am open to abundance and lucky opportunities surround me", region: "Asia", lat: 20.6, lng: 79.0 },
  { name: "Hematite", chakra: "Root", element: "Earth", color: "Metallic Gray/Black", properties: "Grounding, balance, focus, blood circulation, courage", origin: "Brazil, Australia, England", zodiac: "Aries, Aquarius", hardness: "5.5-6.5", rarity: "Common", mantra: "I am grounded in strength and balanced in all I do", region: "Oceania", lat: -25.3, lng: 133.8 },
  { name: "Opal", chakra: "Crown/All", element: "Water", color: "Multi/Iridescent", properties: "Inspiration, creativity, emotional expression, cosmic connection", origin: "Australia, Ethiopia, Mexico", zodiac: "Libra, Scorpio, Cancer", hardness: "5.5-6.5", rarity: "Rare", mantra: "I radiate with creative inspiration and cosmic wonder", region: "Oceania", lat: -28.7, lng: 134.2 },
  { name: "Pyrite", chakra: "Solar Plexus", element: "Fire/Earth", color: "Metallic Gold", properties: "Abundance, willpower, protection, confidence, manifestation", origin: "Spain, Peru, Italy", zodiac: "Leo, Aries", hardness: "6-6.5", rarity: "Common", mantra: "I attract wealth and manifest my golden potential", region: "Europe", lat: 40.5, lng: -3.7 },
  { name: "Chrysocolla", chakra: "Throat/Heart", element: "Water", color: "Blue-Green", properties: "Communication, feminine power, tranquility, teaching", origin: "Peru, Congo, Chile", zodiac: "Taurus, Gemini, Virgo", hardness: "2-4", rarity: "Uncommon", mantra: "I communicate with gentle power and teach through love", region: "South America", lat: -9.2, lng: -75.0 },
  { name: "Kyanite", chakra: "Throat/Third Eye", element: "Air", color: "Blue", properties: "Alignment, tranquility, psychic abilities, never needs cleansing", origin: "Brazil, India, Kenya", zodiac: "Aries, Taurus, Libra", hardness: "4.5-7", rarity: "Uncommon", mantra: "I am aligned with truth and my energy flows freely", region: "Africa", lat: -1.3, lng: 36.8 },
  { name: "Peridot", chakra: "Heart/Solar Plexus", element: "Earth", color: "Green/Olive", properties: "Joy, abundance, renewal, stress relief, detox", origin: "Egypt, Myanmar, Pakistan", zodiac: "Leo, Virgo, Scorpio", hardness: "6.5-7", rarity: "Uncommon", mantra: "I embrace joy and renewal in every moment of life", region: "Africa", lat: 26.8, lng: 30.8 },
  { name: "Celestite", chakra: "Crown/Third Eye/Throat", element: "Air", color: "Light Blue", properties: "Divine connection, peace, dream recall, angelic communication", origin: "Madagascar, Mexico, Poland", zodiac: "Gemini, Libra", hardness: "3-3.5", rarity: "Uncommon", mantra: "I connect with celestial realms and receive divine guidance", region: "Africa", lat: -18.9, lng: 47.5 },
  { name: "Tanzanite", chakra: "Third Eye/Throat/Crown", element: "Air", color: "Blue-Violet", properties: "Spiritual awakening, higher consciousness, transformation", origin: "Tanzania (exclusive)", zodiac: "Sagittarius, Gemini, Libra", hardness: "6.5-7", rarity: "Very Rare", mantra: "I ascend to higher consciousness with every breath", region: "Africa", lat: -3.4, lng: 37.3 },
  { name: "Larimar", chakra: "Throat/Heart/Crown", element: "Water/Air", color: "Light Blue/White", properties: "Serenity, communication, divine feminine, stress relief", origin: "Dominican Republic (exclusive)", zodiac: "Leo, Pisces", hardness: "4.5-5", rarity: "Rare", mantra: "I flow with oceanic peace and express my highest truth", region: "Caribbean", lat: 18.7, lng: -70.2 },
  { name: "Moldavite", chakra: "Heart/Third Eye/Crown", element: "All", color: "Forest Green", properties: "Transformation, cosmic connection, rapid spiritual growth", origin: "Czech Republic (meteorite impact)", zodiac: "All signs (Scorpio esp.)", hardness: "5.5", rarity: "Very Rare", mantra: "I embrace cosmic transformation and accelerated evolution", region: "Europe", lat: 49.8, lng: 15.5 },
  { name: "Lepidolite", chakra: "Third Eye/Crown/Heart", element: "Water", color: "Purple/Lavender", properties: "Anxiety relief, emotional balance, sleep, transition support", origin: "Brazil, Madagascar, USA", zodiac: "Libra, Pisces", hardness: "2.5-3.5", rarity: "Uncommon", mantra: "I release anxiety and embrace peaceful transformation", region: "South America", lat: -14.2, lng: -51.9 },
  { name: "Howlite", chakra: "Crown", element: "Air", color: "White/Gray veined", properties: "Patience, calm, sleep aid, awareness, memory", origin: "Canada, USA, Turkey", zodiac: "Gemini, Virgo", hardness: "3.5", rarity: "Common", mantra: "I rest in patience and calm awareness flows through me", region: "North America", lat: 56.1, lng: -106.3 },
  { name: "Sunstone", chakra: "Sacral/Solar Plexus", element: "Fire", color: "Orange/Gold sparkle", properties: "Joy, leadership, vitality, personal power, independence", origin: "India, Norway, Canada", zodiac: "Leo, Libra", hardness: "6-7.2", rarity: "Uncommon", mantra: "I shine with radiant joy and step into my personal power", region: "Europe", lat: 60.5, lng: 8.5 },
  { name: "Bloodstone", chakra: "Root/Heart", element: "Earth", color: "Dark Green/Red spots", properties: "Courage, vitality, purification, grounding, strength", origin: "India, Australia, Brazil", zodiac: "Aries, Pisces, Libra", hardness: "6.5-7", rarity: "Common", mantra: "I am filled with vital strength and purified courage", region: "Asia", lat: 20.6, lng: 79.0 },
  { name: "Charoite", chakra: "Crown/Third Eye/Heart", element: "Water/Air", color: "Purple swirl", properties: "Transformation, insight, overcoming fear, spiritual healing", origin: "Russia (Siberia exclusive)", zodiac: "Scorpio, Sagittarius", hardness: "5-6", rarity: "Rare", mantra: "I transform fear into insight and embrace spiritual healing", region: "Asia", lat: 61.5, lng: 134.5 },
  { name: "Azurite", chakra: "Third Eye", element: "Air", color: "Deep Blue", properties: "Insight, vision, intellect, psychic development", origin: "Morocco, China, Australia", zodiac: "Sagittarius, Aquarius", hardness: "3.5-4", rarity: "Uncommon", mantra: "I see beyond the visible and trust my psychic vision", region: "Africa", lat: 31.8, lng: -7.1 },
  { name: "Prehnite", chakra: "Heart/Solar Plexus", element: "Earth/Water", color: "Pale Green", properties: "Unconditional love, healing, prophecy, calm", origin: "South Africa, Australia, China", zodiac: "Libra, Virgo", hardness: "6-6.5", rarity: "Uncommon", mantra: "I heal with unconditional love and trust divine prophecy", region: "Africa", lat: -30.6, lng: 22.9 },
];

export const CHAKRAS = [
  { name: "Root", color: "#EF4444", frequency: 256, note: "C", element: "Earth", location: "Base of spine" },
  { name: "Sacral", color: "#F97316", frequency: 288, note: "D", element: "Water", location: "Lower abdomen" },
  { name: "Solar Plexus", color: "#EAB308", frequency: 320, note: "E", element: "Fire", location: "Upper abdomen" },
  { name: "Heart", color: "#22C55E", frequency: 341, note: "F", element: "Air", location: "Center of chest" },
  { name: "Throat", color: "#3B82F6", frequency: 384, note: "G", element: "Ether", location: "Throat" },
  { name: "Third Eye", color: "#6366F1", frequency: 426, note: "A", element: "Light", location: "Between eyebrows" },
  { name: "Crown", color: "#A855F7", frequency: 480, note: "B", element: "Cosmic", location: "Top of head" },
];

export const MOON_PHASES = [
  { name: "New Moon", emoji: "🌑", crystals: ["Obsidian", "Moonstone", "Labradorite"], guidance: "Set new intentions and plant seeds for growth. A powerful time for shadow work and new beginnings." },
  { name: "Waxing Crescent", emoji: "🌒", crystals: ["Citrine", "Carnelian", "Aventurine"], guidance: "Take initial steps toward your goals. Build momentum with courage and optimism." },
  { name: "First Quarter", emoji: "🌓", crystals: ["Tiger's Eye", "Pyrite", "Garnet"], guidance: "Push through obstacles with determination. Take decisive action on your intentions." },
  { name: "Waxing Gibbous", emoji: "🌔", crystals: ["Jade", "Fluorite", "Amazonite"], guidance: "Refine your plans and adjust course. Trust the process and remain patient." },
  { name: "Full Moon", emoji: "🌕", crystals: ["Selenite", "Clear Quartz", "Moonstone"], guidance: "Harvest results and celebrate progress. Full moon energy amplifies all crystal healing work." },
  { name: "Waning Gibbous", emoji: "🌖", crystals: ["Amethyst", "Lepidolite", "Smoky Quartz"], guidance: "Share wisdom and practice gratitude. Release what you've learned into the world." },
  { name: "Last Quarter", emoji: "🌗", crystals: ["Black Tourmaline", "Hematite", "Obsidian"], guidance: "Release old patterns and let go. Clear energy blocks and prepare for renewal." },
  { name: "Waning Crescent", emoji: "🌘", crystals: ["Howlite", "Celestite", "Selenite"], guidance: "Rest, reflect, and recharge. This is a time for deep meditation and surrender." },
];

export function getMoonPhase(): typeof MOON_PHASES[number] {
  const now = new Date();
  const year = now.getFullYear();
  const month = now.getMonth() + 1;
  const day = now.getDate();
  let c = 0, e = 0, jd = 0, b = 0;
  if (month < 3) { c = year - 1; e = month + 12; } else { c = year; e = month; }
  jd = Math.floor(365.25 * (c + 4716)) + Math.floor(30.6001 * (e + 1)) + day - 1524.5;
  const daysSinceNew = jd - 2451549.5;
  const newMoons = daysSinceNew / 29.53058867;
  b = Math.floor((newMoons - Math.floor(newMoons)) * 8);
  return MOON_PHASES[b % 8];
}

export const HEALING_PATHS = [
  { id: "stress", name: "Stress Relief", emoji: "🧘", crystals: ["Amethyst", "Lepidolite", "Howlite"], steps: ["Find a quiet space and hold your chosen crystal", "Close your eyes and take 10 deep breaths", "Visualize stress leaving as dark smoke with each exhale", "Feel the crystal absorbing tension from your body", "Set an intention: 'I release all stress and embrace peace'", "Sit in stillness for 5 minutes", "Thank your crystal and cleanse it with intention"] },
  { id: "love", name: "Attract Love", emoji: "💕", crystals: ["Rose Quartz", "Rhodonite", "Garnet"], steps: ["Hold rose quartz to your heart center", "Breathe deeply and feel your heart opening", "Visualize pink light radiating from your chest", "Affirm: 'I am worthy of deep, authentic love'", "List 5 qualities you wish to attract in a partner", "Place the crystal under your pillow tonight", "Practice self-love rituals daily this week"] },
  { id: "abundance", name: "Abundance & Wealth", emoji: "💎", crystals: ["Citrine", "Pyrite", "Jade"], steps: ["Hold citrine in your dominant hand", "Visualize golden light filling your solar plexus", "State your financial intentions clearly and specifically", "Write down 3 abundance affirmations", "Place pyrite on your desk or workspace", "Carry citrine in your wallet or purse", "Practice gratitude for current abundance daily"] },
  { id: "protection", name: "Energy Protection", emoji: "🛡️", crystals: ["Black Tourmaline", "Obsidian", "Smoky Quartz"], steps: ["Hold black tourmaline and ground your energy", "Visualize a protective shield of black light around you", "Affirm: 'I am protected from all negative energy'", "Place tourmaline by your front door", "Carry obsidian when visiting crowded places", "Cleanse your protective crystals weekly", "Set boundaries with confidence and clarity"] },
  { id: "creativity", name: "Creative Flow", emoji: "🎨", crystals: ["Carnelian", "Sunstone", "Labradorite"], steps: ["Hold carnelian at your sacral chakra (lower abdomen)", "Breathe orange light into your creative center", "Free-write or sketch for 10 minutes without judgment", "Place sunstone in your creative workspace", "Meditate with labradorite for inspiration", "Create something small each day this week", "Celebrate your creative expression regardless of outcome"] },
];

export const CLEANSING_RITUALS = [
  { id: "moonlight", name: "Full Moon Charging", emoji: "🌕", duration: "Overnight", steps: ["Check the lunar calendar for the next full moon", "Gather crystals that need charging", "Clean them gently with a soft cloth", "Place them on a windowsill or outside under moonlight", "Set an intention for each crystal", "Leave overnight (remove before direct sunlight)", "Thank the moon and your crystals in the morning"] },
  { id: "sage", name: "Sage Smoke Cleansing", emoji: "🌿", duration: "10-15 minutes", steps: ["Open a window for ventilation", "Light your sage bundle and let it smolder", "Hold each crystal in the smoke for 30 seconds", "Move the smoke clockwise around the crystal", "Set a cleansing intention while doing so", "Visualize negative energy being carried away", "Extinguish sage safely when finished"] },
  { id: "sound", name: "Sound Cleansing", emoji: "🔔", duration: "5-10 minutes", steps: ["Place crystals in a circle on a flat surface", "Use a singing bowl, bell, or tuning fork", "Strike the instrument near each crystal", "Let the sound waves wash over the crystals", "Move clockwise around the circle", "Feel the vibration clearing stagnant energy", "End with a moment of silence and gratitude"] },
  { id: "earth", name: "Earth Burial", emoji: "🌍", duration: "24 hours", steps: ["Choose a safe spot in your garden or use a pot of soil", "Wrap crystal in a natural cloth (optional)", "Bury it 2-3 inches deep in clean soil", "Mark the spot so you can find it", "Leave for 24 hours (up to 3 days for deep cleansing)", "Dig up and rinse with clean water", "Dry with a soft cloth and feel the renewed energy"] },
  { id: "water", name: "Running Water Cleanse", emoji: "💧", duration: "1-2 minutes", steps: ["Check that your crystal is water-safe (avoid selenite, malachite, etc.)", "Hold crystal under cool running water", "Natural streams are ideal, but tap water works", "Visualize impurities being washed away", "Hold for 1-2 minutes while setting intentions", "Pat dry with a clean cloth", "Place in sunlight briefly to recharge (avoid prolonged sun)"] },
];
