// AUTO-GENERATED by scripts/generate-uni-catalog.mjs — do not edit by hand.
// Searchable catalog of app destinations (routes + sub-features/categories).

export interface UniCatalogEntry {
  path: string;
  label: string;
  keywords: string[];
}

export const UNI_CATALOG: UniCatalogEntry[] = [
  {
    "path": "/",
    "label": "Home",
    "keywords": []
  },
  {
    "path": "/about",
    "label": "About",
    "keywords": [
      "about"
    ]
  },
  {
    "path": "/about-platform",
    "label": "About Platform",
    "keywords": [
      "about",
      "platform"
    ]
  },
  {
    "path": "/account/billing",
    "label": "Account — Billing",
    "keywords": [
      "account",
      "billing"
    ]
  },
  {
    "path": "/account/credits",
    "label": "Account — Credits",
    "keywords": [
      "account",
      "credits"
    ]
  },
  {
    "path": "/account/parental",
    "label": "Account — Parental",
    "keywords": [
      "account",
      "parental"
    ]
  },
  {
    "path": "/account/subscriptions",
    "label": "Account — Subscriptions",
    "keywords": [
      "account",
      "subscriptions"
    ]
  },
  {
    "path": "/account/verification",
    "label": "Account — Verification",
    "keywords": [
      "account",
      "verification"
    ]
  },
  {
    "path": "/admin",
    "label": "Admin",
    "keywords": [
      "admin"
    ]
  },
  {
    "path": "/admin/affiliate-tiers",
    "label": "Admin — Affiliate Tiers",
    "keywords": [
      "admin",
      "affiliate",
      "tiers"
    ]
  },
  {
    "path": "/admin/audit-log",
    "label": "Admin — Audit Log",
    "keywords": [
      "admin",
      "audit",
      "log"
    ]
  },
  {
    "path": "/admin/battle-royale-payouts",
    "label": "Admin — Battle Royale Payouts",
    "keywords": [
      "admin",
      "battle",
      "royale",
      "payouts"
    ]
  },
  {
    "path": "/admin/bazaar-trust",
    "label": "Admin — Bazaar Trust",
    "keywords": [
      "admin",
      "bazaar",
      "trust"
    ]
  },
  {
    "path": "/admin/brand-campaigns",
    "label": "Admin — Brand Campaigns",
    "keywords": [
      "admin",
      "brand",
      "campaigns"
    ]
  },
  {
    "path": "/admin/brand-moderation",
    "label": "Admin — Brand Moderation",
    "keywords": [
      "admin",
      "brand",
      "moderation"
    ]
  },
  {
    "path": "/admin/bug-reports",
    "label": "Admin — Bug Reports",
    "keywords": [
      "admin",
      "bug",
      "reports"
    ]
  },
  {
    "path": "/admin/button-tester",
    "label": "Admin — Button Tester",
    "keywords": [
      "admin",
      "button",
      "tester"
    ]
  },
  {
    "path": "/admin/challenge-subs",
    "label": "Admin — Challenge Subs",
    "keywords": [
      "admin",
      "challenge",
      "subs"
    ]
  },
  {
    "path": "/admin/challenge-subscribers",
    "label": "Admin — Challenge Subscribers",
    "keywords": [
      "admin",
      "challenge",
      "subscribers"
    ]
  },
  {
    "path": "/admin/client-errors",
    "label": "Admin — Client Errors",
    "keywords": [
      "admin",
      "client",
      "errors"
    ]
  },
  {
    "path": "/admin/club-shipping",
    "label": "Admin — Club Shipping",
    "keywords": [
      "admin",
      "club",
      "shipping"
    ]
  },
  {
    "path": "/admin/cohort-retention",
    "label": "Admin — Cohort Retention",
    "keywords": [
      "admin",
      "cohort",
      "retention"
    ]
  },
  {
    "path": "/admin/comedy-payouts",
    "label": "Admin — Comedy Payouts",
    "keywords": [
      "admin",
      "comedy",
      "payouts"
    ]
  },
  {
    "path": "/admin/concert-earnings",
    "label": "Admin — Concert Earnings",
    "keywords": [
      "admin",
      "concert",
      "earnings"
    ]
  },
  {
    "path": "/admin/contest-periods",
    "label": "Admin — Contest Periods",
    "keywords": [
      "admin",
      "contest",
      "periods"
    ]
  },
  {
    "path": "/admin/corporate-inquiries",
    "label": "Admin — Corporate Inquiries",
    "keywords": [
      "admin",
      "corporate",
      "inquiries"
    ]
  },
  {
    "path": "/admin/coupon-disputes",
    "label": "Admin — Coupon Disputes",
    "keywords": [
      "admin",
      "coupon",
      "disputes"
    ]
  },
  {
    "path": "/admin/crawler",
    "label": "Admin — Crawler",
    "keywords": [
      "admin",
      "crawler"
    ]
  },
  {
    "path": "/admin/credits-ledger",
    "label": "Admin — Credits Ledger",
    "keywords": [
      "admin",
      "credits",
      "ledger"
    ]
  },
  {
    "path": "/admin/dating-moderation",
    "label": "Admin — Dating Moderation",
    "keywords": [
      "admin",
      "dating",
      "moderation"
    ]
  },
  {
    "path": "/admin/disputes",
    "label": "Admin — Disputes",
    "keywords": [
      "admin",
      "disputes"
    ]
  },
  {
    "path": "/admin/dunning",
    "label": "Admin — Dunning",
    "keywords": [
      "admin",
      "dunning"
    ]
  },
  {
    "path": "/admin/edge-monitoring",
    "label": "Admin — Edge Monitoring",
    "keywords": [
      "admin",
      "edge",
      "monitoring"
    ]
  },
  {
    "path": "/admin/edge-tester",
    "label": "Admin — Edge Tester",
    "keywords": [
      "admin",
      "edge",
      "tester"
    ]
  },
  {
    "path": "/admin/engagement",
    "label": "Admin — Engagement",
    "keywords": [
      "admin",
      "engagement"
    ]
  },
  {
    "path": "/admin/error-logs",
    "label": "Admin — Error Logs",
    "keywords": [
      "admin",
      "error",
      "logs"
    ]
  },
  {
    "path": "/admin/fanclub-verify-audit",
    "label": "Admin — Fanclub Verify Audit",
    "keywords": [
      "admin",
      "fanclub",
      "verify",
      "audit"
    ]
  },
  {
    "path": "/admin/founders",
    "label": "Admin — Founders",
    "keywords": [
      "admin",
      "founders"
    ]
  },
  {
    "path": "/admin/influencer-payouts",
    "label": "Admin — Influencer Payouts",
    "keywords": [
      "admin",
      "influencer",
      "payouts"
    ]
  },
  {
    "path": "/admin/iq",
    "label": "Admin — Iq",
    "keywords": [
      "admin",
      "iq"
    ]
  },
  {
    "path": "/admin/iq-analytics",
    "label": "Admin — Iq Analytics",
    "keywords": [
      "admin",
      "iq",
      "analytics"
    ]
  },
  {
    "path": "/admin/kitchenstars-payouts",
    "label": "Admin — Kitchenstars Payouts",
    "keywords": [
      "admin",
      "kitchenstars",
      "payouts"
    ]
  },
  {
    "path": "/admin/kyc",
    "label": "Admin — Kyc",
    "keywords": [
      "admin",
      "kyc"
    ]
  },
  {
    "path": "/admin/masterchef-payouts",
    "label": "Admin — Masterchef Payouts",
    "keywords": [
      "admin",
      "masterchef",
      "payouts"
    ]
  },
  {
    "path": "/admin/megatalent-moderation",
    "label": "Admin — Megatalent Moderation",
    "keywords": [
      "admin",
      "megatalent",
      "moderation"
    ]
  },
  {
    "path": "/admin/megatalent-payouts",
    "label": "Admin — Megatalent Payouts",
    "keywords": [
      "admin",
      "megatalent",
      "payouts"
    ]
  },
  {
    "path": "/admin/monetag-stats",
    "label": "Admin — Monetag Stats",
    "keywords": [
      "admin",
      "monetag",
      "stats"
    ]
  },
  {
    "path": "/admin/musician-verifications",
    "label": "Admin — Musician Verifications",
    "keywords": [
      "admin",
      "musician",
      "verifications"
    ]
  },
  {
    "path": "/admin/ops-tools",
    "label": "Admin — Ops Tools",
    "keywords": [
      "admin",
      "ops",
      "tools"
    ]
  },
  {
    "path": "/admin/pauses",
    "label": "Admin — Pauses",
    "keywords": [
      "admin",
      "pauses"
    ]
  },
  {
    "path": "/admin/payment-dashboard",
    "label": "Admin — Payment Dashboard",
    "keywords": [
      "admin",
      "payment",
      "dashboard"
    ]
  },
  {
    "path": "/admin/performance",
    "label": "Admin — Performance",
    "keywords": [
      "admin",
      "performance"
    ]
  },
  {
    "path": "/admin/platform-earnings",
    "label": "Admin — Platform Earnings",
    "keywords": [
      "admin",
      "platform",
      "earnings"
    ]
  },
  {
    "path": "/admin/platform-withdrawals",
    "label": "Admin — Platform Withdrawals",
    "keywords": [
      "admin",
      "platform",
      "withdrawals"
    ]
  },
  {
    "path": "/admin/premium-videos",
    "label": "Admin — Premium Videos",
    "keywords": [
      "admin",
      "premium",
      "videos"
    ]
  },
  {
    "path": "/admin/pwa-stats",
    "label": "Admin — Pwa Stats",
    "keywords": [
      "admin",
      "pwa",
      "stats"
    ]
  },
  {
    "path": "/admin/reconciliation",
    "label": "Admin — Reconciliation",
    "keywords": [
      "admin",
      "reconciliation"
    ]
  },
  {
    "path": "/admin/referral-fraud",
    "label": "Admin — Referral Fraud",
    "keywords": [
      "admin",
      "referral",
      "fraud"
    ]
  },
  {
    "path": "/admin/referral-funnel",
    "label": "Admin — Referral Funnel",
    "keywords": [
      "admin",
      "referral",
      "funnel"
    ]
  },
  {
    "path": "/admin/refunds",
    "label": "Admin — Refunds",
    "keywords": [
      "admin",
      "refunds"
    ]
  },
  {
    "path": "/admin/rewards-audit",
    "label": "Admin — Rewards Audit",
    "keywords": [
      "admin",
      "rewards",
      "audit"
    ]
  },
  {
    "path": "/admin/rewards-seed",
    "label": "Admin — Rewards Seed",
    "keywords": [
      "admin",
      "rewards",
      "seed"
    ]
  },
  {
    "path": "/admin/route-errors",
    "label": "Admin — Route Errors",
    "keywords": [
      "admin",
      "route",
      "errors"
    ]
  },
  {
    "path": "/admin/sca",
    "label": "Admin — Sca",
    "keywords": [
      "admin",
      "sca"
    ]
  },
  {
    "path": "/admin/security-scan",
    "label": "Admin — Security Scan",
    "keywords": [
      "admin",
      "security",
      "scan"
    ]
  },
  {
    "path": "/admin/skills-reviews",
    "label": "Admin — Skills Reviews",
    "keywords": [
      "admin",
      "skills",
      "reviews"
    ]
  },
  {
    "path": "/admin/smoke-test",
    "label": "Admin — Smoke Test",
    "keywords": [
      "admin",
      "smoke",
      "test"
    ]
  },
  {
    "path": "/admin/sports-matches",
    "label": "Admin — Sports Matches",
    "keywords": [
      "admin",
      "sports",
      "matches"
    ]
  },
  {
    "path": "/admin/subscription-analytics",
    "label": "Admin — Subscription Analytics",
    "keywords": [
      "admin",
      "subscription",
      "analytics"
    ]
  },
  {
    "path": "/admin/support",
    "label": "Admin — Support",
    "keywords": [
      "admin",
      "support"
    ]
  },
  {
    "path": "/admin/tipsters",
    "label": "Admin — Tipsters",
    "keywords": [
      "admin",
      "tipsters"
    ]
  },
  {
    "path": "/admin/transactions",
    "label": "Admin — Transactions",
    "keywords": [
      "admin",
      "transactions"
    ]
  },
  {
    "path": "/admin/unlock-videos",
    "label": "Admin — Unlock Videos",
    "keywords": [
      "admin",
      "unlock",
      "videos"
    ]
  },
  {
    "path": "/admin/users-overview",
    "label": "Admin — Users Overview",
    "keywords": [
      "admin",
      "users",
      "overview"
    ]
  },
  {
    "path": "/admin/verifications",
    "label": "Admin — Verifications",
    "keywords": [
      "admin",
      "verifications"
    ]
  },
  {
    "path": "/admin/vitals",
    "label": "Admin — Vitals",
    "keywords": [
      "admin",
      "vitals"
    ]
  },
  {
    "path": "/admin/winback",
    "label": "Admin — Winback",
    "keywords": [
      "admin",
      "winback"
    ]
  },
  {
    "path": "/admin/withdrawals",
    "label": "Admin — Withdrawals",
    "keywords": [
      "admin",
      "withdrawals"
    ]
  },
  {
    "path": "/admin/xp-audit",
    "label": "Admin — Xp Audit",
    "keywords": [
      "admin",
      "xp",
      "audit"
    ]
  },
  {
    "path": "/admin/xp-audit/reconciliation",
    "label": "Admin — Xp Audit — Reconciliation",
    "keywords": [
      "admin",
      "xp",
      "audit",
      "reconciliation"
    ]
  },
  {
    "path": "/adult-puzzles",
    "label": "Adult Puzzles",
    "keywords": [
      "adult",
      "puzzles"
    ]
  },
  {
    "path": "/ai",
    "label": "Ai",
    "keywords": [
      "ai"
    ]
  },
  {
    "path": "/ai-clone",
    "label": "Ai Clone",
    "keywords": [
      "ai",
      "clone"
    ]
  },
  {
    "path": "/ai-credits",
    "label": "Ai Credits",
    "keywords": [
      "ai",
      "credits"
    ]
  },
  {
    "path": "/ai-credits-store",
    "label": "Ai Credits Store",
    "keywords": [
      "ai",
      "credits",
      "store"
    ]
  },
  {
    "path": "/ai-generation",
    "label": "Ai Generation",
    "keywords": [
      "ai",
      "generation"
    ]
  },
  {
    "path": "/ai-mentor",
    "label": "Ai Mentor",
    "keywords": [
      "ai",
      "mentor"
    ]
  },
  {
    "path": "/ai-mentor/hub",
    "label": "Ai Mentor — Hub",
    "keywords": [
      "ai",
      "mentor",
      "hub"
    ]
  },
  {
    "path": "/ai-mentor/premium",
    "label": "Ai Mentor — Premium",
    "keywords": [
      "ai",
      "mentor",
      "premium"
    ]
  },
  {
    "path": "/ai-tattoo",
    "label": "Ai Tattoo",
    "keywords": [
      "ai",
      "tattoo"
    ]
  },
  {
    "path": "/analyzer",
    "label": "Analyzer",
    "keywords": [
      "analyzer"
    ]
  },
  {
    "path": "/analyzer/collections",
    "label": "Analyzer — Collections",
    "keywords": [
      "analyzer",
      "collections"
    ]
  },
  {
    "path": "/analyzer/history",
    "label": "Analyzer — History",
    "keywords": [
      "analyzer",
      "history"
    ]
  },
  {
    "path": "/analyzer/pricing",
    "label": "Analyzer — Pricing",
    "keywords": [
      "analyzer",
      "pricing"
    ]
  },
  {
    "path": "/anonymous-date",
    "label": "Anonymous Date",
    "keywords": [
      "anonymous",
      "date"
    ]
  },
  {
    "path": "/anonymous-dating",
    "label": "Anonymous Dating",
    "keywords": [
      "anonymous",
      "dating"
    ]
  },
  {
    "path": "/antique-appraisal",
    "label": "Antique Appraisal",
    "keywords": [
      "antique",
      "appraisal"
    ]
  },
  {
    "path": "/arena-hub",
    "label": "Arena Hub",
    "keywords": [
      "arena",
      "hub"
    ]
  },
  {
    "path": "/astrology",
    "label": "Astrology",
    "keywords": [
      "astrology"
    ]
  },
  {
    "path": "/auction",
    "label": "Auction",
    "keywords": [
      "auction"
    ]
  },
  {
    "path": "/auction/create",
    "label": "Auction — Create",
    "keywords": [
      "auction",
      "create"
    ]
  },
  {
    "path": "/auction/messages",
    "label": "Auction — Messages",
    "keywords": [
      "auction",
      "messages"
    ]
  },
  {
    "path": "/auction/my",
    "label": "Auction — My",
    "keywords": [
      "auction",
      "my"
    ]
  },
  {
    "path": "/auth",
    "label": "Auth",
    "keywords": [
      "auth"
    ]
  },
  {
    "path": "/auth/callback",
    "label": "Auth — Callback",
    "keywords": [
      "auth",
      "callback"
    ]
  },
  {
    "path": "/bazaar",
    "label": "Bazaar",
    "keywords": [
      "bazaar"
    ]
  },
  {
    "path": "/bazaar/create",
    "label": "Bazaar — Create",
    "keywords": [
      "bazaar",
      "create"
    ]
  },
  {
    "path": "/bazaar/messages",
    "label": "Bazaar — Messages",
    "keywords": [
      "bazaar",
      "messages"
    ]
  },
  {
    "path": "/bazaar/my",
    "label": "Bazaar — My",
    "keywords": [
      "bazaar",
      "my"
    ]
  },
  {
    "path": "/bazaar/saved-searches",
    "label": "Bazaar — Saved Searches",
    "keywords": [
      "bazaar",
      "saved",
      "searches"
    ]
  },
  {
    "path": "/beauty",
    "label": "Beauty",
    "keywords": [
      "beauty"
    ]
  },
  {
    "path": "/beauty-studio",
    "label": "Beauty Studio",
    "keywords": [
      "beauty",
      "studio"
    ]
  },
  {
    "path": "/become-creator",
    "label": "Become Creator",
    "keywords": [
      "become",
      "creator"
    ]
  },
  {
    "path": "/bedtime-stories",
    "label": "Bedtime Stories",
    "keywords": [
      "bedtime",
      "stories"
    ]
  },
  {
    "path": "/best-friend",
    "label": "Best Friend",
    "keywords": [
      "best",
      "friend"
    ]
  },
  {
    "path": "/billing",
    "label": "Billing",
    "keywords": [
      "billing"
    ]
  },
  {
    "path": "/booking",
    "label": "Booking",
    "keywords": [
      "booking"
    ]
  },
  {
    "path": "/brain-duel",
    "label": "Brain Duel",
    "keywords": [
      "brain",
      "duel"
    ]
  },
  {
    "path": "/brain-duel/hub",
    "label": "Brain Duel — Hub",
    "keywords": [
      "brain",
      "duel",
      "hub"
    ]
  },
  {
    "path": "/brand-arena",
    "label": "Brand Arena",
    "keywords": [
      "brand",
      "arena"
    ]
  },
  {
    "path": "/brand-battle",
    "label": "Brand Battle",
    "keywords": [
      "brand",
      "battle"
    ]
  },
  {
    "path": "/brand-battle/hub",
    "label": "Brand Battle — Hub",
    "keywords": [
      "brand",
      "battle",
      "hub"
    ]
  },
  {
    "path": "/brand-builder",
    "label": "Brand Builder",
    "keywords": [
      "brand",
      "builder"
    ]
  },
  {
    "path": "/brand-dashboard",
    "label": "Brand Dashboard",
    "keywords": [
      "brand",
      "dashboard"
    ]
  },
  {
    "path": "/brand-kits",
    "label": "Brand Kits",
    "keywords": [
      "brand",
      "kits"
    ]
  },
  {
    "path": "/card-collections",
    "label": "Card Collections",
    "keywords": [
      "card",
      "collections"
    ]
  },
  {
    "path": "/card-collections/gallery",
    "label": "Card Collections — Gallery",
    "keywords": [
      "card",
      "collections",
      "gallery"
    ]
  },
  {
    "path": "/certification-programs",
    "label": "Certification Programs",
    "keywords": [
      "certification",
      "programs"
    ]
  },
  {
    "path": "/challenges",
    "label": "Challenges",
    "keywords": [
      "challenges"
    ]
  },
  {
    "path": "/character-arena",
    "label": "Character Arena",
    "keywords": [
      "character",
      "arena"
    ]
  },
  {
    "path": "/character-gallery",
    "label": "Character Gallery",
    "keywords": [
      "character",
      "gallery"
    ]
  },
  {
    "path": "/character-inventory",
    "label": "Character Inventory",
    "keywords": [
      "character",
      "inventory"
    ]
  },
  {
    "path": "/chef-chat",
    "label": "Chef Chat",
    "keywords": [
      "chef",
      "chat"
    ]
  },
  {
    "path": "/choose-adventure",
    "label": "Choose Adventure",
    "keywords": [
      "choose",
      "adventure"
    ]
  },
  {
    "path": "/clip-battles",
    "label": "Clip Battles",
    "keywords": [
      "clip",
      "battles"
    ]
  },
  {
    "path": "/close-friends",
    "label": "Close Friends",
    "keywords": [
      "close",
      "friends"
    ]
  },
  {
    "path": "/club",
    "label": "Club",
    "keywords": [
      "club"
    ]
  },
  {
    "path": "/club/card",
    "label": "Club — Card",
    "keywords": [
      "club",
      "card"
    ]
  },
  {
    "path": "/coffee",
    "label": "Coffee",
    "keywords": [
      "coffee"
    ]
  },
  {
    "path": "/coffee/buddy",
    "label": "Coffee — Buddy",
    "keywords": [
      "coffee",
      "buddy"
    ]
  },
  {
    "path": "/coffee/checkins",
    "label": "Coffee — Checkins",
    "keywords": [
      "coffee",
      "checkins"
    ]
  },
  {
    "path": "/coffee/leaderboard",
    "label": "Coffee — Leaderboard",
    "keywords": [
      "coffee",
      "leaderboard"
    ]
  },
  {
    "path": "/coloring-pages",
    "label": "Coloring Pages",
    "keywords": [
      "coloring",
      "pages"
    ]
  },
  {
    "path": "/comedian-dashboard",
    "label": "Comedian Dashboard",
    "keywords": [
      "comedian",
      "dashboard"
    ]
  },
  {
    "path": "/comedy-club",
    "label": "Comedy Club",
    "keywords": [
      "comedy",
      "club"
    ]
  },
  {
    "path": "/community",
    "label": "Community",
    "keywords": [
      "community"
    ]
  },
  {
    "path": "/companions",
    "label": "Companions",
    "keywords": [
      "companions"
    ]
  },
  {
    "path": "/contact",
    "label": "Contact",
    "keywords": [
      "contact"
    ]
  },
  {
    "path": "/content-studio",
    "label": "Content Studio",
    "keywords": [
      "content",
      "studio"
    ]
  },
  {
    "path": "/cooking",
    "label": "Cooking",
    "keywords": [
      "cooking"
    ]
  },
  {
    "path": "/cooking-ai",
    "label": "Cooking Ai",
    "keywords": [
      "cooking",
      "ai"
    ]
  },
  {
    "path": "/corporate-events",
    "label": "Corporate Events",
    "keywords": [
      "corporate",
      "events"
    ]
  },
  {
    "path": "/coupon-marketplace",
    "label": "Coupon Marketplace",
    "keywords": [
      "coupon",
      "marketplace"
    ]
  },
  {
    "path": "/coupon-marketplace/create",
    "label": "Coupon Marketplace — Create",
    "keywords": [
      "coupon",
      "marketplace",
      "create"
    ]
  },
  {
    "path": "/coupon-marketplace/messages",
    "label": "Coupon Marketplace — Messages",
    "keywords": [
      "coupon",
      "marketplace",
      "messages"
    ]
  },
  {
    "path": "/coupon-marketplace/my",
    "label": "Coupon Marketplace — My",
    "keywords": [
      "coupon",
      "marketplace",
      "my"
    ]
  },
  {
    "path": "/coupons/my",
    "label": "Coupons — My",
    "keywords": [
      "coupons",
      "my"
    ]
  },
  {
    "path": "/course-creator",
    "label": "Course Creator",
    "keywords": [
      "course",
      "creator"
    ]
  },
  {
    "path": "/courses",
    "label": "Courses",
    "keywords": [
      "courses"
    ]
  },
  {
    "path": "/create-character",
    "label": "Create Character",
    "keywords": [
      "create",
      "character"
    ]
  },
  {
    "path": "/creative-forge",
    "label": "Creative Forge",
    "keywords": [
      "creative",
      "forge"
    ]
  },
  {
    "path": "/creative-writing",
    "label": "Creative Writing",
    "keywords": [
      "creative",
      "writing"
    ]
  },
  {
    "path": "/creator-analytics",
    "label": "Creator Analytics",
    "keywords": [
      "creator",
      "analytics"
    ]
  },
  {
    "path": "/creator-dashboard",
    "label": "Creator Dashboard",
    "keywords": [
      "creator",
      "dashboard"
    ]
  },
  {
    "path": "/creator-payouts",
    "label": "Creator Payouts",
    "keywords": [
      "creator",
      "payouts"
    ]
  },
  {
    "path": "/creator-studio",
    "label": "Creator Studio",
    "keywords": [
      "creator",
      "studio"
    ]
  },
  {
    "path": "/creator/live-analytics",
    "label": "Creator — Live Analytics",
    "keywords": [
      "creator",
      "live",
      "analytics"
    ]
  },
  {
    "path": "/creators",
    "label": "Creators",
    "keywords": [
      "creators"
    ]
  },
  {
    "path": "/credit-gifts",
    "label": "Credit Gifts",
    "keywords": [
      "credit",
      "gifts"
    ]
  },
  {
    "path": "/credits",
    "label": "Credits",
    "keywords": [
      "credits"
    ]
  },
  {
    "path": "/credits/buy",
    "label": "Credits — Buy",
    "keywords": [
      "credits",
      "buy"
    ]
  },
  {
    "path": "/credits/history",
    "label": "Credits — History",
    "keywords": [
      "credits",
      "history"
    ]
  },
  {
    "path": "/crystal-energy",
    "label": "Crystal Energy",
    "keywords": [
      "crystal",
      "energy"
    ]
  },
  {
    "path": "/crystal-energy-network",
    "label": "Crystal Energy Network",
    "keywords": [
      "crystal",
      "energy",
      "network"
    ]
  },
  {
    "path": "/crystal-marketplace",
    "label": "Crystal Marketplace",
    "keywords": [
      "crystal",
      "marketplace"
    ]
  },
  {
    "path": "/culinary-arts",
    "label": "Culinary Arts",
    "keywords": [
      "culinary",
      "arts"
    ]
  },
  {
    "path": "/dating",
    "label": "Dating",
    "keywords": [
      "dating"
    ]
  },
  {
    "path": "/dating/anonymous",
    "label": "Dating — Anonymous",
    "keywords": [
      "dating",
      "anonymous"
    ]
  },
  {
    "path": "/digital-marketing",
    "label": "Digital Marketing",
    "keywords": [
      "digital",
      "marketing"
    ]
  },
  {
    "path": "/digital-offspring",
    "label": "Digital Offspring",
    "keywords": [
      "digital",
      "offspring"
    ]
  },
  {
    "path": "/discover-creators",
    "label": "Discover Creators",
    "keywords": [
      "discover",
      "creators"
    ]
  },
  {
    "path": "/doctor-dashboard",
    "label": "Doctor Dashboard",
    "keywords": [
      "doctor",
      "dashboard"
    ]
  },
  {
    "path": "/download",
    "label": "Download",
    "keywords": [
      "download"
    ]
  },
  {
    "path": "/downloads",
    "label": "Downloads",
    "keywords": [
      "downloads"
    ]
  },
  {
    "path": "/dream-journal",
    "label": "Dream Journal",
    "keywords": [
      "dream",
      "journal"
    ]
  },
  {
    "path": "/earnings",
    "label": "Earnings",
    "keywords": [
      "earnings"
    ]
  },
  {
    "path": "/eco",
    "label": "Eco",
    "keywords": [
      "eco"
    ]
  },
  {
    "path": "/eco-challenge",
    "label": "Eco Challenge",
    "keywords": [
      "eco",
      "challenge"
    ]
  },
  {
    "path": "/eco-challenge/history",
    "label": "Eco Challenge — History",
    "keywords": [
      "eco",
      "challenge",
      "history"
    ]
  },
  {
    "path": "/edit-profile",
    "label": "Edit Profile",
    "keywords": [
      "edit",
      "profile"
    ]
  },
  {
    "path": "/education",
    "label": "Education",
    "keywords": [
      "education"
    ]
  },
  {
    "path": "/education/achievements",
    "label": "Education — Achievements",
    "keywords": [
      "education",
      "achievements"
    ]
  },
  {
    "path": "/education/certificates",
    "label": "Education — Certificates",
    "keywords": [
      "education",
      "certificates"
    ]
  },
  {
    "path": "/education/daily",
    "label": "Education — Daily",
    "keywords": [
      "education",
      "daily"
    ]
  },
  {
    "path": "/education/flashcards",
    "label": "Education — Flashcards",
    "keywords": [
      "education",
      "flashcards"
    ]
  },
  {
    "path": "/education/hub",
    "label": "Education — Hub",
    "keywords": [
      "education",
      "hub"
    ]
  },
  {
    "path": "/education/league",
    "label": "Education — League",
    "keywords": [
      "education",
      "league"
    ]
  },
  {
    "path": "/education/math-solver",
    "label": "Education — Math Solver",
    "keywords": [
      "education",
      "math",
      "solver"
    ]
  },
  {
    "path": "/education/my-courses",
    "label": "Education — My Courses",
    "keywords": [
      "education",
      "my",
      "courses"
    ]
  },
  {
    "path": "/education/notes",
    "label": "Education — Notes",
    "keywords": [
      "education",
      "notes"
    ]
  },
  {
    "path": "/education/skill-tree",
    "label": "Education — Skill Tree",
    "keywords": [
      "education",
      "skill",
      "tree"
    ]
  },
  {
    "path": "/education/teach",
    "label": "Education — Teach",
    "keywords": [
      "education",
      "teach"
    ]
  },
  {
    "path": "/education/tutor",
    "label": "Education — Tutor",
    "keywords": [
      "education",
      "tutor"
    ]
  },
  {
    "path": "/educational-stories",
    "label": "Educational Stories",
    "keywords": [
      "educational",
      "stories"
    ]
  },
  {
    "path": "/emotion-economy",
    "label": "Emotion Economy",
    "keywords": [
      "emotion",
      "economy"
    ]
  },
  {
    "path": "/employer-dashboard",
    "label": "Employer Dashboard",
    "keywords": [
      "employer",
      "dashboard"
    ]
  },
  {
    "path": "/face-insight",
    "label": "Face Insight",
    "keywords": [
      "face",
      "insight"
    ]
  },
  {
    "path": "/fairytale-book",
    "label": "Fairytale Book",
    "keywords": [
      "fairytale",
      "book"
    ]
  },
  {
    "path": "/fashion-studio",
    "label": "Fashion Studio",
    "keywords": [
      "fashion",
      "studio"
    ]
  },
  {
    "path": "/financial-investment",
    "label": "Financial Investment",
    "keywords": [
      "financial",
      "investment"
    ]
  },
  {
    "path": "/first-aid",
    "label": "First Aid",
    "keywords": [
      "first",
      "aid"
    ]
  },
  {
    "path": "/fit-slim",
    "label": "Fit Slim",
    "keywords": [
      "fit",
      "slim"
    ]
  },
  {
    "path": "/food-scanner",
    "label": "Food Scanner",
    "keywords": [
      "food",
      "scanner"
    ]
  },
  {
    "path": "/for-business",
    "label": "For Business",
    "keywords": [
      "for",
      "business"
    ]
  },
  {
    "path": "/for-healthcare",
    "label": "For Healthcare",
    "keywords": [
      "for",
      "healthcare"
    ]
  },
  {
    "path": "/for-schools",
    "label": "For Schools",
    "keywords": [
      "for",
      "schools"
    ]
  },
  {
    "path": "/friends",
    "label": "Friends",
    "keywords": [
      "friends"
    ]
  },
  {
    "path": "/future-face",
    "label": "Future Face",
    "keywords": [
      "future",
      "face"
    ]
  },
  {
    "path": "/games",
    "label": "Games",
    "keywords": [
      "games"
    ]
  },
  {
    "path": "/games-hub",
    "label": "Games Hub",
    "keywords": [
      "games",
      "hub"
    ]
  },
  {
    "path": "/generate-courses",
    "label": "Generate Courses",
    "keywords": [
      "generate",
      "courses"
    ]
  },
  {
    "path": "/gift/canceled",
    "label": "Gift — Canceled",
    "keywords": [
      "gift",
      "canceled"
    ]
  },
  {
    "path": "/gift/history",
    "label": "Gift — History",
    "keywords": [
      "gift",
      "history"
    ]
  },
  {
    "path": "/gift/success",
    "label": "Gift — Success",
    "keywords": [
      "gift",
      "success"
    ]
  },
  {
    "path": "/gifts/inbox",
    "label": "Gifts — Inbox",
    "keywords": [
      "gifts",
      "inbox"
    ]
  },
  {
    "path": "/graphic-design",
    "label": "Graphic Design",
    "keywords": [
      "graphic",
      "design"
    ]
  },
  {
    "path": "/guess-age",
    "label": "Guess Age",
    "keywords": [
      "guess",
      "age"
    ]
  },
  {
    "path": "/handwriting",
    "label": "Handwriting",
    "keywords": [
      "handwriting"
    ]
  },
  {
    "path": "/health",
    "label": "Health",
    "keywords": [
      "health"
    ]
  },
  {
    "path": "/healthcare",
    "label": "Healthcare",
    "keywords": [
      "healthcare"
    ]
  },
  {
    "path": "/healthcare-dashboard",
    "label": "Healthcare Dashboard",
    "keywords": [
      "healthcare",
      "dashboard"
    ]
  },
  {
    "path": "/healthcare-library",
    "label": "Healthcare Library",
    "keywords": [
      "healthcare",
      "library"
    ]
  },
  {
    "path": "/healthy",
    "label": "Healthy",
    "keywords": [
      "healthy"
    ]
  },
  {
    "path": "/healthy-challenge",
    "label": "Healthy Challenge",
    "keywords": [
      "healthy",
      "challenge"
    ]
  },
  {
    "path": "/healthy-challenge/history",
    "label": "Healthy Challenge — History",
    "keywords": [
      "healthy",
      "challenge",
      "history"
    ]
  },
  {
    "path": "/holographic-avatars",
    "label": "Holographic Avatars",
    "keywords": [
      "holographic",
      "avatars"
    ]
  },
  {
    "path": "/holographic-history",
    "label": "Holographic History",
    "keywords": [
      "holographic",
      "history"
    ]
  },
  {
    "path": "/home-designer",
    "label": "Home Designer",
    "keywords": [
      "home",
      "designer"
    ]
  },
  {
    "path": "/horse-racing",
    "label": "Horse Racing",
    "keywords": [
      "horse",
      "racing"
    ]
  },
  {
    "path": "/index",
    "label": "Index",
    "keywords": [
      "index"
    ]
  },
  {
    "path": "/influ-king",
    "label": "Influ King",
    "keywords": [
      "influ",
      "king"
    ]
  },
  {
    "path": "/influencer/earnings",
    "label": "Influencer — Earnings",
    "keywords": [
      "influencer",
      "earnings"
    ]
  },
  {
    "path": "/instructor-earnings",
    "label": "Instructor Earnings",
    "keywords": [
      "instructor",
      "earnings"
    ]
  },
  {
    "path": "/interactive-workshops",
    "label": "Interactive Workshops",
    "keywords": [
      "interactive",
      "workshops"
    ]
  },
  {
    "path": "/investment",
    "label": "Investment",
    "keywords": [
      "investment"
    ]
  },
  {
    "path": "/investment/portfolio",
    "label": "Investment — Portfolio",
    "keywords": [
      "investment",
      "portfolio"
    ]
  },
  {
    "path": "/iq-platform",
    "label": "Iq Platform",
    "keywords": [
      "iq",
      "platform"
    ]
  },
  {
    "path": "/iq-platform/lab",
    "label": "Iq Platform — Lab",
    "keywords": [
      "iq",
      "platform",
      "lab"
    ]
  },
  {
    "path": "/iq/lab",
    "label": "Iq — Lab",
    "keywords": [
      "iq",
      "lab"
    ]
  },
  {
    "path": "/iq/leaderboard",
    "label": "Iq — Leaderboard",
    "keywords": [
      "iq",
      "leaderboard"
    ]
  },
  {
    "path": "/jobs",
    "label": "Jobs",
    "keywords": [
      "jobs"
    ]
  },
  {
    "path": "/jobs/ai-jd-writer",
    "label": "Jobs — Ai Jd Writer",
    "keywords": [
      "jobs",
      "ai",
      "jd",
      "writer"
    ]
  },
  {
    "path": "/jobs/companies/new",
    "label": "Jobs — Companies — New",
    "keywords": [
      "jobs",
      "companies",
      "new"
    ]
  },
  {
    "path": "/jobs/employer",
    "label": "Jobs — Employer",
    "keywords": [
      "jobs",
      "employer"
    ]
  },
  {
    "path": "/jobs/post/success",
    "label": "Jobs — Post — Success",
    "keywords": [
      "jobs",
      "post",
      "success"
    ]
  },
  {
    "path": "/kids",
    "label": "Kids",
    "keywords": [
      "kids"
    ]
  },
  {
    "path": "/kids-academy",
    "label": "Kids Academy",
    "keywords": [
      "kids",
      "academy"
    ]
  },
  {
    "path": "/kids-channel",
    "label": "Kids Channel",
    "keywords": [
      "kids",
      "channel"
    ]
  },
  {
    "path": "/kids-channel/certificate-gallery",
    "label": "Kids Channel — Certificate Gallery",
    "keywords": [
      "kids",
      "channel",
      "certificate",
      "gallery"
    ]
  },
  {
    "path": "/kids-channel/fairy-admin",
    "label": "Kids Channel — Fairy Admin",
    "keywords": [
      "kids",
      "channel",
      "fairy",
      "admin"
    ]
  },
  {
    "path": "/kids-channel/fairy-castles",
    "label": "Kids Channel — Fairy Castles",
    "keywords": [
      "kids",
      "channel",
      "fairy",
      "castles"
    ]
  },
  {
    "path": "/kids-channel/my-gallery",
    "label": "Kids Channel — My Gallery",
    "keywords": [
      "kids",
      "channel",
      "my",
      "gallery"
    ]
  },
  {
    "path": "/kids-channel/parental-dashboard",
    "label": "Kids Channel — Parental Dashboard",
    "keywords": [
      "kids",
      "channel",
      "parental",
      "dashboard"
    ]
  },
  {
    "path": "/kids-drawing-buddy",
    "label": "Kids Drawing Buddy",
    "keywords": [
      "kids",
      "drawing",
      "buddy"
    ]
  },
  {
    "path": "/kids-drawing-pricing",
    "label": "Kids Drawing Pricing",
    "keywords": [
      "kids",
      "drawing",
      "pricing"
    ]
  },
  {
    "path": "/kids-homework",
    "label": "Kids Homework",
    "keywords": [
      "kids",
      "homework"
    ]
  },
  {
    "path": "/kids-homework-pricing",
    "label": "Kids Homework Pricing",
    "keywords": [
      "kids",
      "homework",
      "pricing"
    ]
  },
  {
    "path": "/kids-pricing",
    "label": "Kids Pricing",
    "keywords": [
      "kids",
      "pricing"
    ]
  },
  {
    "path": "/kids-puzzles",
    "label": "Kids Puzzles",
    "keywords": [
      "kids",
      "puzzles"
    ]
  },
  {
    "path": "/kids-reading-companion",
    "label": "Kids Reading Companion",
    "keywords": [
      "kids",
      "reading",
      "companion"
    ]
  },
  {
    "path": "/kids-reading-pricing",
    "label": "Kids Reading Pricing",
    "keywords": [
      "kids",
      "reading",
      "pricing"
    ]
  },
  {
    "path": "/kids-science-admin",
    "label": "Kids Science Admin",
    "keywords": [
      "kids",
      "science",
      "admin"
    ]
  },
  {
    "path": "/kids-science-lab",
    "label": "Kids Science Lab",
    "keywords": [
      "kids",
      "science",
      "lab"
    ]
  },
  {
    "path": "/kids-science-pricing",
    "label": "Kids Science Pricing",
    "keywords": [
      "kids",
      "science",
      "pricing"
    ]
  },
  {
    "path": "/kids-stories/adventure",
    "label": "Kids Stories — Adventure",
    "keywords": [
      "kids",
      "stories",
      "adventure"
    ]
  },
  {
    "path": "/kids-stories/battle",
    "label": "Kids Stories — Battle",
    "keywords": [
      "kids",
      "stories",
      "battle"
    ]
  },
  {
    "path": "/kids-stories/bedtime",
    "label": "Kids Stories — Bedtime",
    "keywords": [
      "kids",
      "stories",
      "bedtime"
    ]
  },
  {
    "path": "/kids-stories/character-gallery",
    "label": "Kids Stories — Character Gallery",
    "keywords": [
      "kids",
      "stories",
      "character",
      "gallery"
    ]
  },
  {
    "path": "/kids-stories/create-character",
    "label": "Kids Stories — Create Character",
    "keywords": [
      "kids",
      "stories",
      "create",
      "character"
    ]
  },
  {
    "path": "/kids-stories/educational",
    "label": "Kids Stories — Educational",
    "keywords": [
      "kids",
      "stories",
      "educational"
    ]
  },
  {
    "path": "/kids-stories/games",
    "label": "Kids Stories — Games",
    "keywords": [
      "kids",
      "stories",
      "games"
    ]
  },
  {
    "path": "/kids-stories/voice-chat",
    "label": "Kids Stories — Voice Chat",
    "keywords": [
      "kids",
      "stories",
      "voice",
      "chat"
    ]
  },
  {
    "path": "/kids-story-creator",
    "label": "Kids Story Creator",
    "keywords": [
      "kids",
      "story",
      "creator"
    ]
  },
  {
    "path": "/kids-story-pricing",
    "label": "Kids Story Pricing",
    "keywords": [
      "kids",
      "story",
      "pricing"
    ]
  },
  {
    "path": "/kids-voice-chat",
    "label": "Kids Voice Chat",
    "keywords": [
      "kids",
      "voice",
      "chat"
    ]
  },
  {
    "path": "/kids-voice-chat-pricing",
    "label": "Kids Voice Chat Pricing",
    "keywords": [
      "kids",
      "voice",
      "chat",
      "pricing"
    ]
  },
  {
    "path": "/kitchenstars",
    "label": "Kitchenstars",
    "keywords": [
      "kitchenstars"
    ]
  },
  {
    "path": "/kitchenstars-subscription",
    "label": "Kitchenstars Subscription",
    "keywords": [
      "kitchenstars",
      "subscription"
    ]
  },
  {
    "path": "/kitchenstars/battles",
    "label": "Kitchenstars — Battles",
    "keywords": [
      "kitchenstars",
      "battles"
    ]
  },
  {
    "path": "/kitchenstars/my-cookbook",
    "label": "Kitchenstars — My Cookbook",
    "keywords": [
      "kitchenstars",
      "my",
      "cookbook"
    ]
  },
  {
    "path": "/kitchenstars/recipes",
    "label": "Kitchenstars — Recipes",
    "keywords": [
      "kitchenstars",
      "recipes"
    ]
  },
  {
    "path": "/language-learning",
    "label": "Language Learning",
    "keywords": [
      "language",
      "learning"
    ]
  },
  {
    "path": "/legal",
    "label": "Legal",
    "keywords": [
      "legal"
    ]
  },
  {
    "path": "/legal/community",
    "label": "Legal — Community",
    "keywords": [
      "legal",
      "community"
    ]
  },
  {
    "path": "/legal/cookies",
    "label": "Legal — Cookies",
    "keywords": [
      "legal",
      "cookies"
    ]
  },
  {
    "path": "/legal/creator",
    "label": "Legal — Creator",
    "keywords": [
      "legal",
      "creator"
    ]
  },
  {
    "path": "/legal/privacy",
    "label": "Legal — Privacy",
    "keywords": [
      "legal",
      "privacy"
    ]
  },
  {
    "path": "/legal/refund",
    "label": "Legal — Refund",
    "keywords": [
      "legal",
      "refund"
    ]
  },
  {
    "path": "/legal/terms",
    "label": "Legal — Terms",
    "keywords": [
      "legal",
      "terms"
    ]
  },
  {
    "path": "/lie-detector",
    "label": "Lie Detector",
    "keywords": [
      "lie",
      "detector"
    ]
  },
  {
    "path": "/live-concerts",
    "label": "Live Concerts",
    "keywords": [
      "live",
      "concerts"
    ]
  },
  {
    "path": "/livestream",
    "label": "Livestream",
    "keywords": [
      "livestream"
    ]
  },
  {
    "path": "/lottery-ai",
    "label": "Lottery Ai",
    "keywords": [
      "lottery",
      "ai"
    ]
  },
  {
    "path": "/lottery-history",
    "label": "Lottery History",
    "keywords": [
      "lottery",
      "history"
    ]
  },
  {
    "path": "/lucky-wheel",
    "label": "Lucky Wheel",
    "keywords": [
      "lucky",
      "wheel"
    ]
  },
  {
    "path": "/marketplace",
    "label": "Marketplace",
    "keywords": [
      "marketplace"
    ]
  },
  {
    "path": "/masterchef",
    "label": "Masterchef",
    "keywords": [
      "masterchef"
    ]
  },
  {
    "path": "/masterchef-subscription",
    "label": "Masterchef Subscription",
    "keywords": [
      "masterchef",
      "subscription"
    ]
  },
  {
    "path": "/masterchef/competitions",
    "label": "Masterchef — Competitions",
    "keywords": [
      "masterchef",
      "competitions"
    ]
  },
  {
    "path": "/masterchef/duel-upload",
    "label": "Masterchef — Duel Upload",
    "keywords": [
      "masterchef",
      "duel",
      "upload"
    ]
  },
  {
    "path": "/masterchef/live-battles",
    "label": "Masterchef — Live Battles",
    "keywords": [
      "masterchef",
      "live",
      "battles"
    ]
  },
  {
    "path": "/masterclasses",
    "label": "Masterclasses",
    "keywords": [
      "masterclasses"
    ]
  },
  {
    "path": "/meal-planner",
    "label": "Meal Planner",
    "keywords": [
      "meal",
      "planner"
    ]
  },
  {
    "path": "/megaforum",
    "label": "Megaforum",
    "keywords": [
      "megaforum"
    ]
  },
  {
    "path": "/megatalent",
    "label": "Megatalent",
    "keywords": [
      "megatalent"
    ]
  },
  {
    "path": "/megatalent/battle-results",
    "label": "Megatalent — Battle Results",
    "keywords": [
      "megatalent",
      "battle",
      "results"
    ]
  },
  {
    "path": "/megatalent/go-live",
    "label": "Megatalent — Go Live",
    "keywords": [
      "megatalent",
      "go",
      "live"
    ]
  },
  {
    "path": "/megatalent/my-submissions",
    "label": "Megatalent — My Submissions",
    "keywords": [
      "megatalent",
      "my",
      "submissions"
    ]
  },
  {
    "path": "/megatalent/success",
    "label": "Megatalent — Success",
    "keywords": [
      "megatalent",
      "success"
    ]
  },
  {
    "path": "/membership",
    "label": "Membership",
    "keywords": [
      "membership"
    ]
  },
  {
    "path": "/memory-auctions",
    "label": "Memory Auctions",
    "keywords": [
      "memory",
      "auctions"
    ]
  },
  {
    "path": "/messages",
    "label": "Messages",
    "keywords": [
      "messages"
    ]
  },
  {
    "path": "/messenger",
    "label": "Messenger",
    "keywords": [
      "messenger"
    ]
  },
  {
    "path": "/monetization-ideas",
    "label": "Monetization Ideas",
    "keywords": [
      "monetization",
      "ideas"
    ]
  },
  {
    "path": "/music",
    "label": "Music",
    "keywords": [
      "music"
    ]
  },
  {
    "path": "/music-production",
    "label": "Music Production",
    "keywords": [
      "music",
      "production"
    ]
  },
  {
    "path": "/my-auctions",
    "label": "My Auctions",
    "keywords": [
      "my",
      "auctions"
    ]
  },
  {
    "path": "/my-bookings/doctors",
    "label": "My Bookings — Doctors",
    "keywords": [
      "my",
      "bookings",
      "doctors"
    ]
  },
  {
    "path": "/my-bookings/services",
    "label": "My Bookings — Services",
    "keywords": [
      "my",
      "bookings",
      "services"
    ]
  },
  {
    "path": "/my-bug-reports",
    "label": "My Bug Reports",
    "keywords": [
      "my",
      "bug",
      "reports"
    ]
  },
  {
    "path": "/my-credits-history",
    "label": "My Credits History",
    "keywords": [
      "my",
      "credits",
      "history"
    ]
  },
  {
    "path": "/my-learning",
    "label": "My Learning",
    "keywords": [
      "my",
      "learning"
    ]
  },
  {
    "path": "/my-progress",
    "label": "My Progress",
    "keywords": [
      "my",
      "progress"
    ]
  },
  {
    "path": "/my-properties",
    "label": "My Properties",
    "keywords": [
      "my",
      "properties"
    ]
  },
  {
    "path": "/my-purchased-tips",
    "label": "My Purchased Tips",
    "keywords": [
      "my",
      "purchased",
      "tips"
    ]
  },
  {
    "path": "/mystery-box",
    "label": "Mystery Box",
    "keywords": [
      "mystery",
      "box"
    ]
  },
  {
    "path": "/notifications",
    "label": "Notifications",
    "keywords": [
      "notifications"
    ]
  },
  {
    "path": "/numerology",
    "label": "Numerology",
    "keywords": [
      "numerology"
    ]
  },
  {
    "path": "/nutrition-hub",
    "label": "Nutrition Hub",
    "keywords": [
      "nutrition",
      "hub"
    ]
  },
  {
    "path": "/nutrition-subscriptions",
    "label": "Nutrition Subscriptions",
    "keywords": [
      "nutrition",
      "subscriptions"
    ]
  },
  {
    "path": "/online-psychologist",
    "label": "Online Psychologist",
    "keywords": [
      "online",
      "psychologist"
    ]
  },
  {
    "path": "/paid-message/canceled",
    "label": "Paid Message — Canceled",
    "keywords": [
      "paid",
      "message",
      "canceled"
    ]
  },
  {
    "path": "/paid-message/success",
    "label": "Paid Message — Success",
    "keywords": [
      "paid",
      "message",
      "success"
    ]
  },
  {
    "path": "/parallel-universe",
    "label": "Parallel Universe",
    "keywords": [
      "parallel",
      "universe"
    ]
  },
  {
    "path": "/past-life",
    "label": "Past Life",
    "keywords": [
      "past",
      "life"
    ]
  },
  {
    "path": "/payment-documentation",
    "label": "Payment Documentation",
    "keywords": [
      "payment",
      "documentation"
    ]
  },
  {
    "path": "/pet-translator",
    "label": "Pet Translator",
    "keywords": [
      "pet",
      "translator"
    ]
  },
  {
    "path": "/pet-translator-pricing",
    "label": "Pet Translator Pricing",
    "keywords": [
      "pet",
      "translator",
      "pricing"
    ]
  },
  {
    "path": "/pets",
    "label": "Pets",
    "keywords": [
      "pets"
    ]
  },
  {
    "path": "/pets/achievements",
    "label": "Pets — Achievements",
    "keywords": [
      "pets",
      "achievements"
    ]
  },
  {
    "path": "/phobia-trading",
    "label": "Phobia Trading",
    "keywords": [
      "phobia",
      "trading"
    ]
  },
  {
    "path": "/photo-restoration",
    "label": "Photo Restoration",
    "keywords": [
      "photo",
      "restoration"
    ]
  },
  {
    "path": "/photography",
    "label": "Photography",
    "keywords": [
      "photography"
    ]
  },
  {
    "path": "/pitch",
    "label": "Pitch",
    "keywords": [
      "pitch"
    ]
  },
  {
    "path": "/plans",
    "label": "Plans",
    "keywords": [
      "plans"
    ]
  },
  {
    "path": "/plant-care",
    "label": "Plant Care",
    "keywords": [
      "plant",
      "care"
    ]
  },
  {
    "path": "/premium",
    "label": "Premium",
    "keywords": [
      "premium"
    ]
  },
  {
    "path": "/premium-courses",
    "label": "Premium Courses",
    "keywords": [
      "premium",
      "courses"
    ]
  },
  {
    "path": "/premium-plans",
    "label": "Premium Plans",
    "keywords": [
      "premium",
      "plans"
    ]
  },
  {
    "path": "/premium-store",
    "label": "Premium Store",
    "keywords": [
      "premium",
      "store"
    ]
  },
  {
    "path": "/prices",
    "label": "Prices",
    "keywords": [
      "prices"
    ]
  },
  {
    "path": "/pricing",
    "label": "Pricing",
    "keywords": [
      "pricing"
    ]
  },
  {
    "path": "/proclasses",
    "label": "Proclasses",
    "keywords": [
      "proclasses"
    ]
  },
  {
    "path": "/profile",
    "label": "Profile",
    "keywords": [
      "profile"
    ]
  },
  {
    "path": "/profile/edit",
    "label": "Profile — Edit",
    "keywords": [
      "profile",
      "edit"
    ]
  },
  {
    "path": "/promotions",
    "label": "Promotions",
    "keywords": [
      "promotions"
    ]
  },
  {
    "path": "/promotions/mine",
    "label": "Promotions — Mine",
    "keywords": [
      "promotions",
      "mine"
    ]
  },
  {
    "path": "/promotions/new",
    "label": "Promotions — New",
    "keywords": [
      "promotions",
      "new"
    ]
  },
  {
    "path": "/promotions/success",
    "label": "Promotions — Success",
    "keywords": [
      "promotions",
      "success"
    ]
  },
  {
    "path": "/property-favorites",
    "label": "Property Favorites",
    "keywords": [
      "property",
      "favorites"
    ]
  },
  {
    "path": "/property-marketplace",
    "label": "Property Marketplace",
    "keywords": [
      "property",
      "marketplace"
    ]
  },
  {
    "path": "/property-submission",
    "label": "Property Submission",
    "keywords": [
      "property",
      "submission"
    ]
  },
  {
    "path": "/psychologist",
    "label": "Psychologist",
    "keywords": [
      "psychologist"
    ]
  },
  {
    "path": "/public-speaking",
    "label": "Public Speaking",
    "keywords": [
      "public",
      "speaking"
    ]
  },
  {
    "path": "/quiz",
    "label": "Quiz",
    "keywords": [
      "quiz"
    ]
  },
  {
    "path": "/quiz/create",
    "label": "Quiz — Create",
    "keywords": [
      "quiz",
      "create"
    ]
  },
  {
    "path": "/recipe-generator",
    "label": "Recipe Generator",
    "keywords": [
      "recipe",
      "generator"
    ]
  },
  {
    "path": "/reel-battles",
    "label": "Reel Battles",
    "keywords": [
      "reel",
      "battles"
    ]
  },
  {
    "path": "/referral",
    "label": "Referral",
    "keywords": [
      "referral"
    ]
  },
  {
    "path": "/referrals/leaderboard",
    "label": "Referrals — Leaderboard",
    "keywords": [
      "referrals",
      "leaderboard"
    ]
  },
  {
    "path": "/report-bug",
    "label": "Report Bug",
    "keywords": [
      "report",
      "bug"
    ]
  },
  {
    "path": "/reset-password",
    "label": "Reset Password",
    "keywords": [
      "reset",
      "password"
    ]
  },
  {
    "path": "/restaurant-analyzer",
    "label": "Restaurant Analyzer",
    "keywords": [
      "restaurant",
      "analyzer"
    ]
  },
  {
    "path": "/rewards",
    "label": "Rewards",
    "keywords": [
      "rewards"
    ]
  },
  {
    "path": "/rewards/audit",
    "label": "Rewards — Audit",
    "keywords": [
      "rewards",
      "audit"
    ]
  },
  {
    "path": "/roadmap",
    "label": "Roadmap",
    "keywords": [
      "roadmap"
    ]
  },
  {
    "path": "/safety-prevention",
    "label": "Safety Prevention",
    "keywords": [
      "safety",
      "prevention"
    ]
  },
  {
    "path": "/schools",
    "label": "Schools",
    "keywords": [
      "schools"
    ]
  },
  {
    "path": "/search",
    "label": "Search",
    "keywords": [
      "search"
    ]
  },
  {
    "path": "/secret-santa",
    "label": "Secret Santa",
    "keywords": [
      "secret",
      "santa"
    ]
  },
  {
    "path": "/services",
    "label": "Services",
    "keywords": [
      "services"
    ]
  },
  {
    "path": "/services-hub",
    "label": "Services Hub",
    "keywords": [
      "services",
      "hub"
    ]
  },
  {
    "path": "/settings",
    "label": "Settings",
    "keywords": [
      "settings"
    ]
  },
  {
    "path": "/settings/security",
    "label": "Settings — Security",
    "keywords": [
      "settings",
      "security"
    ]
  },
  {
    "path": "/shadow-arena",
    "label": "Shadow Arena",
    "keywords": [
      "shadow",
      "arena"
    ]
  },
  {
    "path": "/shadow-arena/dashboard",
    "label": "Shadow Arena — Dashboard",
    "keywords": [
      "shadow",
      "arena",
      "dashboard"
    ]
  },
  {
    "path": "/shadow-arena/submit-story",
    "label": "Shadow Arena — Submit Story",
    "keywords": [
      "shadow",
      "arena",
      "submit",
      "story"
    ]
  },
  {
    "path": "/shorts",
    "label": "Shorts",
    "keywords": [
      "shorts"
    ]
  },
  {
    "path": "/skill-swap",
    "label": "Skill Swap",
    "keywords": [
      "skill",
      "swap"
    ]
  },
  {
    "path": "/skills",
    "label": "Skills",
    "keywords": [
      "skills"
    ]
  },
  {
    "path": "/skills-marketplace",
    "label": "Skills Marketplace",
    "keywords": [
      "skills",
      "marketplace"
    ]
  },
  {
    "path": "/skills-marketplace/mine",
    "label": "Skills Marketplace — Mine",
    "keywords": [
      "skills",
      "marketplace",
      "mine"
    ]
  },
  {
    "path": "/skills-marketplace/new",
    "label": "Skills Marketplace — New",
    "keywords": [
      "skills",
      "marketplace",
      "new"
    ]
  },
  {
    "path": "/skills-marketplace/orders",
    "label": "Skills Marketplace — Orders",
    "keywords": [
      "skills",
      "marketplace",
      "orders"
    ]
  },
  {
    "path": "/skills-marketplace/orders/success",
    "label": "Skills Marketplace — Orders — Success",
    "keywords": [
      "skills",
      "marketplace",
      "orders",
      "success"
    ]
  },
  {
    "path": "/spin-solve",
    "label": "Spin Solve",
    "keywords": [
      "spin",
      "solve"
    ]
  },
  {
    "path": "/sponsor-dashboard",
    "label": "Sponsor Dashboard",
    "keywords": [
      "sponsor",
      "dashboard"
    ]
  },
  {
    "path": "/sponsor-registration",
    "label": "Sponsor Registration",
    "keywords": [
      "sponsor",
      "registration"
    ]
  },
  {
    "path": "/sports",
    "label": "Sports",
    "keywords": [
      "sports"
    ]
  },
  {
    "path": "/sports-predictor",
    "label": "Sports Predictor",
    "keywords": [
      "sports",
      "predictor"
    ]
  },
  {
    "path": "/status",
    "label": "Status",
    "keywords": [
      "status"
    ]
  },
  {
    "path": "/stock-content-library",
    "label": "Stock Content Library",
    "keywords": [
      "stock",
      "content",
      "library"
    ]
  },
  {
    "path": "/stories",
    "label": "Stories",
    "keywords": [
      "stories"
    ]
  },
  {
    "path": "/story-gallery",
    "label": "Story Gallery",
    "keywords": [
      "story",
      "gallery"
    ]
  },
  {
    "path": "/story-games",
    "label": "Story Games",
    "keywords": [
      "story",
      "games"
    ]
  },
  {
    "path": "/story-video-demo",
    "label": "Story Video Demo",
    "keywords": [
      "story",
      "video",
      "demo"
    ]
  },
  {
    "path": "/subscription",
    "label": "Subscription",
    "keywords": [
      "subscription"
    ]
  },
  {
    "path": "/subscriptions",
    "label": "Subscriptions",
    "keywords": [
      "subscriptions"
    ]
  },
  {
    "path": "/teacher-dashboard",
    "label": "Teacher Dashboard",
    "keywords": [
      "teacher",
      "dashboard"
    ]
  },
  {
    "path": "/teen",
    "label": "Teen",
    "keywords": [
      "teen"
    ]
  },
  {
    "path": "/teen-career-counselor",
    "label": "Teen Career Counselor",
    "keywords": [
      "teen",
      "career",
      "counselor"
    ]
  },
  {
    "path": "/teen-career-pricing",
    "label": "Teen Career Pricing",
    "keywords": [
      "teen",
      "career",
      "pricing"
    ]
  },
  {
    "path": "/teen-essay-coach",
    "label": "Teen Essay Coach",
    "keywords": [
      "teen",
      "essay",
      "coach"
    ]
  },
  {
    "path": "/teen-homework-pro",
    "label": "Teen Homework Pro",
    "keywords": [
      "teen",
      "homework",
      "pro"
    ]
  },
  {
    "path": "/teen-hub",
    "label": "Teen Hub",
    "keywords": [
      "teen",
      "hub"
    ]
  },
  {
    "path": "/teen-mental-wellness",
    "label": "Teen Mental Wellness",
    "keywords": [
      "teen",
      "mental",
      "wellness"
    ]
  },
  {
    "path": "/teen-skill-builder",
    "label": "Teen Skill Builder",
    "keywords": [
      "teen",
      "skill",
      "builder"
    ]
  },
  {
    "path": "/teen-social-coach",
    "label": "Teen Social Coach",
    "keywords": [
      "teen",
      "social",
      "coach"
    ]
  },
  {
    "path": "/teen-study-planner",
    "label": "Teen Study Planner",
    "keywords": [
      "teen",
      "study",
      "planner"
    ]
  },
  {
    "path": "/teen/confessions",
    "label": "Teen — Confessions",
    "keywords": [
      "teen",
      "confessions"
    ]
  },
  {
    "path": "/teens",
    "label": "Teens",
    "keywords": [
      "teens"
    ]
  },
  {
    "path": "/terms",
    "label": "Terms",
    "keywords": [
      "terms"
    ]
  },
  {
    "path": "/time-capsule",
    "label": "Time Capsule",
    "keywords": [
      "time",
      "capsule"
    ]
  },
  {
    "path": "/time-capsule-subscription",
    "label": "Time Capsule Subscription",
    "keywords": [
      "time",
      "capsule",
      "subscription"
    ]
  },
  {
    "path": "/time-reversal",
    "label": "Time Reversal",
    "keywords": [
      "time",
      "reversal"
    ]
  },
  {
    "path": "/time-reversal-subscription",
    "label": "Time Reversal Subscription",
    "keywords": [
      "time",
      "reversal",
      "subscription"
    ]
  },
  {
    "path": "/time-reversal/create-post",
    "label": "Time Reversal — Create Post",
    "keywords": [
      "time",
      "reversal",
      "create",
      "post"
    ]
  },
  {
    "path": "/time-reversal/dashboard",
    "label": "Time Reversal — Dashboard",
    "keywords": [
      "time",
      "reversal",
      "dashboard"
    ]
  },
  {
    "path": "/time-reversal/timeline",
    "label": "Time Reversal — Timeline",
    "keywords": [
      "time",
      "reversal",
      "timeline"
    ]
  },
  {
    "path": "/tipster-dashboard",
    "label": "Tipster Dashboard",
    "keywords": [
      "tipster",
      "dashboard"
    ]
  },
  {
    "path": "/tutorial-platform",
    "label": "Tutorial Platform",
    "keywords": [
      "tutorial",
      "platform"
    ]
  },
  {
    "path": "/unlock-videos",
    "label": "Unlock Videos",
    "keywords": [
      "unlock",
      "videos"
    ]
  },
  {
    "path": "/upgrade",
    "label": "Upgrade",
    "keywords": [
      "upgrade"
    ]
  },
  {
    "path": "/vacationer",
    "label": "Vacationer",
    "keywords": [
      "vacationer"
    ]
  },
  {
    "path": "/verification",
    "label": "Verification",
    "keywords": [
      "verification"
    ]
  },
  {
    "path": "/verified",
    "label": "Verified",
    "keywords": [
      "verified"
    ]
  },
  {
    "path": "/verify-report",
    "label": "Verify Report",
    "keywords": [
      "verify",
      "report"
    ]
  },
  {
    "path": "/video-ad-generator",
    "label": "Video Ad Generator",
    "keywords": [
      "video",
      "ad",
      "generator"
    ]
  },
  {
    "path": "/virtual-escape-room",
    "label": "Virtual Escape Room",
    "keywords": [
      "virtual",
      "escape",
      "room"
    ]
  },
  {
    "path": "/virtual-pet",
    "label": "Virtual Pet",
    "keywords": [
      "virtual",
      "pet"
    ]
  },
  {
    "path": "/wall",
    "label": "Wall",
    "keywords": [
      "wall"
    ]
  },
  {
    "path": "/wall/friends",
    "label": "Wall — Friends",
    "keywords": [
      "wall",
      "friends"
    ]
  },
  {
    "path": "/wall/info",
    "label": "Wall — Info",
    "keywords": [
      "wall",
      "info"
    ]
  },
  {
    "path": "/wall/memories",
    "label": "Wall — Memories",
    "keywords": [
      "wall",
      "memories"
    ]
  },
  {
    "path": "/wall/messages",
    "label": "Wall — Messages",
    "keywords": [
      "wall",
      "messages"
    ]
  },
  {
    "path": "/wall/more",
    "label": "Wall — More",
    "keywords": [
      "wall",
      "more"
    ]
  },
  {
    "path": "/wall/saved",
    "label": "Wall — Saved",
    "keywords": [
      "wall",
      "saved"
    ]
  },
  {
    "path": "/wall/trending",
    "label": "Wall — Trending",
    "keywords": [
      "wall",
      "trending"
    ]
  },
  {
    "path": "/wall/videos",
    "label": "Wall — Videos",
    "keywords": [
      "wall",
      "videos"
    ]
  },
  {
    "path": "/wellness",
    "label": "Wellness",
    "keywords": [
      "wellness"
    ]
  },
  {
    "path": "/wheel-of-fortune",
    "label": "Wheel Of Fortune",
    "keywords": [
      "wheel",
      "of",
      "fortune"
    ]
  },
  {
    "path": "/wine-pairing",
    "label": "Wine Pairing",
    "keywords": [
      "wine",
      "pairing"
    ]
  },
  {
    "path": "/coloring-pages",
    "label": "Coloring Pages — Mandalas category",
    "keywords": [
      "mandala",
      "mandalas",
      "mandaly",
      "mandalu",
      "symmetry",
      "zen",
      "coloring",
      "omalovanky",
      "vyfarbovanie"
    ]
  },
  {
    "path": "/coloring-pages",
    "label": "Coloring Pages — Animals category",
    "keywords": [
      "animals",
      "zvieratka",
      "puppy",
      "lion",
      "coloring templates"
    ]
  },
  {
    "path": "/coloring-pages",
    "label": "Coloring Pages — Fantasy category",
    "keywords": [
      "fantasy",
      "dragons",
      "unicorn",
      "castles",
      "coloring"
    ]
  },
  {
    "path": "/coloring-pages",
    "label": "Coloring Pages — Nature, Vehicles, Holiday, Education categories",
    "keywords": [
      "nature",
      "vehicles",
      "holiday",
      "education",
      "templates",
      "sablony",
      "coloring gallery",
      "ai prompt coloring"
    ]
  },
  {
    "path": "/wellness?tool=mandala",
    "label": "Wellness — Digital Mandala creator",
    "keywords": [
      "digital mandala",
      "mandala drawing",
      "mandala creator",
      "symmetrical drawing",
      "mindfulness drawing",
      "open mandala",
      "otvor mandalu",
      "mandala vo wellness"
    ]
  },
  {
    "path": "/wellness?tool=breathing",
    "label": "Wellness — Breathing Exercises",
    "keywords": [
      "breathing exercise",
      "dychove cvicenie",
      "dychanie",
      "4 7 8 breathing",
      "box breathing"
    ]
  },
  {
    "path": "/wellness?tool=grounding",
    "label": "Wellness — 5-4-3-2-1 Grounding",
    "keywords": [
      "grounding",
      "uzemnenie",
      "panic attack",
      "anxiety exercise",
      "5 4 3 2 1"
    ]
  },
  {
    "path": "/wellness?tool=sounds",
    "label": "Wellness — Nature Sounds",
    "keywords": [
      "nature sounds",
      "zvuky prirody",
      "rain sounds",
      "ocean sounds",
      "forest ambience"
    ]
  },
  {
    "path": "/wellness?tool=bodyscan",
    "label": "Wellness — Body Scan Meditation",
    "keywords": [
      "body scan",
      "body meditation",
      "sken tela",
      "relaxation meditation"
    ]
  },
  {
    "path": "/wellness?tool=challenges",
    "label": "Wellness — Daily Challenges",
    "keywords": [
      "wellness challenges",
      "daily wellness",
      "denne vyzvy",
      "wellness streak"
    ]
  },
  {
    "path": "/wellness?tool=chat",
    "label": "Wellness — AI Mindfulness Coach",
    "keywords": [
      "mindfulness coach",
      "wellness coach",
      "mindfulness chat",
      "coach vsimavosti"
    ]
  },
  {
    "path": "/wellness?tool=journal",
    "label": "Wellness — Gratitude Journal",
    "keywords": [
      "gratitude journal",
      "vdacnost",
      "dennik vdacnosti",
      "mood journal"
    ]
  },
  {
    "path": "/wellness",
    "label": "Wellness — AI Mindfulness Coach, Gratitude Journal, mood tracking",
    "keywords": [
      "mindfulness",
      "gratitude journal",
      "mood",
      "cbt",
      "meditation",
      "breathing",
      "wellness tools"
    ]
  },
  {
    "path": "/kids",
    "label": "Kids Channel — homework help, science lab, story maker, drawing, reading",
    "keywords": [
      "homework",
      "science",
      "story",
      "reading",
      "drawing",
      "kids modules",
      "deti",
      "ulohy"
    ]
  },
  {
    "path": "/spin-solve",
    "label": "Spin & Solve — wheel of fortune with word puzzles (tajnicky)",
    "keywords": [
      "tajnicka",
      "tajnicky",
      "wheel of fortune",
      "koleso stastia",
      "word puzzle",
      "hadanky",
      "spin and solve"
    ]
  },
  {
    "path": "/unlock-videos",
    "label": "Unlock Videos — locked mid-video unlocks for 1 credit",
    "keywords": [
      "unlock videos",
      "locked video",
      "video unlock",
      "odomknutie videa",
      "creator videos"
    ]
  },
  {
    "path": "/gifts/inbox",
    "label": "Unique Gifts inbox — received and sent gifts, earnings",
    "keywords": [
      "gifts",
      "darceky",
      "gift inbox",
      "received gifts",
      "sent gifts",
      "gift earnings",
      "emoji gifts",
      "stickers"
    ]
  },
  {
    "path": "/brain-duel/hub",
    "label": "Brain Lab — brain games and duels (1 credit per game)",
    "keywords": [
      "brain lab",
      "brain games",
      "brain duel",
      "memory",
      "logic games",
      "iq games"
    ]
  },
  {
    "path": "/iq-platform",
    "label": "IQ tests (3 credits)",
    "keywords": [
      "iq",
      "iq test",
      "intelligence test",
      "iq testy"
    ]
  },
  {
    "path": "/skills",
    "label": "Skills Marketplace — P2P microservices with categories",
    "keywords": [
      "skills",
      "microservices",
      "sluzby",
      "freelance",
      "offers",
      "categories"
    ]
  },
  {
    "path": "/bazaar",
    "label": "Bazaar — classifieds with categories and saved searches",
    "keywords": [
      "bazaar",
      "bazar",
      "classifieds",
      "inzeraty",
      "second hand",
      "saved search"
    ]
  },
  {
    "path": "/property-marketplace",
    "label": "Property Marketplace — real estate listings (25 credits per listing)",
    "keywords": [
      "property",
      "real estate",
      "nehnutelnosti",
      "inzerat",
      "rent",
      "sale",
      "listings"
    ]
  },
  {
    "path": "/auction",
    "label": "Online Auction — bidding and antiques",
    "keywords": [
      "auction",
      "aukcia",
      "bidding",
      "antique",
      "starozitnosti",
      "antique identification"
    ]
  },
  {
    "path": "/megatalent",
    "label": "Megatalent — talent contest, voting, comments, uploads",
    "keywords": [
      "megatalent",
      "talent",
      "contest",
      "voting",
      "hlasovanie",
      "upload video",
      "champion"
    ]
  },
  {
    "path": "/dating",
    "label": "Dating & Anonymous Dating (2 credits entry)",
    "keywords": [
      "dating",
      "anonymous dating",
      "randenie",
      "matches",
      "swipe",
      "coffee community"
    ]
  },
  {
    "path": "/education",
    "label": "Education — courses, lessons, exams, certificates",
    "keywords": [
      "education",
      "courses",
      "kurzy",
      "lessons",
      "exam",
      "certificate",
      "academy",
      "tutorial"
    ]
  },
  {
    "path": "/cooking",
    "label": "Cooking hub — recipe generator, culinary academy, AI cooking tools",
    "keywords": [
      "cooking",
      "recipe",
      "recepty",
      "culinary",
      "kitchen",
      "nutrition",
      "meal plan"
    ]
  },
  {
    "path": "/health",
    "label": "Health & Wellness hub — fitness plans, nutrition, doctor booking",
    "keywords": [
      "health",
      "fitness",
      "nutrition",
      "doctor",
      "booking",
      "wellness",
      "plan 30 60 90"
    ]
  },
  {
    "path": "/jobs",
    "label": "Work & Jobs — job listings, AI CV generator, promotions board",
    "keywords": [
      "jobs",
      "work",
      "praca",
      "cv",
      "resume",
      "zivotopis",
      "employer",
      "promotions"
    ]
  },
  {
    "path": "/credits",
    "label": "Credits & wallet — buy credits, ledger, cashout",
    "keywords": [
      "credits",
      "kredity",
      "wallet",
      "balance",
      "cashout",
      "payout",
      "vyplata",
      "ledger"
    ]
  },
  {
    "path": "/rewards",
    "label": "Rewards — XP, daily login, lucky wheel, achievements",
    "keywords": [
      "rewards",
      "xp",
      "daily login",
      "lucky wheel",
      "achievements",
      "streak",
      "odmeny"
    ]
  },
  {
    "path": "/brand-arena",
    "label": "Brand Arena — brand battles, leaderboard, sponsorship tiers",
    "keywords": [
      "brand",
      "brand battle",
      "arena",
      "sponsor",
      "leaderboard",
      "champions"
    ]
  },
  {
    "path": "/face-insight",
    "label": "Face Insight Studio — face analysis, compare mode, PDF report",
    "keywords": [
      "face",
      "face insight",
      "palmistry",
      "guess my age",
      "vek",
      "photo analysis"
    ]
  },
  {
    "path": "/fairytale-book",
    "label": "Fairytale Book Generator — personalised story book from a photo",
    "keywords": [
      "fairytale",
      "story book",
      "rozpravka",
      "kniha",
      "book generator"
    ]
  },
  {
    "path": "/wall",
    "label": "Wall — social feed, stories, groups, 24h notes, close friends",
    "keywords": [
      "wall",
      "feed",
      "stories",
      "groups",
      "close friends",
      "24h note",
      "posts",
      "socialna siet"
    ]
  },
  {
    "path": "/referral",
    "label": "Referrals — invite friends, earn 5 EUR",
    "keywords": [
      "referral",
      "invite",
      "affiliate",
      "odporucenie",
      "5 eur"
    ]
  },
  {
    "path": "/profile",
    "label": "Profile — verification, subscriptions, achievements, my gifts",
    "keywords": [
      "profile",
      "verified",
      "verification",
      "subscriptions",
      "my gifts",
      "avatar",
      "profil"
    ]
  }
];

function norm(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9 ]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Fuzzy keyword search over the whole catalog. Returns best matches first. */
export function searchCatalog(query: string, limit = 25): UniCatalogEntry[] {
  const q = norm(query);
  if (!q) return [];
  const tokens = q.split(" ").filter((t) => t.length > 2);
  const scored = UNI_CATALOG.map((e) => {
    const hay = norm([e.label, e.path, ...e.keywords].join(" "));
    let score = 0;
    for (const t of tokens) {
      if (hay.includes(t)) score += 3;
      else {
        const stem = t.slice(0, Math.max(4, t.length - 2));
        if (stem.length > 2 && hay.includes(stem)) score += 2;
      }
    }
    if (hay.includes(q)) score += 4;
    if (e.path.startsWith("/admin")) score -= 4;
    return { e, score };
  })
    .filter((r) => r.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit);
  return scored.map((r) => r.e);
}

/** True when the path exists in the catalog (allows query strings). */
export function isKnownPath(p: string): boolean {
  const base = p.split("?")[0];
  return UNI_CATALOG.some((e) => e.path.split("?")[0] === base);
}
