import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { AstrologyCreditsDisplay } from "@/components/astrology/AstrologyCreditsDisplay";
import { TarotReader } from "@/components/astrology/TarotReader";
import { DailyHoroscope } from "@/components/astrology/DailyHoroscope";
import { DreamInterpretation } from "@/components/astrology/DreamInterpretation";
import { NumerologyCalculator } from "@/components/astrology/NumerologyCalculator";
import { PalmistryReader } from "@/components/astrology/PalmistryReader";
import { CompatibilityChecker } from "@/components/astrology/CompatibilityChecker";
import { YesNoOracle } from "@/components/astrology/YesNoOracle";
import { RuneReader } from "@/components/astrology/RuneReader";
import { BirthChartAnalyzer } from "@/components/astrology/BirthChartAnalyzer";
import { LiveChatWithAI } from "@/components/astrology/LiveChatWithAI";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const Astrology = () => {
  return (
    <div className="min-h-screen bg-background p-2 sm:p-4">
      <div className="container mx-auto max-w-6xl pt-16 sm:pt-20">
        <div className="text-center mb-4 sm:mb-6">
          <h1 className="text-2xl sm:text-3xl lg:text-4xl font-bold bg-gradient-to-r from-purple-600 via-pink-600 to-purple-700 bg-clip-text text-transparent px-2">
            ✨ Astrology & Mystical Readings
          </h1>
        </div>

        {/* Description Section */}
        <Card className="mb-6 bg-gradient-to-br from-purple-50 to-pink-50 dark:from-purple-950/30 dark:to-pink-950/30 border-purple-200 dark:border-purple-800">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg sm:text-xl text-purple-700 dark:text-purple-300">
              🔮 What is Astrology & Mystical Readings?
            </CardTitle>
          </CardHeader>
          <CardContent className="text-sm sm:text-base text-muted-foreground space-y-4">
            <p>
              Explore the mysteries of the universe with our comprehensive AI-powered mystical reading platform. 
              Get personalized insights into your life, relationships, and future through ancient wisdom combined with modern technology.
            </p>
            
            <div>
              <h4 className="font-semibold text-foreground mb-2">📖 How to Use:</h4>
              <ol className="list-decimal list-inside space-y-1 ml-2">
                <li><strong>Purchase Credits</strong> - Buy credit packages to unlock readings</li>
                <li><strong>Choose a Reading Type</strong> - Select from 10 different mystical services</li>
                <li><strong>Enter Your Details</strong> - Provide zodiac sign, birth date, or question</li>
                <li><strong>Receive Your Reading</strong> - Get AI-generated personalized insights</li>
                <li><strong>Save & Share</strong> - Keep your readings for future reference</li>
              </ol>
            </div>

            <div>
              <h4 className="font-semibold text-foreground mb-2">✨ Available Services:</h4>
              <ul className="grid grid-cols-1 sm:grid-cols-2 gap-1 ml-2 text-xs sm:text-sm">
                <li>⭐ <strong>Horoscope</strong> - Daily, weekly & monthly zodiac forecasts</li>
                <li>💳 <strong>Tarot</strong> - AI-powered tarot card readings</li>
                <li>💭 <strong>Dreams</strong> - Dream interpretation & symbolism analysis</li>
                <li>🔢 <strong>Numerology</strong> - Life path & destiny number calculations</li>
                <li>🖐️ <strong>Palmistry</strong> - Upload palm photo for line analysis</li>
                <li>💕 <strong>Love Compatibility</strong> - Zodiac relationship matching</li>
                <li>❓ <strong>Yes/No Oracle</strong> - Quick answers to your questions</li>
                <li>🗿 <strong>Rune Reading</strong> - Ancient Norse divination</li>
                <li>🌌 <strong>Birth Chart</strong> - Full astrological chart analysis</li>
                <li>💬 <strong>AI Chat</strong> - Live conversation with mystical AI</li>
              </ul>
            </div>

            <p className="text-xs text-muted-foreground italic border-t pt-3 mt-3">
              ⚠️ <strong>Disclaimer:</strong> All readings are generated by AI for entertainment purposes only. 
              They should not be used as a substitute for professional advice in medical, legal, financial, or psychological matters.
            </p>
          </CardContent>
        </Card>

        <div className="mb-4 sm:mb-6">
          <AstrologyCreditsDisplay />
        </div>

        <Tabs defaultValue="horoscope" className="w-full">
          <TabsList className="flex overflow-x-auto gap-1 sm:gap-2 h-auto p-1 sm:p-2 w-full">
            <TabsTrigger value="horoscope" className="text-xs sm:text-sm px-2 sm:px-3 py-1 whitespace-nowrap flex-shrink-0">⭐ Horoscope</TabsTrigger>
            <TabsTrigger value="tarot" className="text-xs sm:text-sm px-2 sm:px-3 py-1 whitespace-nowrap flex-shrink-0">💳 Tarot</TabsTrigger>
            <TabsTrigger value="dream" className="text-xs sm:text-sm px-2 sm:px-3 py-1 whitespace-nowrap flex-shrink-0">💭 Dreams</TabsTrigger>
            <TabsTrigger value="numerology" className="text-xs sm:text-sm px-2 sm:px-3 py-1 whitespace-nowrap flex-shrink-0">🔢 Numerology</TabsTrigger>
            <TabsTrigger value="palmistry" className="text-xs sm:text-sm px-2 sm:px-3 py-1 whitespace-nowrap flex-shrink-0">🖐️ Palmistry</TabsTrigger>
            <TabsTrigger value="compatibility" className="text-xs sm:text-sm px-2 sm:px-3 py-1 whitespace-nowrap flex-shrink-0">💕 Love</TabsTrigger>
            <TabsTrigger value="yesno" className="text-xs sm:text-sm px-2 sm:px-3 py-1 whitespace-nowrap flex-shrink-0">❓ Yes/No</TabsTrigger>
            <TabsTrigger value="rune" className="text-xs sm:text-sm px-2 sm:px-3 py-1 whitespace-nowrap flex-shrink-0">🗿 Rune</TabsTrigger>
            <TabsTrigger value="birthchart" className="text-xs sm:text-sm px-2 sm:px-3 py-1 whitespace-nowrap flex-shrink-0">🌌 Birth</TabsTrigger>
            <TabsTrigger value="livechat" className="text-xs sm:text-sm px-2 sm:px-3 py-1 whitespace-nowrap flex-shrink-0">💬 Chat</TabsTrigger>
          </TabsList>

          <div className="mt-6">
            <TabsContent value="horoscope">
              <DailyHoroscope />
            </TabsContent>

            <TabsContent value="tarot">
              <TarotReader />
            </TabsContent>

            <TabsContent value="dream">
              <DreamInterpretation />
            </TabsContent>

            <TabsContent value="numerology">
              <NumerologyCalculator />
            </TabsContent>

            <TabsContent value="palmistry">
              <PalmistryReader />
            </TabsContent>

            <TabsContent value="compatibility">
              <CompatibilityChecker />
            </TabsContent>

            <TabsContent value="yesno">
              <YesNoOracle />
            </TabsContent>

            <TabsContent value="rune">
              <RuneReader />
            </TabsContent>

            <TabsContent value="birthchart">
              <BirthChartAnalyzer />
            </TabsContent>

            <TabsContent value="livechat">
              <LiveChatWithAI />
            </TabsContent>
          </div>
        </Tabs>
      </div>
    </div>
  );
};

export default Astrology;
