// PDF / share helpers for analyzer results — pure client-side, no backend.
export const exportAnalysisPDF = async (
  title: string,
  imageUrl: string,
  sections: { heading: string; body: string }[]
) => {
  const w = window.open("", "_blank");
  if (!w) return;
  const safe = (s: string) => String(s ?? "").replace(/[<>&]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;" }[c]!));
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${safe(title)}</title>
  <style>
    body { font-family: -apple-system, system-ui, sans-serif; max-width: 800px; margin: 32px auto; padding: 24px; color:#111; }
    h1 { font-size: 28px; margin-bottom: 8px; }
    h2 { font-size: 18px; color: #0891b2; margin-top: 24px; }
    img { max-width: 100%; border-radius: 12px; margin: 16px 0; }
    p { line-height: 1.6; white-space: pre-wrap; }
    .footer { margin-top: 48px; font-size: 11px; color: #888; text-align:center; }
  </style></head><body>
  <h1>${safe(title)}</h1>
  ${imageUrl ? `<img src="${safe(imageUrl)}" alt="${safe(title)}" />` : ""}
  ${sections.map(s => `<h2>${safe(s.heading)}</h2><p>${safe(s.body)}</p>`).join("")}
  <div class="footer">Generated by Universal Analyzer · ${new Date().toLocaleString()}</div>
  <script>setTimeout(() => window.print(), 400);</script>
  </body></html>`);
  w.document.close();
};

export const shareAnalysisCard = async (title: string, url: string) => {
  const data = { title, text: `Check out this analysis: ${title}`, url };
  try {
    if ((navigator as any).share) await (navigator as any).share(data);
    else {
      await navigator.clipboard.writeText(url);
      return "copied";
    }
  } catch { /* user cancelled */ }
  return "shared";
};
