import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Loader2, FileDown } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import jsPDF from "jspdf";
import { FloatingHowItWorks } from "../common/FloatingHowItWorks";

export default function FutureFaceMonthlyReport() {
  const [busy, setBusy] = useState(false);
  const { toast } = useToast();

  const generate = async () => {
    setBusy(true);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) { toast({ title: "Sign in first", variant: "destructive" }); return; }

      const since = new Date(); since.setDate(since.getDate() - 30);
      const sinceISO = since.toISOString();
      const [scoresRes, routineRes, imagesRes] = await Promise.all([
        supabase.from("future_face_skin_scores").select("score, recorded_at").gte("recorded_at", sinceISO).order("recorded_at"),
        supabase.from("future_face_routine_log").select("*").gte("routine_date", sinceISO.slice(0, 10)).order("routine_date"),
        supabase.from("future_face_images").select("action, created_at").gte("created_at", sinceISO),
      ]);

      const scores = (scoresRes.data || []) as any[];
      const routine = (routineRes.data || []) as any[];
      const images = (imagesRes.data || []) as any[];

      const avgScore = scores.length ? Math.round(scores.reduce((a, b) => a + b.score, 0) / scores.length) : 0;
      const fullDays = routine.filter(r => r.morning_done && r.evening_done).length;
      const compliance = routine.length ? Math.round((fullDays / routine.length) * 100) : 0;
      const avgSleep = routine.length ? (routine.reduce((a, b) => a + (b.sleep_hours || 0), 0) / routine.length).toFixed(1) : "0";
      const avgWater = routine.length ? Math.round(routine.reduce((a, b) => a + (b.hydration_glasses || 0), 0) / routine.length) : 0;

      const pdf = new jsPDF();
      pdf.setFillColor(13, 16, 35); pdf.rect(0, 0, 210, 40, "F");
      pdf.setTextColor(255, 255, 255); pdf.setFontSize(22); pdf.setFont("helvetica", "bold");
      pdf.text("Future Face — 30-day Report", 14, 22);
      pdf.setFontSize(10); pdf.setFont("helvetica", "normal");
      pdf.text(new Date().toLocaleDateString(), 14, 32);

      pdf.setTextColor(20, 20, 20); pdf.setFontSize(14); pdf.setFont("helvetica", "bold");
      pdf.text("Highlights", 14, 55);
      pdf.setFontSize(11); pdf.setFont("helvetica", "normal");
      const lines = [
        `Average skin score: ${avgScore}/100  (${scores.length} entries)`,
        `Routine compliance: ${compliance}%  (${fullDays}/${routine.length} full days)`,
        `Avg sleep: ${avgSleep} h/night`,
        `Avg hydration: ${avgWater} glasses/day`,
        `AI transformations created: ${images.length}`,
      ];
      lines.forEach((l, i) => pdf.text(l, 14, 65 + i * 8));

      pdf.setFontSize(14); pdf.setFont("helvetica", "bold");
      pdf.text("Daily Skin Score Trend", 14, 115);
      pdf.setDrawColor(120, 120, 240);
      // mini bar chart
      const maxBar = 60;
      scores.slice(-30).forEach((s, i) => {
        const x = 14 + i * 6;
        const h = (s.score / 100) * maxBar;
        pdf.setFillColor(80, 200, 240);
        pdf.rect(x, 180 - h, 4, h, "F");
      });
      pdf.setDrawColor(180);
      pdf.line(14, 180, 200, 180);
      pdf.setFontSize(8); pdf.text("Last 30 days", 14, 185);

      pdf.setFontSize(14); pdf.setFont("helvetica", "bold");
      pdf.text("Recommendations", 14, 205);
      pdf.setFontSize(10); pdf.setFont("helvetica", "normal");
      const recs: string[] = [];
      if (compliance < 70) recs.push("Improve routine consistency — aim for 80%+ next month.");
      if (avgScore < 70) recs.push("Consider adding vitamin C serum and consistent SPF.");
      if (parseFloat(avgSleep) < 7) recs.push("Increase sleep to 7-9 h/night for skin regeneration.");
      if (avgWater < 6) recs.push("Hydrate more — target 8 glasses/day.");
      if (recs.length === 0) recs.push("Great work — keep your current routine going!");
      recs.forEach((r, i) => pdf.text(`• ${r}`, 14, 215 + i * 7));

      pdf.setFontSize(8); pdf.setTextColor(120);
      pdf.text("Generated by Unique · Future Face", 14, 285);

      pdf.save(`future-face-report-${new Date().toISOString().slice(0, 10)}.pdf`);
      toast({ title: "Report downloaded!" });
    } catch (e: any) {
      toast({ title: "Failed", description: e.message, variant: "destructive" });
    } finally { setBusy(false); }
  };

  return (
    <>
      <FloatingHowItWorks title={"Future Face Monthly Report - How it works"} steps={[{ title: 'Open', desc: 'Access the Future Face Monthly Report section from its module.' }, { title: 'Explore', desc: 'Review the controls and content available in Future Face Monthly Report.' }, { title: 'Interact', desc: 'Use the available actions - browse, select, or submit as needed.' }, { title: 'Review', desc: 'Check the results, updates, or feedback shown after your action.' }]} />
      <div className="mb-8 space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="text-xl sm:text-2xl font-black">📄 Monthly PDF Report</h2>
        <Badge className="bg-emerald-500/20 text-emerald-400 border-emerald-500/30">Free</Badge>
      </div>
      <Card className="border-cyan-500/20 bg-gradient-to-br from-cyan-500/5 to-purple-500/5">
        <CardContent className="p-4 space-y-3">
          <p className="text-sm">Get a beautiful PDF summary of your last 30 days: average skin score, routine compliance, sleep & hydration trends, and personalized recommendations.</p>
          <Button onClick={generate} disabled={busy} className="w-full bg-gradient-to-r from-cyan-600 to-purple-600">
            {busy ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <FileDown className="h-4 w-4 mr-2" />}
            Generate Report
          </Button>
        </CardContent>
      </Card>
    </div>
    </>
  );
}
