export const CATEGORY_TEASERS = {
  wall: {
    label: "Social Wall",
    hook: "CREATE. CONNECT. EARN.",
    lines: ["Share posts, stories and reels", "Grow smarter with AI tools", "Receive gifts with real cash value"],
    outro: "Your audience is waiting.",
    accent: "#ff3ea5",
  },
  messenger: {
    label: "Messenger",
    hook: "CLOSER. EVERY DAY.",
    lines: ["Private chats that feel personal", "Share moments, gifts and reactions", "Keep every connection in one place"],
    outro: "Start the conversation.",
    accent: "#8b5cf6",
  },
  games: {
    label: "Games",
    hook: "PLAY. COMPETE. WIN.",
    lines: ["Discover games for every mood", "Challenge friends and climb higher", "Turn every round into a new adventure"],
    outro: "Your next game starts here.",
    accent: "#36d6c3",
  },
  jobs: {
    label: "Jobs",
    hook: "TALENT MEETS OPPORTUNITY.",
    lines: ["Find work that fits your skills", "Connect directly with real people", "Build income on your own terms"],
    outro: "Make your next move.",
    accent: "#ff855c",
  },
  rewards: {
    label: "Rewards",
    hook: "EVERY ACTION COUNTS.",
    lines: ["Earn XP for being active", "Unlock badges and milestones", "Collect rewards as you grow"],
    outro: "Your progress deserves more.",
    accent: "#f5c84c",
  },
  promotions: {
    label: "Promotions",
    hook: "BE SEEN. GROW FASTER.",
    lines: ["Put your offer in the spotlight", "Reach people across Unique", "Choose the promotion that fits you"],
    outro: "Turn attention into growth.",
    accent: "#ff567f",
  },
  megatalent: {
    label: "Megatalent",
    hook: "YOUR TALENT. YOUR STAGE.",
    lines: ["Share your performance", "Let the community vote", "Compete for the quarterly prize"],
    outro: "This could be your moment.",
    accent: "#d7a83b",
  },
  vip: {
    label: "VIP Membership Group",
    hook: "STEP INSIDE THE CIRCLE.",
    lines: ["Exclusive space for members only", "Early access to new features", "Premium perks every month"],
    outro: "Membership has its privileges.",
    accent: "#e8bf5a",
  },
  eco: {
    label: "Eco Challenge",
    hook: "SMALL ACTS. REAL IMPACT.",
    lines: ["Take on green challenges", "Share your proof and inspire others", "Part of every pool goes to charity"],
    outro: "Do good, get rewarded.",
    accent: "#4ade80",
  },
  health: {
    label: "Health Challenge",
    hook: "STRONGER EVERY DAY.",
    lines: ["Join challenges that keep you moving", "Track progress with the community", "Win while supporting a good cause"],
    outro: "Your best shape starts now.",
    accent: "#37c9e8",
  },
  clipbattles: {
    label: "Clip Battles",
    hook: "TWO CLIPS. ONE WINNER.",
    lines: ["Upload your best short clip", "Go head to head with creators", "The community picks the champion"],
    outro: "Let your clip do the talking.",
    accent: "#ff4d8d",
  },
  education: {
    label: "Education Hub",
    hook: "LEARN. LEVEL UP.",
    lines: ["Courses across dozens of topics", "Tests and certificates included", "Teach and earn from your own course"],
    outro: "Knowledge that pays off.",
    accent: "#6ea8ff",
  },
  mentor: {
    label: "Personal Mentor",
    hook: "GUIDANCE THAT FITS YOU.",
    lines: ["Get a plan built around your goals", "Ask anything, anytime", "Stay accountable week by week"],
    outro: "Your mentor is ready.",
    accent: "#f0a35e",
  },
  brainduel: {
    label: "Brain Duel",
    hook: "THINK FAST. WIN BIG.",
    lines: ["Live quiz duels in real time", "Dozens of knowledge categories", "Climb the leaderboard with every win"],
    outro: "Prove who is sharper.",
    accent: "#4fa8ff",
  },
  diceduel: {
    label: "Dice Trail Duel",
    hook: "ROLL. RACE. RULE.",
    lines: ["Real-time duel for two players", "Every roll changes the race", "Traps and boosts on the trail"],
    outro: "Your turn to roll.",
    accent: "#a78bfa",
  },
  kidschannel: {
    label: "Kids Channel",
    hook: "A WORLD MADE FOR KIDS.",
    lines: ["Explore playful activities in one colorful place", "Create, learn and discover something new", "Designed for curious young minds"],
    outro: "Let the adventure begin.",
    accent: "#ffd34e",
  },
  coloringpages: {
    label: "Coloring Pages",
    hook: "COLOR YOUR IMAGINATION.",
    lines: ["Choose a picture that sparks your creativity", "Bring every detail to life with color", "Save your finished artwork and feel proud"],
    outro: "Every color tells a story.",
    accent: "#ff6fae",
  },
  kidspuzzles: {
    label: "Kids Puzzles",
    hook: "THINK. MATCH. COMPLETE.",
    lines: ["Solve bright puzzles one piece at a time", "Build focus while having fun", "Complete the picture and celebrate the win"],
    outro: "Your next puzzle is waiting.",
    accent: "#63d5c5",
  },
  homeworkhelper: {
    label: "Homework Helper",
    hook: "HOMEWORK MADE CLEARER.",
    lines: ["Ask questions when a lesson feels difficult", "Follow simple explanations step by step", "Learn with confidence at your own pace"],
    outro: "A little help goes a long way.",
    accent: "#72a9ff",
  },
  storycreator: {
    label: "Story Creator",
    hook: "YOUR IDEA. YOUR ADVENTURE.",
    lines: ["Choose the heroes, setting and big idea", "Shape an original story full of surprises", "Turn imagination into a tale to remember"],
    outro: "What will your story become?",
    accent: "#b78cff",
  },
  sciencelab: {
    label: "Science Lab",
    hook: "DISCOVER HOW THINGS WORK.",
    lines: ["Explore science through playful experiments", "Ask questions and uncover surprising answers", "Make every discovery feel like an adventure"],
    outro: "Curiosity starts here.",
    accent: "#45d7e8",
  },
  drawingbuddy: {
    label: "Drawing Buddy",
    hook: "DRAW IT YOUR WAY.",
    lines: ["Follow friendly drawing ideas step by step", "Practice shapes, details and creative expression", "Turn a blank page into something wonderful"],
    outro: "Pick up a pencil and create.",
    accent: "#ff8f5c",
  },
  readingcompanion: {
    label: "Reading Companion",
    hook: "READ. LISTEN. GROW.",
    lines: ["Enjoy stories with a supportive reading guide", "Build confidence one page at a time", "Discover new words in a calm, friendly way"],
    outro: "Every page opens a new world.",
    accent: "#70cf76",
  },
  fairytalebook: {
    label: "Fairytale Book Generator",
    hook: "MAGIC MADE JUST FOR YOU.",
    lines: ["Choose a hero and a magical world", "Create an original fairytale from your ideas", "Enjoy a personal book filled with wonder"],
    outro: "Your fairytale begins now.",
    accent: "#d9a7ff",
  },
  kidscollectibles: {
    label: "Kids Collectibles",
    hook: "DISCOVER. COLLECT. COMPLETE.",
    lines: ["Reveal colorful cards from original worlds", "Build themed collections as you explore", "Complete each album one card at a time"],
    outro: "Which card will you find next?",
    accent: "#ffb34f",
  },
  careercounselor: {
    label: "Career Counselor",
    hook: "DREAM BIG. FIND YOUR PATH.",
    lines: ["Explore careers that match your interests", "Discover strengths you can build for the future", "Turn curiosity into an inspiring direction"],
    outro: "Your future has many possibilities.",
    accent: "#68b9ff",
  },
} as const;

export type CategoryTeaserId = keyof typeof CATEGORY_TEASERS;
