export const CATEGORY_TEASERS = {
  wall: {
    label: "Social Wall",
    hook: "CREATE. CONNECT. EARN.",
    lines: ["Share posts, stories and reels", "Grow smarter with AI tools", "Receive gifts with real cash value"],
    outro: "Your audience is waiting.",
    accent: "#ff3ea5",
  },
  messenger: {
    label: "Messenger",
    hook: "CLOSER. EVERY DAY.",
    lines: ["Private chats that feel personal", "Share moments, gifts and reactions", "Keep every connection in one place"],
    outro: "Start the conversation.",
    accent: "#8b5cf6",
  },
  games: {
    label: "Games",
    hook: "PLAY. COMPETE. WIN.",
    lines: ["Discover games for every mood", "Challenge friends and climb higher", "Turn every round into a new adventure"],
    outro: "Your next game starts here.",
    accent: "#36d6c3",
  },
  jobs: {
    label: "Jobs",
    hook: "TALENT MEETS OPPORTUNITY.",
    lines: ["Find work that fits your skills", "Connect directly with real people", "Build income on your own terms"],
    outro: "Make your next move.",
    accent: "#ff855c",
  },
  rewards: {
    label: "Rewards",
    hook: "EVERY ACTION COUNTS.",
    lines: ["Earn XP for being active", "Unlock badges and milestones", "Collect rewards as you grow"],
    outro: "Your progress deserves more.",
    accent: "#f5c84c",
  },
  promotions: {
    label: "Promotions",
    hook: "BE SEEN. GROW FASTER.",
    lines: ["Put your offer in the spotlight", "Reach people across Unique", "Choose the promotion that fits you"],
    outro: "Turn attention into growth.",
    accent: "#ff567f",
  },
  megatalent: {
    label: "Megatalent",
    hook: "YOUR TALENT. YOUR STAGE.",
    lines: ["Share your performance", "Let the community vote", "Compete for the quarterly prize"],
    outro: "This could be your moment.",
    accent: "#d7a83b",
  },
  vip: {
    label: "VIP Membership Group",
    hook: "STEP INSIDE THE CIRCLE.",
    lines: ["Exclusive space for members only", "Early access to new features", "Premium perks every month"],
    outro: "Membership has its privileges.",
    accent: "#e8bf5a",
  },
  eco: {
    label: "Eco Challenge",
    hook: "SMALL ACTS. REAL IMPACT.",
    lines: ["Take on green challenges", "Share your proof and inspire others", "Part of every pool goes to charity"],
    outro: "Do good, get rewarded.",
    accent: "#4ade80",
  },
  health: {
    label: "Health Challenge",
    hook: "STRONGER EVERY DAY.",
    lines: ["Join challenges that keep you moving", "Track progress with the community", "Win while supporting a good cause"],
    outro: "Your best shape starts now.",
    accent: "#37c9e8",
  },
  clipbattles: {
    label: "Clip Battles",
    hook: "TWO CLIPS. ONE WINNER.",
    lines: ["Upload your best short clip", "Go head to head with creators", "The community picks the champion"],
    outro: "Let your clip do the talking.",
    accent: "#ff4d8d",
  },
  education: {
    label: "Education Hub",
    hook: "LEARN. LEVEL UP.",
    lines: ["Courses across dozens of topics", "Tests and certificates included", "Teach and earn from your own course"],
    outro: "Knowledge that pays off.",
    accent: "#6ea8ff",
  },
  mentor: {
    label: "Personal Mentor",
    hook: "GUIDANCE THAT FITS YOU.",
    lines: ["Get a plan built around your goals", "Ask anything, anytime", "Stay accountable week by week"],
    outro: "Your mentor is ready.",
    accent: "#f0a35e",
  },
  brainduel: {
    label: "Brain Duel",
    hook: "THINK FAST. WIN BIG.",
    lines: ["Live quiz duels in real time", "Dozens of knowledge categories", "Climb the leaderboard with every win"],
    outro: "Prove who is sharper.",
    accent: "#4fa8ff",
  },
  diceduel: {
    label: "Dice Trail Duel",
    hook: "ROLL. RACE. RULE.",
    lines: ["Real-time duel for two players", "Every roll changes the race", "Traps and boosts on the trail"],
    outro: "Your turn to roll.",
    accent: "#a78bfa",
  },
  kidschannel: {
    label: "Kids Channel",
    hook: "A WORLD MADE FOR KIDS.",
    lines: ["Explore playful activities in one colorful place", "Create, learn and discover something new", "Designed for curious young minds"],
    outro: "Let the adventure begin.",
    accent: "#ffd34e",
  },
  coloringpages: {
    label: "Coloring Pages",
    hook: "COLOR YOUR IMAGINATION.",
    lines: ["Choose a picture that sparks your creativity", "Bring every detail to life with color", "Save your finished artwork and feel proud"],
    outro: "Every color tells a story.",
    accent: "#ff6fae",
  },
  kidspuzzles: {
    label: "Kids Puzzles",
    hook: "THINK. MATCH. COMPLETE.",
    lines: ["Solve bright puzzles one piece at a time", "Build focus while having fun", "Complete the picture and celebrate the win"],
    outro: "Your next puzzle is waiting.",
    accent: "#63d5c5",
  },
  homeworkhelper: {
    label: "Homework Helper",
    hook: "HOMEWORK MADE CLEARER.",
    lines: ["Ask questions when a lesson feels difficult", "Follow simple explanations step by step", "Learn with confidence at your own pace"],
    outro: "A little help goes a long way.",
    accent: "#72a9ff",
  },
  storycreator: {
    label: "Story Creator",
    hook: "YOUR IDEA. YOUR ADVENTURE.",
    lines: ["Choose the heroes, setting and big idea", "Shape an original story full of surprises", "Turn imagination into a tale to remember"],
    outro: "What will your story become?",
    accent: "#b78cff",
  },
  sciencelab: {
    label: "Science Lab",
    hook: "DISCOVER HOW THINGS WORK.",
    lines: ["Explore science through playful experiments", "Ask questions and uncover surprising answers", "Make every discovery feel like an adventure"],
    outro: "Curiosity starts here.",
    accent: "#45d7e8",
  },
  drawingbuddy: {
    label: "Drawing Buddy",
    hook: "DRAW IT YOUR WAY.",
    lines: ["Follow friendly drawing ideas step by step", "Practice shapes, details and creative expression", "Turn a blank page into something wonderful"],
    outro: "Pick up a pencil and create.",
    accent: "#ff8f5c",
  },
  readingcompanion: {
    label: "Reading Companion",
    hook: "READ. LISTEN. GROW.",
    lines: ["Enjoy stories with a supportive reading guide", "Build confidence one page at a time", "Discover new words in a calm, friendly way"],
    outro: "Every page opens a new world.",
    accent: "#70cf76",
  },
  fairytalebook: {
    label: "Fairytale Book Generator",
    hook: "MAGIC MADE JUST FOR YOU.",
    lines: ["Choose a hero and a magical world", "Create an original fairytale from your ideas", "Enjoy a personal book filled with wonder"],
    outro: "Your fairytale begins now.",
    accent: "#d9a7ff",
  },
  kidscollectibles: {
    label: "Kids Collectibles",
    hook: "DISCOVER. COLLECT. COMPLETE.",
    lines: ["Reveal colorful cards from original worlds", "Build themed collections as you explore", "Complete each album one card at a time"],
    outro: "Which card will you find next?",
    accent: "#ffb34f",
  },
  careercounselor: {
    label: "Career Counselor",
    hook: "DREAM BIG. FIND YOUR PATH.",
    lines: ["Explore careers that match your interests", "Discover strengths you can build for the future", "Turn curiosity into an inspiring direction"],
    outro: "Your future has many possibilities.",
    accent: "#68b9ff",
  },
  creativeforge: {
    label: "Creative Forge",
    hook: "WRITE WITH AI POWER.",
    lines: ["Brainstorm ideas and expand them instantly", "Rewrite, shorten and optimize for search", "Check quality and translate in one place"],
    outro: "Your words, perfected.",
    accent: "#ff5f8d",
  },
  contentstudio: {
    label: "Content Studio",
    hook: "PLAN. CREATE. PUBLISH.",
    lines: ["Generate captions and hashtags for every platform", "Preview posts before they go live", "Schedule everything in one smart calendar"],
    outro: "Stay consistent, effortlessly.",
    accent: "#7c5cff",
  },
  aigeneration: {
    label: "AI Generation",
    hook: "IMAGINE IT. SEE IT.",
    lines: ["Describe any idea in your own words", "Choose style, format and quality", "Save your favourites to your gallery"],
    outro: "Creation without limits.",
    accent: "#35c6f4",
  },
  universalanalyzer: {
    label: "Universal Analyzer",
    hook: "UNDERSTAND ANY FILE.",
    lines: ["Analyze documents, images, audio and video", "Get summaries, key points and insights", "Export a clean report in seconds"],
    outro: "Clarity from any content.",
    accent: "#4bd6a6",
  },
  flyerstudio: {
    label: "Promotion Flyer Studio",
    hook: "DESIGN THAT SELLS.",
    lines: ["Build eye-catching flyers in minutes", "Pick layouts, colors and messages", "Download print-ready designs instantly"],
    outro: "Promote like a pro.",
    accent: "#ffa63d",
  },
  videoadgen: {
    label: "Video Ad Generator",
    hook: "ADS THAT MOVE PEOPLE.",
    lines: ["Turn your product into a polished video ad", "Choose scenes, music and voiceover", "Export for every social format"],
    outro: "Your campaign starts here.",
    accent: "#ff4d6d",
  },
  aivideocreator: {
    label: "AI Video Creator",
    hook: "FROM IDEA TO MOTION.",
    lines: ["Describe a scene and watch it come alive", "Or bring your own photos into motion", "Download cinematic clips with sound"],
    outro: "Make video the easy way.",
    accent: "#a06bff",
  },
  photostyler: {
    label: "Photo Styler",
    hook: "ONE PHOTO. MANY LOOKS.",
    lines: ["Transform portraits with striking styles", "Keep your face natural and true", "Get share-ready results in moments"],
    outro: "Your best look, unlocked.",
    accent: "#ff77c8",
  },
  reversevideo: {
    label: "Reverse Video",
    hook: "PLAY TIME BACKWARDS.",
    lines: ["Flip any clip into a mesmerizing rewind", "Smooth playback with perfect timing", "Save and share the magic instantly"],
    outro: "Rewind reality.",
    accent: "#3fd0d6",
  },
  aitattoo: {
    label: "AI Tattoo Designer",
    hook: "INK YOUR OWN IDEA.",
    lines: ["Describe the concept and pick a style", "Explore sizes, colors and placements", "Preview the design before you commit"],
    outro: "Design it before you ink it.",
    accent: "#8f9bff",
  },
  aiclone: {
    label: "AI Personality Clone",
    hook: "A DIGITAL YOU.",
    lines: ["Shape a clone with your own style and voice", "Let it chat, post and grow your audience", "Track engagement and earn from it"],
    outro: "Meet your second self.",
    accent: "#ff9e3d",
  },
  pettranslator: {
    label: "AI Pet Translator",
    hook: "HEAR WHAT THEY MEAN.",
    lines: ["Record a bark, meow or playful sound", "Discover possible moods and needs", "Understand your companion a little better"],
    outro: "Listen with a new perspective.",
    accent: "#ffb34f",
  },
  handwriting: {
    label: "Handwriting Analyzer",
    hook: "EVERY STROKE TELLS A STORY.",
    lines: ["Upload a clear sample of your handwriting", "Explore patterns in shape, rhythm and pressure", "Receive a thoughtful visual analysis"],
    outro: "See your writing differently.",
    accent: "#62c7dc",
  },
  futureface: {
    label: "Future Face",
    hook: "MEET YOUR FUTURE SELF.",
    lines: ["Upload one clear portrait", "Explore natural age transformations", "Compare each stage side by side"],
    outro: "Take a look through time.",
    accent: "#d995ff",
  },
  photorestoration: {
    label: "Photo Restoration",
    hook: "BRING MEMORIES BACK.",
    lines: ["Repair scratches, fading and old damage", "Recover natural detail and balanced color", "Preserve treasured moments in high quality"],
    outro: "Give every memory new life.",
    accent: "#f2c56b",
  },
  stocklibrary: {
    label: "Stock Content Library",
    hook: "THE RIGHT VISUAL. READY.",
    lines: ["Explore useful imagery for every idea", "Find content by theme, mood and format", "Build polished projects faster"],
    outro: "Your next visual is waiting.",
    accent: "#51d2aa",
  },
  brandbuilder: {
    label: "Brand Builder",
    hook: "BUILD A BRAND PEOPLE REMEMBER.",
    lines: ["Define your identity and visual direction", "Create consistent colors, voice and assets", "Turn one idea into a complete brand"],
    outro: "Make your identity unmistakable.",
    accent: "#ff5f7d",
  },
  homedesigner: {
    label: "Home Designer",
    hook: "REIMAGINE YOUR SPACE.",
    lines: ["Upload a photo of any room", "Explore layouts, colors and interior styles", "Visualize the transformation before you begin"],
    outro: "Your dream room starts here.",
    accent: "#56c9bd",
  },
  beautystudio: {
    label: "Beauty Studio",
    hook: "DISCOVER YOUR NEXT LOOK.",
    lines: ["Try makeup, hair and nail inspiration", "Explore looks shaped around your photo", "Save your favourites before making a change"],
    outro: "Find the look that feels like you.",
    accent: "#ff65a8",
  },
  fashionstudio: {
    label: "Fashion Studio",
    hook: "STYLE WITHOUT LIMITS.",
    lines: ["Explore outfits for every mood and moment", "Mix silhouettes, colors and accessories", "Turn inspiration into your signature style"],
    outro: "Wear your imagination.",
    accent: "#8da1ff",
  },
  guessage: {
    label: "Guess My Age",
    hook: "HOW OLD DO YOU LOOK?",
    lines: ["Upload a clear photo for a playful estimate", "Discover the visual cues behind the result", "Compare guesses and share the surprise"],
    outro: "Ready for the reveal?",
    accent: "#ffd052",
  },
  faceinsight: {
    label: "Face Insight Studio",
    hook: "SEE YOUR FEATURES ANEW.",
    lines: ["Explore facial balance and visible features", "Receive clear, personalized observations", "Create a polished insight report"],
    outro: "Discover a fresh perspective on you.",
    accent: "#48d2cf",
  },
  pastlife: {
    label: "Past Life Explorer",
    hook: "EXPLORE STORIES BEYOND TIME.",
    lines: ["Enter your birth details and personal clues", "Discover AI-created past-life narratives", "Reflect on patterns, talents and connections"],
    outro: "Open a new chapter of reflection.",
    accent: "#c99cff",
  },
  lottery: {
    label: "Lottery Numbers",
    hook: "EXPLORE THE PATTERNS.",
    lines: ["Generate number sets for entertainment", "Explore trends, dreams and numerology", "Compare frequencies in a visual heatmap"],
    outro: "Play responsibly. No outcome is guaranteed.",
    accent: "#f3c84b",
  },
  astrology: {
    label: "Astrology",
    hook: "LOOK TO THE COSMOS.",
    lines: ["Explore daily zodiac perspectives", "Discover your personalized birth chart", "Try tarot, runes and compatibility readings"],
    outro: "Find a fresh perspective in the stars.",
    accent: "#839cff",
  },
  dreamanalyzer: {
    label: "Dream Analyzer",
    hook: "WHAT DID YOUR DREAM REVEAL?",
    lines: ["Describe the moments you remember", "Explore symbols, emotions and possible themes", "Turn your dream into imaginative visual art"],
    outro: "See your dreams from a new angle.",
    accent: "#72c8e8",
  },
  crystalenergy: {
    label: "Crystal & Energy Network",
    hook: "FIND YOUR INNER BALANCE.",
    lines: ["Explore personalized crystal guidance", "Receive a fresh daily oracle reading", "Reflect on your aura and energy patterns"],
    outro: "Begin your mindful energy journey.",
    accent: "#58d1b4",
  },
  timecapsule: {
    label: "Time Capsule Network",
    hook: "A MESSAGE FOR THE FUTURE.",
    lines: ["Save meaningful words, photos and videos", "Choose a future date for the reveal", "Preserve moments for people who matter"],
    outro: "Create a memory worth reopening.",
    accent: "#ff9b69",
  },
  timereversal: {
    label: "Time Reversal Social",
    hook: "REIMAGINE YOUR TIMELINE.",
    lines: ["Explore playful alternate-life stories", "Create age journeys and reverse biographies", "Share perspectives across the community"],
    outro: "See your story in a different direction.",
    accent: "#ed75be",
  },
  holographicavatars: {
    label: "Holographic Avatars",
    hook: "CREATE YOUR DIGITAL DOUBLE.",
    lines: ["Shape an avatar with unique traits", "Customize its style and personality", "Explore battles, breeding and the marketplace"],
    outro: "Step into a new digital identity.",
    accent: "#54d9df",
  },
  anondate: {
    label: "Anonymous Date",
    hook: "MEET SOMEONE, MYSTERY FIRST.",
    lines: ["Chat safely with a protected anonymous profile", "Get matched by interests, goals and filters", "Reveal identities only when you both agree"],
    outro: "Start a conversation without pressure.",
    accent: "#ff7ba9",
  },
  dating: {
    label: "Dating",
    hook: "REAL PEOPLE. REAL CONNECTIONS.",
    lines: ["Build an authentic profile that shows your style", "Discover matches with smart suggestions", "Chat, connect and take things at your pace"],
    outro: "Find someone worth meeting.",
    accent: "#ff5d6c",
  },
  bestfriend: {
    label: "Best Friend",
    hook: "A FRIEND WHO'S ALWAYS THERE.",
    lines: ["Talk with a supportive AI companion anytime", "Share your day, your plans and your feelings", "Grow a friendship that remembers your story"],
    outro: "Meet your always-on companion.",
    accent: "#b07cff",
  },
  megaforum: {
    label: "Mega Forum",
    hook: "EVERY TOPIC. ONE COMMUNITY.",
    lines: ["Join themed discussions across every interest", "Ask questions and get real answers fast", "Start threads and grow your reputation"],
    outro: "Add your voice to the conversation.",
    accent: "#6fa9ff",
  },
  charactercompanions: {
    label: "Character Companions",
    hook: "STEP INTO THE STORY.",
    lines: ["Chat with unique characters and personas", "Explore roleplay, adventures and scenarios", "Create your own custom companion"],
    outro: "Begin your next adventure.",
    accent: "#ffb54d",
  },
  brokenhearts: {
    label: "Broken Hearts",
    hook: "HEAL, GROW, MOVE FORWARD.",
    lines: ["Process feelings in a safe private space", "Get gentle guidance and daily check-ins", "Rebuild confidence at your own rhythm"],
    outro: "Take the first step to feeling better.",
    accent: "#ff8f6b",
  },
  emotioneconomy: {
    label: "Emotion Economy",
    hook: "YOUR EMOTIONS HAVE VALUE.",
    lines: ["Express moods and reactions across the platform", "Track your emotional journey over time", "Turn authentic engagement into rewards"],
    outro: "Discover the power of feeling.",
    accent: "#63e0a1",
  },
  invitefriends: {
    label: "Invite Friends",
    hook: "BRING A FRIEND, GET REWARDED.",
    lines: ["Share your personal invite link anywhere", "Earn credits when friends join and stay active", "Get bonus rewards on Premium referrals"],
    outro: "Grow together. Earn together.",
    accent: "#ffd94d",
  },
} as const;

export type CategoryTeaserId = keyof typeof CATEGORY_TEASERS;
