-- Insert more recipes - Šaláty, Múčniky, Nápoje, Vegánske, Fitness
INSERT INTO public.recipes (title, category, difficulty, time, servings, calories, image_url, description, ingredients, instructions, tags) VALUES
-- Šaláty (15)
('Grécky šalát', 'Šaláty', 'Ľahké', '15 min', 4, 220, 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe', 'Tradičný grécky šalát', ARRAY['paradajky', 'uhorka', 'feta', 'olivy', 'cibuľa', 'olivový olej'], ARRAY['Nakrájať zeleninu', 'Zmiešať s fetou', 'Poliať dresingom'], ARRAY['grécke', 'vegetariánske', 'bezlepkové']),
('Cézar šalát', 'Šaláty', 'Stredné', '20 min', 2, 380, 'https://images.unsplash.com/photo-1546793665-c74683f339c1', 'Klasický Caesar šalát', ARRAY['rímsky šalát', 'parmezán', 'krutonky', 'ančovičky', 'cesnak'], ARRAY['Pripraviť dresing', 'Zmiešať šalát', 'Posypať parmezánom'], ARRAY['americké', 'klasické']),
('Niçoise', 'Šaláty', 'Stredné', '30 min', 4, 380, 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd', 'Francúzsky tuniak šalát', ARRAY['tuniak', 'vajcia', 'fazuľky', 'paradajky', 'olivy', 'zemiaky'], ARRAY['Uvariť zemiaky a vajcia', 'Zmiešať so zeleninou', 'Pridať tuniak'], ARRAY['francúzske', 'bezlepkové']),
('Waldorf šalát', 'Šaláty', 'Ľahké', '15 min', 4, 280, 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af', 'Americký jablkový šalát', ARRAY['jablká', 'zeler', 'vlašské orechy', 'hrozienka', 'majonéza'], ARRAY['Nakrájať jablká', 'Zmiešať prísady', 'Pridať dresing'], ARRAY['americké', 'vegetariánske']),
('Tabbouleh', 'Šaláty', 'Ľahké', '20 min', 4, 180, 'https://images.unsplash.com/photo-1529059997568-3d847b1154f0', 'Libanonský bulgur šalát', ARRAY['bulgur', 'petržlen', 'paradajky', 'mäta', 'citrón'], ARRAY['Namočiť bulgur', 'Nakrájať zeleninu', 'Zmiešať s citrónom'], ARRAY['blízkovýchodné', 'vegánske']),
('Coleslaw', 'Šaláty', 'Ľahké', '15 min', 6, 150, 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf', 'Kapustový šalát', ARRAY['kapusta', 'mrkva', 'majonéza', 'ocot', 'cukor'], ARRAY['Nastrúhať zeleninu', 'Zmiešať s dresingom'], ARRAY['americké', 'vegetariánske']),
('Fattoush', 'Šaláty', 'Ľahké', '20 min', 4, 200, 'https://images.unsplash.com/photo-1607532941433-304659e8198a', 'Libanonský chlebový šalát', ARRAY['pita', 'paradajky', 'uhorka', 'sumac', 'mäta'], ARRAY['Opiecť pitu', 'Zmiešať so zeleninou', 'Pridať sumac'], ARRAY['blízkovýchodné', 'vegánske']),
('Quinoa šalát', 'Šaláty', 'Ľahké', '25 min', 4, 280, 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71', 'Quinoa so zeleninou', ARRAY['quinoa', 'uhorka', 'paradajky', 'avokádo', 'citrón'], ARRAY['Uvariť quinou', 'Nakrájať zeleninu', 'Zmiešať'], ARRAY['fitness', 'bezlepkové', 'vegánske']),
('Caprese', 'Šaláty', 'Ľahké', '10 min', 2, 220, 'https://images.unsplash.com/photo-1592417817038-d13fd7342e31', 'Taliansky mozzarella šalát', ARRAY['mozzarella', 'paradajky', 'bazalka', 'olivový olej'], ARRAY['Nakrájať mozzarellu a paradajky', 'Poukladať', 'Poliať olejom'], ARRAY['talianske', 'vegetariánske', 'bezlepkové']),
('Zeleninový šalát', 'Šaláty', 'Ľahké', '15 min', 4, 120, 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd', 'Čerstvý šalát', ARRAY['šalát', 'uhorka', 'paradajky', 'paprika', 'olivový olej'], ARRAY['Nakrájať zeleninu', 'Zmiešať', 'Poliať dresingom'], ARRAY['vegánske', 'bezlepkové', 'fitness']),
('Potato šalát', 'Šaláty', 'Stredné', '40 min', 6, 280, 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af', 'Zemiakový šalát', ARRAY['zemiaky', 'vajcia', 'uhorky', 'majonéza', 'horčica'], ARRAY['Uvariť zemiaky', 'Nakrájať prísady', 'Zmiešať s dresingom'], ARRAY['americké', 'vegetariánské']),
('Panzanella', 'Šaláty', 'Ľahké', '20 min', 4, 240, 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af', 'Taliansky chlebový šalát', ARRAY['starý chlieb', 'paradajky', 'uhorka', 'bazalka', 'olivový olej'], ARRAY['Namočiť chlieb', 'Zmiešať so zeleninou'], ARRAY['talianske', 'vegánske']),
('Asian slaw', 'Šaláty', 'Ľahké', '15 min', 4, 180, 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf', 'Ázijský kapustový šalát', ARRAY['kapusta', 'mrkva', 'sezamový olej', 'sójová omáčka', 'sezam'], ARRAY['Nastrúhať zeleninu', 'Pridať ázijský dresing'], ARRAY['ázijské', 'vegánske']),
('Feta šalát', 'Šaláty', 'Ľahké', '15 min', 4, 260, 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe', 'Šalát s fetou a olivami', ARRAY['mix šalátov', 'feta', 'olivy', 'uhorka', 'olivový olej'], ARRAY['Zmiešať šaláty', 'Pridať fetu', 'Poliať dresingom'], ARRAY['grécke', 'vegetariánske', 'bezlepkové']),
('Jarná miešaná', 'Šaláty', 'Ľahké', '20 min', 4, 150, 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd', 'Jarný zeleninový šalát', ARRAY['mix šalátov', 'reďkovka', 'uhorka', 'jarná cibuľka', 'balzamikový ocot'], ARRAY['Nakrájať zeleninu', 'Zmiešať so šalátom', 'Poliať dresingom'], ARRAY['vegánske', 'bezlepkové', 'fitness']),

-- Múčniky (10)
('Trdelník', 'Múčniky', 'Stredné', '1 hod', 8, 320, 'https://images.unsplash.com/photo-1558326567-98ae2405596b', 'Český tradičný múčnik', ARRAY['múka', 'mlieko', 'cukor', 'maslo', 'škorica'], ARRAY['Pripraviť cesto', 'Formovať', 'Piecť a posypať'], ARRAY['české', 'tradičné']),
('Štrúdľa', 'Múčniky', 'Stredné', '1 hod 15 min', 8, 280, 'https://images.unsplash.com/photo-1509440159596-0249088772ff', 'Jablková štrúdľa', ARRAY['cesto', 'jablká', 'cukor', 'škorica', 'hrozienka'], ARRAY['Vyvaľkať cesto', 'Naplniť jablkami', 'Zabaliť a piecť'], ARRAY['tradičné']),
('Koláče', 'Múčniky', 'Stredné', '50 min', 12, 240, 'https://images.unsplash.com/photo-1517433670267-08bbd4be890f', 'Tradičné slovenské koláče', ARRAY['múka', 'mak', 'tvaroh', 'lekvár', 'maslo'], ARRAY['Pripraviť cesto', 'Formovať', 'Piecť'], ARRAY['slovenské', 'tradičné']),
('Bábovka', 'Múčniky', 'Ľahké', '1 hod', 10, 280, 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e', 'Klasická bábovka', ARRAY['múka', 'cukor', 'vajcia', 'mlieko', 'kakao'], ARRAY['Zmiešať prísady', 'Naliať do formy', 'Piecť'], ARRAY['tradičné', 'vegetariánske']),
('Perník', 'Múčniky', 'Ľahké', '1 hod 10 min', 12, 260, 'https://images.unsplash.com/photo-1607478900766-efe13248b125', 'Medový perník', ARRAY['múka', 'med', 'korenie', 'vajcia', 'cukor'], ARRAY['Zmiešať cesto', 'Naliať do formy', 'Piecť'], ARRAY['tradičné', 'vianočné']),
('Linecké koláčiky', 'Múčniky', 'Stredné', '1 hod', 20, 120, 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec', 'Vianočné koláčiky', ARRAY['múka', 'maslo', 'cukor', 'vajcia', 'lekvár'], ARRAY['Pripraviť cesto', 'Vykrajovať', 'Piecť a naplniť'], ARRAY['vianočné', 'tradičné']),
('Makové rezy', 'Múčniky', 'Stredné', '1 hod 30 min', 12, 320, 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d', 'Makový koláč', ARRAY['múka', 'mak', 'cukor', 'vajcia', 'mlieko'], ARRAY['Pripraviť cesto', 'Pripraviť plnku', 'Zapiecť'], ARRAY['tradičné']),
('Krémeš', 'Múčniky', 'Náročné', '2 hod', 12, 380, 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3', 'Vanilkový krémeš', ARRAY['lístky cesta', 'vanilkový krém', 'vajcia', 'mlieko', 'cukor'], ARRAY['Napiecť cesto', 'Pripraviť krém', 'Vrstvit'], ARRAY['slovenské', 'tradičné']),
('Veterník', 'Múčniky', 'Náročné', '1 hod 45 min', 8, 420, 'https://images.unsplash.com/photo-1519869325930-281384150729', 'Veterník s krémom', ARRAY['múka', 'vajcia', 'maslo', 'vanilkový krém', 'karamel'], ARRAY['Napiecť cesto', 'Naplniť krémom', 'Ozdobiť karamelom'], ARRAY['tradičné']),
('Medovník', 'Múčniky', 'Náročné', '2 hod + chlad', 12, 350, 'https://images.unsplash.com/photo-1621303837174-89787a7d4729', 'Medový koláč', ARRAY['múka', 'med', 'vajcia', 'mlieko', 'karamelový krém'], ARRAY['Napiecť plátky', 'Pripraviť krém', 'Vrstvit a chladiť'], ARRAY['tradičné', 'slovenské']),

-- Nápoje (10)
('Smoothie', 'Nápoje', 'Ľahké', '5 min', 2, 180, 'https://images.unsplash.com/photo-1505252585461-04db1eb84625', 'Ovocné smoothie', ARRAY['banán', 'jahody', 'jogurt', 'med', 'ľad'], ARRAY['Rozmixovať všetky prísady'], ARRAY['fitness', 'bezlepkové', 'vegetariánske']),
('Zelené smoothie', 'Nápoje', 'Ľahké', '5 min', 2, 120, 'https://images.unsplash.com/photo-1610970881699-44a5587cabec', 'Detoxikačný nápoj', ARRAY['špenát', 'banán', 'jablko', 'zázvor', 'kokosová voda'], ARRAY['Rozmixovať všetko dokopy'], ARRAY['fitness', 'vegánske', 'detox']),
('Protein shake', 'Nápoje', 'Ľahké', '5 min', 1, 280, 'https://images.unsplash.com/photo-1622483831622-bf6447874960', 'Proteínový nápoj', ARRAY['proteínový prášok', 'banán', 'mlieko', 'arašidové maslo', 'ovos'], ARRAY['Zmiešať v mixéri'], ARRAY['fitness', 'bezlepkové']),
('Limonáda', 'Nápoje', 'Ľahké', '10 min', 4, 80, 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9d', 'Domáca citrónová limonáda', ARRAY['citróny', 'cukor', 'voda', 'mäta', 'ľad'], ARRAY['Vyžmýkať citróny', 'Zmiešať s vodou a cukrom'], ARRAY['vegánske', 'bezlepkové', 'osviežujúce']),
('Horúca čokoláda', 'Nápoje', 'Ľahké', '10 min', 2, 240, 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed', 'Krémová horúca čokoláda', ARRAY['mlieko', 'čokoláda', 'cukor', 'šľahačka', 'marshmallows'], ARRAY['Rozpustiť čokoládu v mlieku', 'Ozdobiť šľahačkou'], ARRAY['vegetariánske', 'bezlepkové']),
('Ľadová káva', 'Nápoje', 'Ľahké', '5 min', 1, 120, 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7', 'Osviežujúca ľadová káva', ARRAY['káva', 'mlieko', 'ľad', 'cukor', 'karamel'], ARRAY['Uvariť kávu', 'Pridať ľad a mlieko'], ARRAY['vegetariánske', 'bezlepkové']),
('Mojito', 'Nápoje', 'Ľahké', '5 min', 1, 140, 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a', 'Kubánsky koktail', ARRAY['mäta', 'limetka', 'cukor', 'sódovka', 'rum'], ARRAY['Rozdrviť mätu', 'Zmiešať prísady'], ARRAY['osviežujúce']),
('Zázvorový čaj', 'Nápoje', 'Ľahké', '15 min', 2, 40, 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12', 'Hrejivý zázvorový čaj', ARRAY['zázvor', 'citrón', 'med', 'voda'], ARRAY['Uvariť zázvor', 'Pridať citrón a med'], ARRAY['vegánske', 'bezlepkové', 'zdravé']),
('Matcha latte', 'Nápoje', 'Ľahké', '5 min', 1, 150, 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7', 'Japonský zelený čaj latte', ARRAY['matcha prášok', 'mlieko', 'cukor', 'horúca voda'], ARRAY['Zmiešať matchu', 'Pridať mlieko'], ARRAY['vegetariánske', 'bezlepkové']),
('Fresh juice', 'Nápoje', 'Ľahké', '5 min', 2, 100, 'https://images.unsplash.com/photo-1600271886742-f049cd451bba', 'Čerstvý ovocný džús', ARRAY['pomaranče', 'jablká', 'mrkva', 'zázvor'], ARRAY['Rozmixovať ovocie'], ARRAY['vegánske', 'bezlepkové', 'fitness']),

-- Vegánske (10)
('Vegánske burger', 'Vegánske', 'Stredné', '40 min', 4, 420, 'https://images.unsplash.com/photo-1520072959219-c595dc870360', 'Burger z čiernych fazulí', ARRAY['čierne fazule', 'quinoa', 'cibuľa', 'cesnak', 'korenie'], ARRAY['Rozmixovať fazule', 'Formovať placky', 'Opiecť'], ARRAY['vegánske', 'fitness']),
('Tofu stir-fry', 'Vegánske', 'Ľahké', '25 min', 2, 320, 'https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f', 'Smažené tofu so zeleninou', ARRAY['tofu', 'brokolica', 'paprika', 'sójová omáčka', 'cesnak'], ARRAY['Nakrájať tofu', 'Osmažiť so zeleninou', 'Pridať omáčku'], ARRAY['vegánske', 'ázijské', 'bezlepkové']),
('Falafel', 'Vegánske', 'Stredné', '30 min', 4, 280, 'https://images.unsplash.com/photo-1601050690597-df0568f70950', 'Blízkovýchodné cícerové guličky', ARRAY['cícer', 'petržlen', 'cesnak', 'koreničková soľ', 'sezam'], ARRAY['Rozmixovať cícer', 'Formovať guličky', 'Smažiť'], ARRAY['vegánske', 'blízkovýchodné']),
('Vegánske curry', 'Vegánske', 'Stredné', '35 min', 4, 380, 'https://images.unsplash.com/photo-1585937421612-70a008356fbe', 'Kokosové curry so zeleninou', ARRAY['zelenina', 'kokosové mlieko', 'curry pasta', 'tofu', 'ryža'], ARRAY['Opražiť curry', 'Pridať zeleninu', 'Doliať kokosovým mliekom'], ARRAY['vegánske', 'ázijské', 'bezlepkové']),
('Vegánska pizza', 'Vegánske', 'Stredné', '45 min', 4, 380, 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002', 'Pizza bez živočíšnych produktov', ARRAY['cesto', 'paradajková omáčka', 'zelenina', 'vegánsky syr'], ARRAY['Pripraviť cesto', 'Pridať prísady', 'Piecť'], ARRAY['vegánske', 'talianske']),
('Buddha bowl', 'Vegánske', 'Ľahké', '30 min', 2, 350, 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd', 'Výživná misa', ARRAY['quinoa', 'sladké zemiaky', 'cícer', 'avokádo', 'tahini'], ARRAY['Upiecť zemiaky', 'Uvariť quinou', 'Poukladať do misy'], ARRAY['vegánske', 'fitness', 'bezlepkové']),
('Vegánske lasagne', 'Vegánske', 'Náročné', '1 hod 30 min', 6, 420, 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3', 'Lasagne so zeleninou', ARRAY['lasagne plátky', 'paradajková omáčka', 'zelenina', 'vegánsky bešamel'], ARRAY['Pripraviť omáčky', 'Vrstvit', 'Zapiecť'], ARRAY['vegánske', 'talianske']),
('Vegánske tacos', 'Vegánske', 'Ľahké', '25 min', 4, 320, 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b', 'Mexické tacos', ARRAY['tortilla', 'fazule', 'avokádo', 'kukurica', 'salsa'], ARRAY['Pripraviť fazule', 'Naplniť tortilly', 'Pridať prísady'], ARRAY['vegánske', 'mexické']),
('Hummus wrap', 'Vegánske', 'Ľahké', '15 min', 2, 280, 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f', 'Hummus so zeleninou v tortille', ARRAY['tortilla', 'hummus', 'zelenina', 'šalát'], ARRAY['Natierať hummus', 'Pridať zeleninu', 'Zabaliť'], ARRAY['vegánske', 'rýchle']),
('Vegánske chilli', 'Vegánske', 'Stredné', '45 min', 6, 320, 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143', 'Pikantné fazuľové chilli', ARRAY['fazule', 'paradajky', 'kukurica', 'paprika', 'chilli'], ARRAY['Opražiť zeleninu', 'Pridať fazule', 'Variť pomaly'], ARRAY['vegánske', 'mexické', 'bezlepkové']);
