-- Update remaining Slovak recipes to English (batch 5)
UPDATE recipes SET ingredients = ARRAY['tart shell', 'lemons', 'eggs', 'sugar', 'butter'], instructions = ARRAY['Make lemon curd', 'Fill tart shell', 'Chill until set'] WHERE id = 'e8c59f28-b115-4ad4-87d9-4244ace66d2c';
UPDATE recipes SET ingredients = ARRAY['potatoes', 'mayonnaise', 'mustard', 'celery', 'onion', 'eggs'], instructions = ARRAY['Boil and cube potatoes', 'Mix dressing', 'Combine all ingredients', 'Chill before serving'] WHERE id = 'b23cfd78-edba-4dcb-86a8-d7603bcb53d3';
UPDATE recipes SET ingredients = ARRAY['tuna', 'green beans', 'potatoes', 'eggs', 'olives', 'anchovies', 'tomatoes'], instructions = ARRAY['Arrange all ingredients on plate', 'Drizzle with vinaigrette'] WHERE id = '20dc764b-1dc6-40c0-8346-3d9352af3f8e';
UPDATE recipes SET ingredients = ARRAY['romaine lettuce', 'parmesan', 'croutons', 'Caesar dressing'], instructions = ARRAY['Tear lettuce', 'Add dressing', 'Top with parmesan and croutons'] WHERE id = '180a76c9-944d-475d-806f-4af83bc31be0';
UPDATE recipes SET ingredients = ARRAY['tagliatelle', 'butter', 'cream', 'parmesan', 'garlic'], instructions = ARRAY['Cook pasta', 'Make cream sauce', 'Toss together', 'Serve with parmesan'] WHERE id = '42427b33-d6d8-454f-ab0c-eb6c3fe5baab';
UPDATE recipes SET ingredients = ARRAY['spaghetti', 'pecorino romano', 'black pepper', 'pasta water'], instructions = ARRAY['Cook pasta', 'Mix cheese with pepper', 'Toss with pasta and water', 'Serve immediately'] WHERE id = '6c24b36c-43a2-47ae-ba0a-fc78bd596896';
UPDATE recipes SET ingredients = ARRAY['arborio rice', 'mushrooms', 'onion', 'white wine', 'broth', 'parmesan', 'butter'], instructions = ARRAY['Saute mushrooms and set aside', 'Toast rice', 'Add wine', 'Gradually add broth', 'Stir in mushrooms and cheese'] WHERE id = 'de6d4e7f-0d66-4c70-ac42-0a899d0cff6f';
UPDATE recipes SET ingredients = ARRAY['flour', 'cocoa powder', 'sugar', 'eggs', 'butter', 'chocolate'], instructions = ARRAY['Mix dry ingredients', 'Beat eggs with sugar', 'Combine and bake', 'Frost with chocolate'] WHERE id = 'd9011d2b-e414-49ff-b148-9fb3121f822b';
UPDATE recipes SET ingredients = ARRAY['trofie pasta', 'basil pesto', 'potatoes', 'green beans', 'parmesan'], instructions = ARRAY['Cook pasta with vegetables', 'Toss with pesto', 'Serve with cheese'] WHERE id = '3e78c338-a778-459b-839d-1692e5a32d28';
UPDATE recipes SET ingredients = ARRAY['dough', 'sugar', 'cinnamon', 'walnuts'], instructions = ARRAY['Wrap dough around cylinder', 'Grill over charcoal', 'Coat with sugar and nuts'] WHERE id = '593a86a3-7b0c-4c60-9527-0113ab4fd9fd';
UPDATE recipes SET ingredients = ARRAY['phyllo dough', 'apples', 'raisins', 'breadcrumbs', 'cinnamon', 'sugar'], instructions = ARRAY['Prepare apple filling', 'Layer phyllo sheets', 'Roll with filling', 'Bake until golden'] WHERE id = 'fbb04847-c4ec-4110-a8e6-fc4f7dfa3460';
UPDATE recipes SET ingredients = ARRAY['ladyfingers', 'mascarpone', 'espresso', 'eggs', 'sugar', 'cocoa powder'], instructions = ARRAY['Make mascarpone cream', 'Dip ladyfingers in coffee', 'Layer cream and cookies', 'Dust with cocoa'] WHERE id = 'ba733cb9-daaa-4fa6-8fb3-267aada7c887';
UPDATE recipes SET ingredients = ARRAY['flour', 'butter', 'sugar', 'eggs', 'jam filling'], instructions = ARRAY['Make dough', 'Roll and cut shapes', 'Fill with jam', 'Bake'] WHERE id = '187929f2-a7a8-46e6-8cc6-69df6731d719';
UPDATE recipes SET ingredients = ARRAY['flour', 'butter', 'powdered sugar', 'almonds', 'jam'], instructions = ARRAY['Make shortbread dough', 'Cut into shapes', 'Bake until golden', 'Sandwich with jam'] WHERE id = 'e4db2dd6-3839-416d-aa95-870fcb1d3930';
UPDATE recipes SET ingredients = ARRAY['poppy seeds', 'flour', 'butter', 'sugar', 'eggs', 'milk'], instructions = ARRAY['Grind poppy seeds', 'Make cake batter', 'Add poppy filling', 'Bake and slice'] WHERE id = 'c1a00f51-f8e5-441a-aed7-1fa81497acc7';