-- Update remaining Slovak recipes to English (batch 4)
UPDATE recipes SET ingredients = ARRAY['200ml milk', '50g dark chocolate', '2 tbsp cocoa powder', '2 tbsp sugar', 'whipped cream'], instructions = ARRAY['Heat milk', 'Add chocolate and cocoa', 'Stir until dissolved', 'Top with whipped cream'] WHERE id = '99c8240f-47f9-44a1-ace8-79ff46edb92d';
UPDATE recipes SET ingredients = ARRAY['2 shots espresso', '200ml milk', 'ice cubes', 'sugar syrup'], instructions = ARRAY['Brew espresso and cool', 'Fill glass with ice', 'Pour coffee and milk', 'Add syrup to taste'] WHERE id = '2b083ad9-0c09-4e14-8296-90f9ccdd682b';
UPDATE recipes SET ingredients = ARRAY['fresh ginger (5cm)', 'honey', 'lemon', 'hot water'], instructions = ARRAY['Slice ginger', 'Pour hot water', 'Add honey and lemon'] WHERE id = 'd48e626a-7fa2-4c63-b65a-d409dc3b3515';
UPDATE recipes SET ingredients = ARRAY['spinach', 'banana', 'apple', 'cucumber', 'lemon juice', 'water'], instructions = ARRAY['Add all ingredients to blender', 'Blend until smooth', 'Serve immediately'] WHERE id = '35fc5e13-1cb7-445c-87d9-95f8afdd0776';
UPDATE recipes SET ingredients = ARRAY['pizza dough', 'tomato sauce', 'garlic', 'olive oil', 'oregano'], instructions = ARRAY['Stretch dough', 'Spread sauce', 'Add garlic and oil', 'Bake until crispy'] WHERE id = '19015d06-be7b-4ea9-93b4-7208c877b7c0';
UPDATE recipes SET ingredients = ARRAY['protein powder', 'banana', 'milk', 'peanut butter', 'oats'], instructions = ARRAY['Add all ingredients to blender', 'Blend until smooth'] WHERE id = '104065c3-feea-45e9-b33a-1cad60673195';
UPDATE recipes SET ingredients = ARRAY['4 lemons', '100g sugar', '1 liter water', 'fresh mint', 'ice'], instructions = ARRAY['Squeeze lemons', 'Make sugar syrup', 'Mix juice with syrup and water', 'Serve with ice and mint'] WHERE id = '869c4b93-bc61-495c-852f-6282ed618f11';
UPDATE recipes SET ingredients = ARRAY['400g firm tofu', 'mixed vegetables', 'soy sauce', 'sesame oil', 'garlic', 'ginger'], instructions = ARRAY['Press and cube tofu', 'Stir-fry until golden', 'Add vegetables and sauce', 'Serve over rice'] WHERE id = 'a9f9167b-667f-46bf-a953-5d12b4a941be';
UPDATE recipes SET ingredients = ARRAY['bell peppers', 'olive oil', 'garlic', 'salt'], instructions = ARRAY['Roast peppers until charred', 'Peel and slice', 'Season with oil and garlic'] WHERE id = 'e4ebe5e8-407f-4cc1-a891-9035b1f65287';
UPDATE recipes SET ingredients = ARRAY['rice paper', 'rice noodles', 'shrimp', 'vegetables', 'herbs', 'dipping sauce'], instructions = ARRAY['Soften rice paper', 'Add fillings', 'Roll tightly', 'Serve with sauce'] WHERE id = 'a2e1e29c-fae3-4be9-b8a5-d31ab1e80b18';
UPDATE recipes SET ingredients = ARRAY['4 large onions', 'beef broth', 'butter', 'white wine', 'gruyere cheese', 'baguette'], instructions = ARRAY['Caramelize onions slowly', 'Add wine and broth', 'Simmer 30 minutes', 'Top with bread and cheese', 'Broil until bubbly'] WHERE id = 'e330a87b-a46b-4928-a5a4-7434f4251f60';
UPDATE recipes SET ingredients = ARRAY['2 ribeye steaks', 'potatoes', 'butter', 'salt', 'pepper', 'garlic'], instructions = ARRAY['Season steaks', 'Pan-sear to preference', 'Make crispy fries', 'Serve together'] WHERE id = '73c3820b-f6be-4ce7-8d55-47927f61ef63';
UPDATE recipes SET ingredients = ARRAY['chicken thighs', 'soy sauce', 'mirin', 'sake', 'sugar', 'ginger'], instructions = ARRAY['Make teriyaki sauce', 'Grill chicken', 'Glaze with sauce', 'Serve over rice'] WHERE id = '3d10010b-cc1f-42a4-87f3-496b7f5d23ac';
UPDATE recipes SET ingredients = ARRAY['500ml cream', 'sugar', 'vanilla', 'gelatin', 'berry sauce'], instructions = ARRAY['Heat cream with sugar and vanilla', 'Add bloomed gelatin', 'Pour into molds', 'Chill until set', 'Serve with berry sauce'] WHERE id = '1efafd71-c502-4b06-a2a1-83a414a55eb9';
UPDATE recipes SET ingredients = ARRAY['pie crust', 'apples', 'sugar', 'cinnamon', 'butter', 'lemon juice'], instructions = ARRAY['Make pie crust', 'Slice and season apples', 'Fill crust', 'Top with second crust', 'Bake until golden'] WHERE id = '7cfd35b8-7ec1-417b-a9d8-8d549f8cc48f';