-- Insert more recipes to reach 100+ total
INSERT INTO public.recipes (title, category, difficulty, time, servings, calories, image_url, description, ingredients, instructions, tags) VALUES
-- Cestoviny (10)
('Carbonara', 'Cestoviny', 'Stredné', '30 min', 2, 620, 'https://images.unsplash.com/photo-1612874742237-6526221588e3', 'Rímske cestoviny so slaninou a vajcami', ARRAY['400g špagiet', '150g slaniny', '3 vajcia', 'parmezán', 'čierne korenie'], ARRAY['Uvariť cestoviny', 'Osmažiť slaninu', 'Zmiešať s vajcami a syrom'], ARRAY['talianske', 'klasické']),
('Aglio e Olio', 'Cestoviny', 'Ľahké', '20 min', 2, 480, 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9', 'Jednoduché cestoviny s cesnakom', ARRAY['400g špagiet', '6 strúčikov cesnaku', 'olivový olej', 'chilli', 'petržlen'], ARRAY['Uvariť špagety', 'Osmažiť cesnak v oleji', 'Zmiešať'], ARRAY['talianske', 'vegánske']),
('Pesto pasta', 'Cestoviny', 'Ľahké', '25 min', 4, 520, 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601', 'Cestoviny s bazalkovým pestom', ARRAY['pasta', 'bazalka', 'pínové oriešky', 'parmezán', 'cesnak'], ARRAY['Uvariť cestoviny', 'Zmiešať s pestom'], ARRAY['talianske', 'vegetariánske']),
('Arrabiata', 'Cestoviny', 'Ľahké', '30 min', 4, 450, 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9', 'Pikantné paradajkové cestoviny', ARRAY['penne', 'paradajky', 'cesnak', 'chilli', 'olivový olej'], ARRAY['Pripraviť omáčku', 'Uvariť cestoviny', 'Zmiešať'], ARRAY['talianske', 'pikantné', 'vegánske']),
('Mac and Cheese', 'Cestoviny', 'Stredné', '35 min', 4, 580, 'https://images.unsplash.com/photo-1559054663-e8ee6e9e6d93', 'Americké syrové cestoviny', ARRAY['makaróny', 'čedar syr', 'mlieko', 'maslo', 'múka'], ARRAY['Uvariť makaróny', 'Pripraviť syrovú omáčku', 'Zmiešať a zapiecť'], ARRAY['americké', 'vegetariánske']),
('Tagliatelle Alfredo', 'Cestoviny', 'Stredné', '25 min', 2, 650, 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a', 'Krémové cestoviny s parmezánom', ARRAY['tagliatelle', 'smotana', 'parmezán', 'maslo', 'cesnak'], ARRAY['Uvariť cestoviny', 'Pripraviť smotanovú omáčku', 'Servírovať'], ARRAY['talianske', 'vegetariánske']),
('Bolognese', 'Cestoviny', 'Náročné', '2 hod', 6, 520, 'https://images.unsplash.com/photo-1598866594230-a7c12756260f', 'Klasická talianska mäsová omáčka', ARRAY['mleté mäso', 'paradajky', 'mrkva', 'zeler', 'červené víno'], ARRAY['Opražiť zeleninu', 'Pridať mäso', 'Variť pomaly'], ARRAY['talianske', 'klasické']),
('Cacio e Pepe', 'Cestoviny', 'Stredné', '20 min', 2, 480, 'https://images.unsplash.com/photo-1633337474564-1d9478ca4e2e', 'Rímske cestoviny so syrom a korením', ARRAY['špagety', 'pecorino syr', 'čierne korenie', 'soľ'], ARRAY['Uvariť cestoviny', 'Zmiešať so syrom a korením'], ARRAY['talianske', 'vegetariánske']),
('Puttanesca', 'Cestoviny', 'Ľahké', '30 min', 4, 420, 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9', 'Cestoviny s olivami a kapary', ARRAY['špagety', 'paradajky', 'olivy', 'kapary', 'ančovičky'], ARRAY['Pripraviť omáčku', 'Uvariť cestoviny', 'Zmiešať'], ARRAY['talianske', 'bezlepkové']),
('Trofie al pesto', 'Cestoviny', 'Stredné', '35 min', 4, 540, 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9', 'Ligúrske cestoviny s pestom', ARRAY['trofie pasta', 'bazalkové pesto', 'zemiaky', 'fazuľky', 'parmezán'], ARRAY['Uvariť cestoviny so zeleninou', 'Pridať pesto'], ARRAY['talianske', 'vegetariánske']),

-- Pizza (10)
('Margherita pizza', 'Pizza', 'Stredné', '45 min', 4, 380, 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002', 'Klasická talianska pizza', ARRAY['cesto', 'paradajková omáčka', 'mozzarella', 'bazalka', 'olivový olej'], ARRAY['Pripraviť cesto', 'Natierať omáčkou', 'Piecť v rúre'], ARRAY['talianske', 'vegetariánske']),
('Quattro Formaggi', 'Pizza', 'Stredné', '50 min', 4, 520, 'https://images.unsplash.com/photo-1513104890138-7c749659a591', 'Pizza so štyrmi syrmi', ARRAY['cesto', 'mozzarella', 'gorgonzola', 'parmezán', 'fontina'], ARRAY['Pripraviť cesto', 'Posypať syrmi', 'Piecť'], ARRAY['talianske', 'vegetariánske']),
('Diavola', 'Pizza', 'Stredné', '45 min', 4, 450, 'https://images.unsplash.com/photo-1628840042765-356cda07504e', 'Pikantná pizza s klobásou', ARRAY['cesto', 'paradajková omáčka', 'mozzarella', 'pikantná klobása', 'chilli'], ARRAY['Pripraviť cesto', 'Pridať prísady', 'Piecť'], ARRAY['talianske', 'pikantné']),
('Prosciutto e Funghi', 'Pizza', 'Stredné', '50 min', 4, 420, 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38', 'Pizza so šunkou a hubami', ARRAY['cesto', 'paradajková omáčka', 'mozzarella', 'šunka', 'huby'], ARRAY['Pripraviť cesto', 'Pridať prísady', 'Piecť'], ARRAY['talianske']),
('Capricciosa', 'Pizza', 'Stredné', '55 min', 4, 480, 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f', 'Zmiešaná pizza', ARRAY['cesto', 'paradajková omáčka', 'mozzarella', 'šunka', 'huby', 'artičoky', 'olivy'], ARRAY['Pripraviť cesto', 'Pridať všetky prísady', 'Piecť'], ARRAY['talianske']),
('Marinara', 'Pizza', 'Ľahké', '40 min', 4, 320, 'https://images.unsplash.com/photo-1590534047443-4cdb2d2f3d93', 'Jednoduchá pizza bez syra', ARRAY['cesto', 'paradajková omáčka', 'cesnak', 'oregano', 'olivový olej'], ARRAY['Pripraviť cesto', 'Natierať omáčkou', 'Piecť'], ARRAY['talianske', 'vegánske']),
('Vegetariana', 'Pizza', 'Stredné', '50 min', 4, 400, 'https://images.unsplash.com/photo-1574126154517-d1e0d89ef734', 'Zeleninová pizza', ARRAY['cesto', 'paradajková omáčka', 'mozzarella', 'paprika', 'cuketa', 'baklažán'], ARRAY['Pripraviť cesto', 'Pridať zeleninu', 'Piecť'], ARRAY['talianske', 'vegetariánske']),
('Calzone', 'Pizza', 'Stredné', '45 min', 2, 550, 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e', 'Skladaná pizza', ARRAY['cesto', 'ricotta', 'mozzarella', 'šunka', 'paradajková omáčka'], ARRAY['Pripraviť cesto', 'Naplniť a zložiť', 'Piecť'], ARRAY['talianske']),
('Tonno e Cipolla', 'Pizza', 'Stredné', '45 min', 4, 420, 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38', 'Pizza s tuňiakom', ARRAY['cesto', 'paradajková omáčka', 'mozzarella', 'tuniak', 'cibuľa'], ARRAY['Pripraviť cesto', 'Pridať prísady', 'Piecť'], ARRAY['talianske', 'morské plody']),
('Bianca', 'Pizza', 'Stredné', '40 min', 4, 450, 'https://images.unsplash.com/photo-1513104890138-7c749659a591', 'Biela pizza bez paradajok', ARRAY['cesto', 'mozzarella', 'ricotta', 'cesnak', 'rozmarín'], ARRAY['Pripraviť cesto', 'Pridať syry a korenie', 'Piecť'], ARRAY['talianske', 'vegetariánske']),

-- Dezerty (15)
('Tiramisu', 'Dezerty', 'Stredné', '30 min + chlad', 6, 390, 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9', 'Taliansky dezert s mascarpone', ARRAY['piškóty', 'mascarpone', 'káva', 'kakao', 'vajcia'], ARRAY['Namočiť piškóty', 'Striedať s krémom', 'Chladiť'], ARRAY['talianske', 'klasické']),
('Panna cotta', 'Dezerty', 'Stredné', '20 min + chlad', 4, 320, 'https://images.unsplash.com/photo-1488477181946-6428a0291777', 'Krémový taliansky dezert', ARRAY['smotana', 'cukor', 'želatína', 'vanilka', 'ovocie'], ARRAY['Zohriať smotanu', 'Pridať želatínu', 'Chladiť'], ARRAY['talianske', 'bezlepkové']),
('Čokoládová torta', 'Dezerty', 'Stredné', '1 hod 20 min', 8, 450, 'https://images.unsplash.com/photo-1578985545062-69928b1d9587', 'Bohatá čokoládová torta', ARRAY['múka', 'čokoláda', 'vajcia', 'cukor', 'maslo'], ARRAY['Zmiešať prísady', 'Piecť', 'Ozdobíť krémom'], ARRAY['čokoládové']),
('Cheesecake', 'Dezerty', 'Náročné', '1 hod + chlad', 10, 480, 'https://images.unsplash.com/photo-1533134242820-b77cf0b8f9c3', 'Americký syrový koláč', ARRAY['piškóty', 'cream cheese', 'cukor', 'vajcia', 'smotana'], ARRAY['Pripraviť základ', 'Zmiešať krém', 'Piecť a chladiť'], ARRAY['americké']),
('Crème brûlée', 'Dezerty', 'Náročné', '1 hod + chlad', 4, 380, 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc', 'Francúzsky krémový dezert', ARRAY['smotana', 'žĺtky', 'cukor', 'vanilka'], ARRAY['Pripraviť krém', 'Piecť vo vodnom kúpeli', 'Karamelizovať'], ARRAY['francúzske', 'bezlepkové']),
('Brownies', 'Dezerty', 'Ľahké', '40 min', 12, 350, 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c', 'Čokoládové kocky', ARRAY['čokoláda', 'maslo', 'cukor', 'vajcia', 'múka'], ARRAY['Rozpustiť čokoládu', 'Zmiešať prísady', 'Piecť'], ARRAY['americké', 'čokoládové']),
('Apple pie', 'Dezerty', 'Stredné', '1 hod 15 min', 8, 320, 'https://images.unsplash.com/photo-1535920527002-b35e96722eb9', 'Americký jablkový koláč', ARRAY['jablká', 'cesto', 'cukor', 'škorica', 'maslo'], ARRAY['Pripraviť cesto', 'Naplniť jablkami', 'Piecť'], ARRAY['americké']),
('Pavlova', 'Dezerty', 'Stredné', '2 hod', 8, 280, 'https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81', 'Dezert z bielkov', ARRAY['bielky', 'cukor', 'smotana', 'ovocie'], ARRAY['Vyšľahať bielky', 'Piecť', 'Ozdobiť'], ARRAY['bezlepkové']),
('Profiteroles', 'Dezerty', 'Náročné', '1 hod 30 min', 6, 420, 'https://images.unsplash.com/photo-1612203985729-70726954388c', 'Francúzske veterníky', ARRAY['múka', 'vajcia', 'maslo', 'šľahačka', 'čokoláda'], ARRAY['Pripraviť cesto', 'Napiecť', 'Naplniť krémom'], ARRAY['francúzske']),
('Lemon tart', 'Dezerty', 'Stredné', '1 hod', 8, 350, 'https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e', 'Citrónový koláč', ARRAY['cesto', 'citróny', 'vajcia', 'cukor', 'maslo'], ARRAY['Pripraviť cesto', 'Naplniť citrónovou plnkou', 'Piecť'], ARRAY['francúzske']),
('Macarons', 'Dezerty', 'Náročné', '2 hod', 20, 90, 'https://images.unsplash.com/photo-1569864358642-9d1684040f43', 'Francúzske mandľové pusinky', ARRAY['mandľová múka', 'cukor', 'bielky', 'krém'], ARRAY['Vyšľahať bielky', 'Vytvarovať', 'Piecť a naplniť'], ARRAY['francúzske', 'bezlepkové']),
('Muffins', 'Dezerty', 'Ľahké', '35 min', 12, 280, 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa', 'Americké koláčiky', ARRAY['múka', 'cukor', 'vajcia', 'mlieko', 'ovocie'], ARRAY['Zmiešať prísady', 'Naplniť formičky', 'Piecť'], ARRAY['americké']),
('Baklava', 'Dezerty', 'Náročné', '1 hod 30 min', 12, 350, 'https://images.unsplash.com/photo-1519676867240-f03562e64548', 'Turecký dezert s orieškami', ARRAY['filo cesto', 'oriešky', 'med', 'maslo', 'škorica'], ARRAY['Vrstvit cesto', 'Posypať orieškami', 'Zalievať medom'], ARRAY['turecké', 'stredovýchodné']),
('Palacinky', 'Dezerty', 'Ľahké', '30 min', 4, 320, 'https://images.unsplash.com/photo-1528207776546-365bb710ee93', 'Tenké palacinky', ARRAY['múka', 'mlieko', 'vajcia', 'cukor', 'džem'], ARRAY['Zmiešať cesto', 'Smažiť', 'Podávať s plnkou'], ARRAY['tradičné', 'vegetariánske']),
('Puding', 'Dezerty', 'Ľahké', '20 min + chlad', 4, 240, 'https://images.unsplash.com/photo-1563805042-7684c019e1cb', 'Krémový dezert', ARRAY['mlieko', 'cukor', 'škrob', 'vanilka', 'vajce'], ARRAY['Zohriať mlieko', 'Pridať škrob', 'Chladiť'], ARRAY['tradičné', 'bezlepkové']);
