-- Add 80 more paint by numbers images to reach 100 total

INSERT INTO paint_by_numbers (title, category, difficulty, price_coins, total_sections, image_data) VALUES
-- Fairy Tales (20 more)
('Rapunzel Tower', 'fairy-tales', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Little Red Riding Hood', 'fairy-tales', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Three Little Pigs', 'fairy-tales', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Hansel and Gretel', 'fairy-tales', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Jack and Beanstalk', 'fairy-tales', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Thumbelina', 'fairy-tales', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Snow Queen', 'fairy-tales', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Aladdin Lamp', 'fairy-tales', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Peter Pan Flying', 'fairy-tales', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Tinkerbell', 'fairy-tales', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Ariel Mermaid', 'fairy-tales', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Belle Library', 'fairy-tales', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Elsa Ice Palace', 'fairy-tales', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Moana Ocean', 'fairy-tales', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Jasmine Palace', 'fairy-tales', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Mulan Warrior', 'fairy-tales', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Pocahontas Nature', 'fairy-tales', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Tiana Restaurant', 'fairy-tales', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Brave Merida', 'fairy-tales', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Frozen Sisters', 'fairy-tales', 'hard', 80, 20, '{"sections": [], "colors": []}'),

-- Animals (30 more)
('Tiger Cub', 'animals', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Baby Penguin', 'animals', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Koala Bear', 'animals', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Giraffe Family', 'animals', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Zebra Stripes', 'animals', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Panda Playing', 'animals', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Monkey Jungle', 'animals', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Polar Bear', 'animals', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Flamingo Pink', 'animals', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Peacock Feathers', 'animals', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Owl Wisdom', 'animals', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Eagle Flying', 'animals', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Hummingbird', 'animals', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Toucan Tropical', 'animals', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Sea Turtle', 'animals', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Whale Ocean', 'animals', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Shark Swimming', 'animals', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Jellyfish Glow', 'animals', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Octopus Smart', 'animals', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Clownfish Nemo', 'animals', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Starfish Beach', 'animals', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Seahorse Magic', 'animals', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Bunny Rabbit', 'animals', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Fox Forest', 'animals', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Deer Bambi', 'animals', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Squirrel Nuts', 'animals', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Hedgehog Cute', 'animals', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Raccoon Mask', 'animals', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Wolf Moon', 'animals', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Horse Gallop', 'animals', 'hard', 80, 20, '{"sections": [], "colors": []}'),

-- Nature (15 more)
('Rainbow Sky', 'nature', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Aurora Borealis', 'nature', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Waterfall Paradise', 'nature', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Desert Dunes', 'nature', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Forest Path', 'nature', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Tropical Island', 'nature', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Cherry Blossoms', 'nature', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Autumn Leaves', 'nature', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Winter Wonderland', 'nature', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Spring Garden', 'nature', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Volcano Eruption', 'nature', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Coral Reef', 'nature', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Lightning Storm', 'nature', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Full Moon Night', 'nature', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Solar System', 'nature', 'hard', 80, 20, '{"sections": [], "colors": []}'),

-- Vehicles (15 more)
('School Bus', 'vehicles', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Police Car', 'vehicles', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Ambulance', 'vehicles', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Garbage Truck', 'vehicles', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Monster Truck', 'vehicles', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Train Engine', 'vehicles', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Helicopter', 'vehicles', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Hot Air Balloon', 'vehicles', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Sailboat', 'vehicles', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Submarine', 'vehicles', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Cruise Ship', 'vehicles', 'hard', 80, 20, '{"sections": [], "colors": []}'),
('Motorcycle', 'vehicles', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Bicycle', 'vehicles', 'easy', 30, 8, '{"sections": [], "colors": []}'),
('Tractor Farm', 'vehicles', 'medium', 50, 12, '{"sections": [], "colors": []}'),
('Excavator', 'vehicles', 'medium', 50, 12, '{"sections": [], "colors": []}');