-- Fix Slovak achievement names to English and fix text icons to emojis

-- Fix "Lovec XP" to "XP Hunter"
UPDATE achievements SET name = 'XP Hunter I' WHERE code = 'xp_hunter_1';
UPDATE achievements SET name = 'XP Hunter II' WHERE code = 'xp_hunter_2';
UPDATE achievements SET name = 'XP Hunter III' WHERE code = 'xp_hunter_3';
UPDATE achievements SET name = 'XP Hunter IV' WHERE code = 'xp_hunter_4';
UPDATE achievements SET name = 'XP Hunter V' WHERE code = 'xp_hunter_5';

-- Fix broken text icons to proper emojis
UPDATE achievements SET icon = '❤️' WHERE icon = 'Heart' OR icon = 'heart';
UPDATE achievements SET icon = '⭐' WHERE icon = 'Star' OR icon = 'star';
UPDATE achievements SET icon = '💬' WHERE icon = 'MessageCircle' OR icon = 'messagecircle';
UPDATE achievements SET icon = '👨‍🍳' WHERE icon = 'ChefHat' OR icon = 'chefhat';
UPDATE achievements SET icon = '🏆' WHERE icon = 'Trophy' OR icon = 'trophy';
UPDATE achievements SET icon = '👍' WHERE icon = 'ThumbsUp' OR icon = 'thumbsup';
UPDATE achievements SET icon = '🔥' WHERE icon = 'Flame' OR icon = 'flame';
UPDATE achievements SET icon = '📷' WHERE icon = 'Camera' OR icon = 'camera';
UPDATE achievements SET icon = '🎬' WHERE icon = 'Video' OR icon = 'video';
UPDATE achievements SET icon = '🎥' WHERE icon = 'Film' OR icon = 'film';
UPDATE achievements SET icon = '📱' WHERE icon = 'Smartphone' OR icon = 'smartphone';
UPDATE achievements SET icon = '💡' WHERE icon = 'Lightbulb' OR icon = 'lightbulb';
UPDATE achievements SET icon = '🎯' WHERE icon = 'Target' OR icon = 'target';
UPDATE achievements SET icon = '🏅' WHERE icon = 'Medal' OR icon = 'medal';
UPDATE achievements SET icon = '👑' WHERE icon = 'Crown' OR icon = 'crown';
UPDATE achievements SET icon = '🎁' WHERE icon = 'Gift' OR icon = 'gift';
UPDATE achievements SET icon = '📝' WHERE icon = 'Edit' OR icon = 'edit';
UPDATE achievements SET icon = '✨' WHERE icon = 'Sparkles' OR icon = 'sparkles';
UPDATE achievements SET icon = '🌟' WHERE icon = 'Sparkle' OR icon = 'sparkle';
UPDATE achievements SET icon = '📚' WHERE icon = 'Book' OR icon = 'book';
UPDATE achievements SET icon = '🎨' WHERE icon = 'Palette' OR icon = 'palette';
UPDATE achievements SET icon = '🎵' WHERE icon = 'Music' OR icon = 'music';
UPDATE achievements SET icon = '🔔' WHERE icon = 'Bell' OR icon = 'bell';
UPDATE achievements SET icon = '⚡' WHERE icon = 'Zap' OR icon = 'zap';
UPDATE achievements SET icon = '🚀' WHERE icon = 'Rocket' OR icon = 'rocket';
UPDATE achievements SET icon = '💎' WHERE icon = 'Diamond' OR icon = 'diamond';
UPDATE achievements SET icon = '🌈' WHERE icon = 'Rainbow' OR icon = 'rainbow';
UPDATE achievements SET icon = '☀️' WHERE icon = 'Sun' OR icon = 'sun';
UPDATE achievements SET icon = '🌙' WHERE icon = 'Moon' OR icon = 'moon';
UPDATE achievements SET icon = '⏰' WHERE icon = 'Clock' OR icon = 'clock';
UPDATE achievements SET icon = '📅' WHERE icon = 'Calendar' OR icon = 'calendar';
UPDATE achievements SET icon = '👤' WHERE icon = 'User' OR icon = 'user';
UPDATE achievements SET icon = '👥' WHERE icon = 'Users' OR icon = 'users';
UPDATE achievements SET icon = '🔗' WHERE icon = 'Link' OR icon = 'link';
UPDATE achievements SET icon = '📢' WHERE icon = 'Megaphone' OR icon = 'megaphone';
UPDATE achievements SET icon = '🛒' WHERE icon = 'ShoppingCart' OR icon = 'shoppingcart';
UPDATE achievements SET icon = '💰' WHERE icon = 'Wallet' OR icon = 'wallet';
UPDATE achievements SET icon = '🎮' WHERE icon = 'Gamepad' OR icon = 'gamepad';
UPDATE achievements SET icon = '🏠' WHERE icon = 'Home' OR icon = 'home';
UPDATE achievements SET icon = '✈️' WHERE icon = 'Plane' OR icon = 'plane';
UPDATE achievements SET icon = '🎪' WHERE icon = 'Tent' OR icon = 'tent';
UPDATE achievements SET icon = '🎭' WHERE icon = 'Drama' OR icon = 'drama';
UPDATE achievements SET icon = '🎲' WHERE icon = 'Dice' OR icon = 'dice';
UPDATE achievements SET icon = '🔮' WHERE icon = 'Crystal' OR icon = 'crystal';
UPDATE achievements SET icon = '🧩' WHERE icon = 'Puzzle' OR icon = 'puzzle';
UPDATE achievements SET icon = '🏋️' WHERE icon = 'Dumbbell' OR icon = 'dumbbell';
UPDATE achievements SET icon = '🎂' WHERE icon = 'Cake' OR icon = 'cake';
UPDATE achievements SET icon = '🍕' WHERE icon = 'Pizza' OR icon = 'pizza';
UPDATE achievements SET icon = '☕' WHERE icon = 'Coffee' OR icon = 'coffee';
UPDATE achievements SET icon = '🍎' WHERE icon = 'Apple' OR icon = 'apple';
UPDATE achievements SET icon = '📧' WHERE icon = 'Mail' OR icon = 'mail';
UPDATE achievements SET icon = '🔒' WHERE icon = 'Lock' OR icon = 'lock';
UPDATE achievements SET icon = '🔓' WHERE icon = 'Unlock' OR icon = 'unlock';
UPDATE achievements SET icon = '⚙️' WHERE icon = 'Settings' OR icon = 'settings';
UPDATE achievements SET icon = '🔍' WHERE icon = 'Search' OR icon = 'search';
UPDATE achievements SET icon = '📊' WHERE icon = 'BarChart' OR icon = 'barchart';
UPDATE achievements SET icon = '📈' WHERE icon = 'TrendingUp' OR icon = 'trendingup';
UPDATE achievements SET icon = '✅' WHERE icon = 'Check' OR icon = 'check' OR icon = 'CheckCircle';
UPDATE achievements SET icon = '❌' WHERE icon = 'X' OR icon = 'x' OR icon = 'XCircle';
UPDATE achievements SET icon = '➕' WHERE icon = 'Plus' OR icon = 'plus';
UPDATE achievements SET icon = '➖' WHERE icon = 'Minus' OR icon = 'minus';
UPDATE achievements SET icon = '❓' WHERE icon = 'HelpCircle' OR icon = 'helpcircle';
UPDATE achievements SET icon = 'ℹ️' WHERE icon = 'Info' OR icon = 'info';
UPDATE achievements SET icon = '⚠️' WHERE icon = 'AlertTriangle' OR icon = 'alerttriangle';
UPDATE achievements SET icon = '🔴' WHERE icon = 'Circle' OR icon = 'circle';
UPDATE achievements SET icon = '🟢' WHERE icon = 'Dot' OR icon = 'dot';
UPDATE achievements SET icon = '📍' WHERE icon = 'MapPin' OR icon = 'mappin';
UPDATE achievements SET icon = '🗺️' WHERE icon = 'Map' OR icon = 'map';
UPDATE achievements SET icon = '🌍' WHERE icon = 'Globe' OR icon = 'globe';
UPDATE achievements SET icon = '🏢' WHERE icon = 'Building' OR icon = 'building';
UPDATE achievements SET icon = '🛠️' WHERE icon = 'Tool' OR icon = 'tool' OR icon = 'Wrench';
UPDATE achievements SET icon = '📎' WHERE icon = 'Paperclip' OR icon = 'paperclip';
UPDATE achievements SET icon = '📁' WHERE icon = 'Folder' OR icon = 'folder';
UPDATE achievements SET icon = '📄' WHERE icon = 'File' OR icon = 'file';
UPDATE achievements SET icon = '🖼️' WHERE icon = 'Image' OR icon = 'image';
UPDATE achievements SET icon = '🎞️' WHERE icon = 'Film' OR icon = 'film';
UPDATE achievements SET icon = '🎧' WHERE icon = 'Headphones' OR icon = 'headphones';
UPDATE achievements SET icon = '🎤' WHERE icon = 'Mic' OR icon = 'mic' OR icon = 'Microphone';
UPDATE achievements SET icon = '🔊' WHERE icon = 'Volume2' OR icon = 'volume' OR icon = 'Speaker';
UPDATE achievements SET icon = '🔇' WHERE icon = 'VolumeX' OR icon = 'mute';
UPDATE achievements SET icon = '📞' WHERE icon = 'Phone' OR icon = 'phone';
UPDATE achievements SET icon = '💻' WHERE icon = 'Laptop' OR icon = 'laptop' OR icon = 'Monitor';
UPDATE achievements SET icon = '⌨️' WHERE icon = 'Keyboard' OR icon = 'keyboard';
UPDATE achievements SET icon = '🖱️' WHERE icon = 'Mouse' OR icon = 'mouse';
UPDATE achievements SET icon = '🖨️' WHERE icon = 'Printer' OR icon = 'printer';
UPDATE achievements SET icon = '💿' WHERE icon = 'Disc' OR icon = 'disc';
UPDATE achievements SET icon = '💾' WHERE icon = 'Save' OR icon = 'save';
UPDATE achievements SET icon = '🗑️' WHERE icon = 'Trash' OR icon = 'trash';
UPDATE achievements SET icon = '📦' WHERE icon = 'Package' OR icon = 'package' OR icon = 'Box';
UPDATE achievements SET icon = '🏷️' WHERE icon = 'Tag' OR icon = 'tag';
UPDATE achievements SET icon = '🔖' WHERE icon = 'Bookmark' OR icon = 'bookmark';
UPDATE achievements SET icon = '📌' WHERE icon = 'Pin' OR icon = 'pin';
UPDATE achievements SET icon = '✂️' WHERE icon = 'Scissors' OR icon = 'scissors';
UPDATE achievements SET icon = '📐' WHERE icon = 'Ruler' OR icon = 'ruler';
UPDATE achievements SET icon = '✏️' WHERE icon = 'Pencil' OR icon = 'pencil';
UPDATE achievements SET icon = '🖊️' WHERE icon = 'Pen' OR icon = 'pen';
UPDATE achievements SET icon = '🖍️' WHERE icon = 'Crayon' OR icon = 'crayon';
UPDATE achievements SET icon = '🧹' WHERE icon = 'Broom' OR icon = 'broom';
UPDATE achievements SET icon = '🔑' WHERE icon = 'Key' OR icon = 'key';
UPDATE achievements SET icon = '🚪' WHERE icon = 'Door' OR icon = 'door';
UPDATE achievements SET icon = '🪟' WHERE icon = 'Window' OR icon = 'window';
UPDATE achievements SET icon = '🛋️' WHERE icon = 'Sofa' OR icon = 'sofa' OR icon = 'Couch';
UPDATE achievements SET icon = '🛏️' WHERE icon = 'Bed' OR icon = 'bed';
UPDATE achievements SET icon = '🚿' WHERE icon = 'Shower' OR icon = 'shower';
UPDATE achievements SET icon = '🛁' WHERE icon = 'Bath' OR icon = 'bath';
UPDATE achievements SET icon = '🚽' WHERE icon = 'Toilet' OR icon = 'toilet';