
-- Shadow Arena AI Credits System
CREATE TABLE IF NOT EXISTS public.shadow_arena_credits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL UNIQUE,
  credits_remaining INTEGER NOT NULL DEFAULT 5,
  total_credits_purchased INTEGER NOT NULL DEFAULT 5,
  last_used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.shadow_arena_credits ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users view own shadow credits" ON public.shadow_arena_credits FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own shadow credits" ON public.shadow_arena_credits FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "System updates shadow credits" ON public.shadow_arena_credits FOR UPDATE USING (true);

-- AI Horror Stories generated by AI Story Generator
CREATE TABLE IF NOT EXISTS public.shadow_ai_stories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  prompt TEXT NOT NULL,
  generated_title TEXT,
  generated_story TEXT NOT NULL,
  illustration_url TEXT,
  tone TEXT,
  length TEXT,
  credits_used INTEGER NOT NULL DEFAULT 4,
  is_public BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.shadow_ai_stories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users view own ai stories" ON public.shadow_ai_stories FOR SELECT USING (auth.uid() = user_id OR is_public = true);
CREATE POLICY "Users insert own ai stories" ON public.shadow_ai_stories FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own ai stories" ON public.shadow_ai_stories FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users delete own ai stories" ON public.shadow_ai_stories FOR DELETE USING (auth.uid() = user_id);

-- Narrations from AI Voice Narrator
CREATE TABLE IF NOT EXISTS public.shadow_narrations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  story_id UUID,
  story_text TEXT NOT NULL,
  audio_base64 TEXT,
  voice_id TEXT NOT NULL,
  voice_label TEXT,
  credits_used INTEGER NOT NULL DEFAULT 6,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.shadow_narrations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users view own narrations" ON public.shadow_narrations FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own narrations" ON public.shadow_narrations FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users delete own narrations" ON public.shadow_narrations FOR DELETE USING (auth.uid() = user_id);

-- Battle predictions
CREATE TABLE IF NOT EXISTS public.shadow_battle_predictions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  battle_id UUID,
  predicted_winner_name TEXT,
  predicted_winner_id UUID,
  confidence_score INTEGER,
  reasoning TEXT,
  factors JSONB,
  credits_used INTEGER NOT NULL DEFAULT 5,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.shadow_battle_predictions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users view own predictions" ON public.shadow_battle_predictions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own predictions" ON public.shadow_battle_predictions FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Nightmare avatars
CREATE TABLE IF NOT EXISTS public.shadow_nightmare_avatars (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  source_image_url TEXT NOT NULL,
  nightmare_image_url TEXT,
  style TEXT NOT NULL,
  is_profile_avatar BOOLEAN NOT NULL DEFAULT false,
  credits_used INTEGER NOT NULL DEFAULT 8,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.shadow_nightmare_avatars ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users view own avatars" ON public.shadow_nightmare_avatars FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own avatars" ON public.shadow_nightmare_avatars FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own avatars" ON public.shadow_nightmare_avatars FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users delete own avatars" ON public.shadow_nightmare_avatars FOR DELETE USING (auth.uid() = user_id);

-- Storage bucket for nightmare avatars
INSERT INTO storage.buckets (id, name, public) VALUES ('shadow-nightmare-avatars', 'shadow-nightmare-avatars', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public read nightmare avatars" ON storage.objects FOR SELECT USING (bucket_id = 'shadow-nightmare-avatars');
CREATE POLICY "Users upload nightmare avatars" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'shadow-nightmare-avatars' AND auth.uid()::text = (storage.foldername(name))[1]);
CREATE POLICY "Users delete own nightmare avatars" ON storage.objects FOR DELETE USING (bucket_id = 'shadow-nightmare-avatars' AND auth.uid()::text = (storage.foldername(name))[1]);

-- Stripe-driven topup transactions for Shadow Arena AI credits
CREATE TABLE IF NOT EXISTS public.shadow_credit_purchases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  credits_purchased INTEGER NOT NULL,
  amount_eur NUMERIC(10,2) NOT NULL,
  stripe_session_id TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.shadow_credit_purchases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users view own credit purchases" ON public.shadow_credit_purchases FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "System manages credit purchases" ON public.shadow_credit_purchases FOR ALL USING (true);

-- Trigger to update updated_at
CREATE OR REPLACE FUNCTION public.update_shadow_credits_timestamp()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS shadow_credits_updated ON public.shadow_arena_credits;
CREATE TRIGGER shadow_credits_updated BEFORE UPDATE ON public.shadow_arena_credits FOR EACH ROW EXECUTE FUNCTION public.update_shadow_credits_timestamp();
