INSERT INTO public.gift_catalog (slug, name, category, price_credits, rarity, animation, sort_order) VALUES
('sleeping-puppies','Sleeping Puppies','scenes',20,'rare','float',900),
('lion-cub','Lion Cub','scenes',25,'rare','float',901),
('unicorn-fantasy','Unicorn Fantasy','scenes',50,'epic','float',902),
('party-bus','Party Bus','scenes',30,'rare','shake',903),
('diamond-blaster','Diamond Blaster','scenes',50,'epic','pulse',904),
('dino-freestyle','Dino Freestyle','scenes',18,'rare','shake',905),
('dj-cat','DJ Cat','scenes',30,'rare','pulse',906),
('kitten-rose','Kitten & Rose','scenes',22,'rare','float',907),
('panda-picnic','Panda Picnic','scenes',15,'common','float',908),
('sloth-hammock','Sloth Hammock','scenes',12,'common','float',909),
('penguin-slide','Penguin Slide','scenes',10,'common','shake',910),
('bunny-balloon','Bunny Balloons','scenes',8,'common','float',911),
('corgi-skate','Corgi Skate','scenes',14,'common','shake',912),
('otter-boat','Otter Boat','scenes',16,'common','float',913),
('space-kitty','Space Kitty','scenes',35,'epic','float',914),
('pegasus-sky','Pegasus Sky','scenes',60,'epic','float',915),
('dragon-castle','Dragon Castle','scenes',80,'epic','pulse',916),
('sunset-supercar','Sunset Supercar','scenes',100,'legendary','shake',917),
('love-carriage','Love Carriage','scenes',70,'epic','float',918),
('treasure-island','Treasure Island','scenes',90,'epic','float',919),
('magic-library','Magic Library','scenes',65,'epic','float',920),
('neon-motorbike','Neon Motorbike','scenes',85,'epic','shake',921),
('koala-surf','Koala Surf','scenes',28,'rare','float',922),
('tiger-throne','Tiger Throne','scenes',120,'legendary','pulse',923),
('fox-lantern','Fox Lantern','scenes',24,'rare','float',924),
('sky-whale','Sky Whale','scenes',110,'legendary','float',925),
('mermaid-cove','Mermaid Cove','scenes',95,'epic','float',926),
('robot-buddy','Robot Buddy','scenes',26,'rare','shake',927),
('cloud-castle','Cloud Castle','scenes',150,'legendary','float',928),
('phoenix-rise','Phoenix Rise','scenes',300,'legendary','pulse',929)
ON CONFLICT (slug) DO NOTHING;