ALTER TABLE public.gift_catalog ADD COLUMN IF NOT EXISTS emoji text;
ALTER TABLE public.gift_catalog ALTER COLUMN image_url DROP NOT NULL;

INSERT INTO public.gift_catalog (slug, name, category, price_credits, rarity, animation, emoji, sort_order)
VALUES
('rose','Rose','classic',1,'common','float','🌹',1),
('heart','Heart','classic',2,'common','pulse','❤️',2),
('star','Star','classic',3,'common','spin','⭐',3),
('coffee','Coffee','classic',4,'common','bounce','☕',4),
('cake','Cake','classic',5,'common','swing','🍰',5),
('teddy','Teddy','classic',6,'common','glow','🧸',6),
('applause','Applause','classic',5,'rare','burst','👏',7),
('kiss','Kiss','classic',7,'rare','float','💋',8),
('sunflower','Sunflower','classic',9,'rare','pulse','🌻',9),
('thumbs-up','Thumbs Up','classic',11,'rare','spin','👍',10),
('bouquet','Bouquet','classic',13,'rare','bounce','💐',11),
('ribbon','Ribbon','classic',15,'rare','swing','🎀',12),
('letter','Letter','classic',20,'epic','glow','💌',13),
('bell','Bell','classic',30,'epic','burst','🔔',14),
('candle','Candle','classic',40,'epic','float','🕯️',15),
('handshake','Handshake','classic',50,'epic','pulse','🤝',16),
('peace','Peace','classic',60,'epic','spin','✌️',17),
('wink','Wink','classic',100,'legendary','bounce','😉',18),
('smile','Smile','classic',200,'legendary','swing','😊',19),
('hug','Hug','classic',300,'legendary','glow','🫂',20),
('sparkling-heart','Sparkling Heart','love',1,'common','pulse','💖',21),
('two-hearts','Two Hearts','love',2,'common','spin','💕',22),
('heart-arrow','Heart Arrow','love',3,'common','bounce','💘',23),
('heart-gift','Heart Gift','love',4,'common','swing','💝',24),
('love-locket','Love Locket','love',5,'common','glow','🔐',25),
('cupid-wing','Cupid Wing','love',6,'common','burst','🪽',26),
('red-lips','Red Lips','love',5,'rare','float','👄',27),
('ring','Ring','love',7,'rare','pulse','💍',28),
('love-note','Love Note','love',9,'rare','spin','📜',29),
('heartbeat','Heartbeat','love',11,'rare','bounce','💓',30),
('rose-garden','Rose Garden','love',13,'rare','swing','🌷',31),
('blue-heart','Blue Heart','love',15,'rare','glow','💙',32),
('purple-heart','Purple Heart','love',20,'epic','burst','💜',33),
('golden-heart','Golden Heart','love',30,'epic','float','💛',34),
('broken-heart','Broken Heart','love',40,'epic','pulse','💔',35),
('couple','Couple','love',50,'epic','spin','💑',36),
('wedding-bell','Wedding Bell','love',60,'epic','bounce','👰',37),
('love-potion','Love Potion','love',100,'legendary','swing','🧪',38),
('swan-pair','Swan Pair','love',200,'legendary','glow','🦢',39),
('forever','Forever','love',300,'legendary','burst','♾️',40),
('balloons','Balloons','party',1,'common','spin','🎈',41),
('disco','Disco Ball','party',2,'common','bounce','🪩',42),
('guitar','Guitar','party',3,'common','swing','🎸',43),
('fireworks','Fireworks','party',4,'common','glow','🎆',44),
('confetti','Confetti','party',5,'common','burst','🎉',45),
('microphone','Microphone','party',6,'common','float','🎤',46),
('headphones','Headphones','party',5,'rare','pulse','🎧',47),
('drum','Drum','party',7,'rare','spin','🥁',48),
('saxophone','Saxophone','party',9,'rare','bounce','🎷',49),
('trumpet','Trumpet','party',11,'rare','swing','🎺',50),
('violin','Violin','party',13,'rare','glow','🎻',51),
('piano','Piano','party',15,'rare','burst','🎹',52),
('party-hat','Party Hat','party',20,'epic','float','🥳',53),
('sparkler','Sparkler','party',30,'epic','pulse','🎇',54),
('dancer','Dancer','party',40,'epic','spin','💃',55),
('dance-floor','Dance Floor','party',50,'epic','bounce','🕺',56),
('ticket','Ticket','party',60,'epic','swing','🎫',57),
('boombox','Boombox','party',100,'legendary','glow','📻',58),
('cheers','Cheers','party',200,'legendary','burst','🥂',59),
('neon-sign','Neon Sign','party',300,'legendary','float','🪧',60),
('unicorn','Unicorn','fairytale',1,'common','bounce','🦄',61),
('dragon','Dragon','fairytale',2,'common','swing','🐉',62),
('castle','Cloud Castle','fairytale',3,'common','glow','🏰',63),
('phoenix','Phoenix','fairytale',4,'common','burst','🔥',64),
('lion','Brave Lion','fairytale',5,'common','float','🦁',65),
('magic-wand','Magic Wand','fairytale',6,'common','pulse','🪄',66),
('fairy','Fairy','fairytale',5,'rare','spin','🧚',67),
('wizard','Wizard','fairytale',7,'rare','bounce','🧙',68),
('mermaid','Mermaid','fairytale',9,'rare','swing','🧜',69),
('genie-lamp','Genie Lamp','fairytale',11,'rare','glow','🪔',70),
('spell-book','Spell Book','fairytale',13,'rare','burst','📖',71),
('crystal-ball','Crystal Ball','fairytale',15,'rare','float','🔮',72),
('frog-prince','Frog Prince','fairytale',20,'epic','pulse','🐸',73),
('elf-guardian','Elf Guardian','fairytale',30,'epic','spin','🧝',74),
('glass-slipper','Glass Slipper','fairytale',40,'epic','bounce','👠',75),
('enchanted-rose','Enchanted Rose','fairytale',50,'epic','swing','🥀',76),
('moon-owl','Moon Owl','fairytale',60,'epic','glow','🦉',77),
('snow-queen','Snow Queen','fairytale',100,'legendary','burst','❄️',78),
('pixie-dust','Pixie Dust','fairytale',200,'legendary','float','✨',79),
('griffin','Griffin','fairytale',300,'legendary','pulse','🦅',80),
('diamond','Diamond','luxury',2,'common','swing','💎',81),
('crown','Crown','luxury',4,'common','glow','👑',82),
('treasure','Treasure Chest','luxury',6,'common','burst','🧰',83),
('sportscar','Sports Car','luxury',8,'common','float','🏎️',84),
('jet','Private Jet','luxury',10,'common','pulse','✈️',85),
('gold-bar','Gold Bar','luxury',12,'common','spin','🧱',86),
('champagne','Champagne','luxury',10,'rare','bounce','🍾',87),
('yacht','Yacht','luxury',14,'rare','swing','🛥️',88),
('money-bag','Money Bag','luxury',18,'rare','glow','💰',89),
('luxury-watch','Luxury Watch','luxury',22,'rare','burst','⌚',90),
('penthouse','Penthouse','luxury',26,'rare','float','🏙️',91),
('helicopter','Helicopter','luxury',30,'rare','pulse','🚁',92),
('fur-coat','Fur Coat','luxury',40,'epic','spin','🧥',93),
('pearl-necklace','Pearl Necklace','luxury',60,'epic','bounce','📿',94),
('golden-trophy','Golden Trophy','luxury',80,'epic','swing','🏆',95),
('limousine','Limousine','luxury',100,'epic','glow','🚙',96),
('caviar','Caviar','luxury',120,'epic','burst','🥂',97),
('emerald','Emerald','luxury',200,'legendary','float','🟢',98),
('ruby','Ruby','luxury',400,'legendary','pulse','🔴',99),
('platinum-card','Platinum Card','luxury',600,'legendary','spin','💳',100),
('rainbow','Rainbow','nature',1,'common','glow','🌈',101),
('sunrise','Sunrise','nature',2,'common','burst','🌅',102),
('ocean-wave','Ocean Wave','nature',3,'common','float','🌊',103),
('cherry-blossom','Cherry Blossom','nature',4,'common','pulse','🌸',104),
('four-leaf-clover','Four Leaf Clover','nature',5,'common','spin','🍀',105),
('cactus','Cactus','nature',6,'common','bounce','🌵',106),
('palm-tree','Palm Tree','nature',5,'rare','swing','🌴',107),
('maple-leaf','Maple Leaf','nature',7,'rare','glow','🍁',108),
('snowflake','Snowflake','nature',9,'rare','burst','🌨️',109),
('thunderbolt','Thunderbolt','nature',11,'rare','float','⚡',110),
('volcano','Volcano','nature',13,'rare','pulse','🌋',111),
('mountain','Mountain','nature',15,'rare','spin','🏔️',112),
('waterfall','Waterfall','nature',20,'epic','bounce','💦',113),
('forest','Forest','nature',30,'epic','swing','🌲',114),
('mushroom','Mushroom','nature',40,'epic','glow','🍄',115),
('tulip-field','Tulip Field','nature',50,'epic','burst','🌷',116),
('firefly','Firefly','nature',60,'epic','float','🪰',117),
('butterfly','Butterfly','nature',100,'legendary','pulse','🦋',118),
('honeybee','Honeybee','nature',200,'legendary','spin','🐝',119),
('full-moon','Full Moon','nature',300,'legendary','bounce','🌕',120),
('pizza-slice','Pizza Slice','food',1,'common','burst','🍕',121),
('ice-cream','Ice Cream','food',2,'common','float','🍦',122),
('donut','Donut','food',3,'common','pulse','🍩',123),
('sushi','Sushi','food',4,'common','spin','🍣',124),
('burger','Burger','food',5,'common','bounce','🍔',125),
('cupcake','Cupcake','food',6,'common','swing','🧁',126),
('chocolate','Chocolate','food',5,'rare','glow','🍫',127),
('strawberry','Strawberry','food',7,'rare','burst','🍓',128),
('watermelon','Watermelon','food',9,'rare','float','🍉',129),
('popcorn','Popcorn','food',11,'rare','pulse','🍿',130),
('pancakes','Pancakes','food',13,'rare','spin','🥞',131),
('croissant','Croissant','food',15,'rare','bounce','🥐',132),
('bubble-tea','Bubble Tea','food',20,'epic','swing','🧋',133),
('cocktail','Cocktail','food',30,'epic','glow','🍸',134),
('cheese-wheel','Cheese Wheel','food',40,'epic','burst','🧀',135),
('lollipop','Lollipop','food',50,'epic','float','🍭',136),
('honey-pot','Honey Pot','food',60,'epic','pulse','🍯',137),
('taco','Taco','food',100,'legendary','spin','🌮',138),
('ramen','Ramen','food',200,'legendary','bounce','🍜',139),
('birthday-feast','Birthday Feast','food',300,'legendary','swing','🎂',140),
('rocket','Rocket','adventure',1,'common','float','🚀',141),
('hot-air-balloon','Hot Air Balloon','adventure',2,'common','pulse','🎈',142),
('compass','Compass','adventure',3,'common','spin','🧭',143),
('treasure-map','Treasure Map','adventure',4,'common','bounce','🗺️',144),
('surfboard','Surfboard','adventure',5,'common','swing','🏄',145),
('ski-jump','Ski Jump','adventure',6,'common','glow','🎿',146),
('skateboard','Skateboard','adventure',5,'rare','burst','🛹',147),
('bicycle','Bicycle','adventure',7,'rare','float','🚲',148),
('camping-tent','Camping Tent','adventure',9,'rare','pulse','⛺',149),
('lighthouse','Lighthouse','adventure',11,'rare','spin','🗼',150),
('sailboat','Sailboat','adventure',13,'rare','bounce','⛵',151),
('submarine','Submarine','adventure',15,'rare','swing','🛳️',152),
('parachute','Parachute','adventure',20,'epic','glow','🪂',153),
('climbing-rope','Climbing Rope','adventure',30,'epic','burst','🧗',154),
('safari-jeep','Safari Jeep','adventure',40,'epic','float','🚙',155),
('desert-camel','Desert Camel','adventure',50,'epic','pulse','🐪',156),
('polar-trek','Polar Trek','adventure',60,'epic','spin','🧊',157),
('jungle-path','Jungle Path','adventure',100,'legendary','bounce','🌿',158),
('deep-dive','Deep Dive','adventure',200,'legendary','swing','🤿',159),
('world-trip','World Trip','adventure',300,'legendary','glow','🌍',160),
('shooting-star','Shooting Star','cosmic',1,'common','pulse','🌟',161),
('galaxy','Galaxy','cosmic',2,'common','spin','🌌',162),
('saturn','Saturn','cosmic',3,'common','bounce','🪐',163),
('comet','Comet','cosmic',4,'common','swing','☄️',164),
('sun-flare','Sun Flare','cosmic',5,'common','glow','🌞',165),
('crescent-moon','Crescent Moon','cosmic',6,'common','burst','🌙',166),
('constellation','Constellation','cosmic',5,'rare','float','♈',167),
('nebula','Nebula','cosmic',7,'rare','pulse','🌫️',168),
('space-station','Space Station','cosmic',9,'rare','spin','🛰️',169),
('alien-friend','Alien Friend','cosmic',11,'rare','bounce','👽',170),
('black-hole','Black Hole','cosmic',13,'rare','swing','⚫',171),
('star-map','Star Map','cosmic',15,'rare','glow','🗺️',172),
('meteor-shower','Meteor Shower','cosmic',20,'epic','burst','💫',173),
('aurora','Aurora','cosmic',30,'epic','float','🌠',174),
('telescope','Telescope','cosmic',40,'epic','pulse','🔭',175),
('cosmic-egg','Cosmic Egg','cosmic',50,'epic','spin','🥚',176),
('time-portal','Time Portal','cosmic',60,'epic','bounce','🌀',177),
('astronaut','Astronaut','cosmic',100,'legendary','swing','👨‍🚀',178),
('star-crown','Star Crown','cosmic',200,'legendary','glow','🌟',179),
('infinity-star','Infinity Star','cosmic',300,'legendary','burst','✳️',180),
('kitten','Kitten','cute',1,'common','spin','🐱',181),
('puppy','Puppy','cute',2,'common','bounce','🐶',182),
('bunny','Bunny','cute',3,'common','swing','🐰',183),
('panda','Panda','cute',4,'common','glow','🐼',184),
('penguin','Penguin','cute',5,'common','burst','🐧',185),
('fox-cub','Fox Cub','cute',6,'common','float','🦊',186),
('baby-chick','Baby Chick','cute',5,'rare','pulse','🐤',187),
('hamster','Hamster','cute',7,'rare','spin','🐹',188),
('koala','Koala','cute',9,'rare','bounce','🐨',189),
('sloth','Sloth','cute',11,'rare','swing','🦥',190),
('axolotl','Axolotl','cute',13,'rare','glow','🦎',191),
('hedgehog','Hedgehog','cute',15,'rare','burst','🦔',192),
('duckling','Duckling','cute',20,'epic','float','🦆',193),
('piglet','Piglet','cute',30,'epic','pulse','🐷',194),
('lamb','Lamb','cute',40,'epic','spin','🐑',195),
('otter','Otter','cute',50,'epic','bounce','🦦',196),
('seal-pup','Seal Pup','cute',60,'epic','swing','🦭',197),
('turtle','Turtle','cute',100,'legendary','glow','🐢',198),
('owlet','Owlet','cute',200,'legendary','burst','🦉',199),
('squirrel','Squirrel','cute',300,'legendary','float','🐿️',200)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  price_credits = EXCLUDED.price_credits,
  rarity = EXCLUDED.rarity,
  animation = EXCLUDED.animation,
  emoji = EXCLUDED.emoji,
  sort_order = EXCLUDED.sort_order,
  is_active = true;