-- Insert 400+ more achievements to reach ~500 total (all in English)
INSERT INTO achievements (code, name, description, icon, points) VALUES
-- Content Creation Series (50)
('content_creator_1', 'Content Starter', 'Create your first piece of content', '📝', 5),
('content_creator_5', 'Content Enthusiast', 'Create 5 pieces of content', '📝', 15),
('content_creator_10', 'Content Producer', 'Create 10 pieces of content', '📝', 25),
('content_creator_25', 'Content Master', 'Create 25 pieces of content', '📝', 50),
('content_creator_50', 'Content Expert', 'Create 50 pieces of content', '📝', 100),
('content_creator_100', 'Content Legend', 'Create 100 pieces of content', '📝', 200),
('story_teller_1', 'Story Beginner', 'Share your first story', '📖', 10),
('story_teller_5', 'Story Enthusiast', 'Share 5 stories', '📖', 25),
('story_teller_10', 'Story Master', 'Share 10 stories', '📖', 50),
('story_teller_25', 'Story Legend', 'Share 25 stories', '📖', 100),
('meme_lord_1', 'Meme Starter', 'Post your first meme', '😂', 10),
('meme_lord_5', 'Meme Enthusiast', 'Post 5 memes', '😂', 25),
('meme_lord_10', 'Meme Master', 'Post 10 memes', '😂', 50),
('meme_lord_25', 'Meme Legend', 'Post 25 memes', '😂', 100),
('quote_master_1', 'Quote Starter', 'Share your first quote', '💭', 10),
('quote_master_5', 'Quote Enthusiast', 'Share 5 quotes', '💭', 25),
('quote_master_10', 'Quote Master', 'Share 10 quotes', '💭', 50),
('tutorial_creator_1', 'Tutorial Beginner', 'Create your first tutorial', '🎓', 15),
('tutorial_creator_5', 'Tutorial Teacher', 'Create 5 tutorials', '🎓', 40),
('tutorial_creator_10', 'Tutorial Professor', 'Create 10 tutorials', '🎓', 80),
('review_writer_1', 'Review Starter', 'Write your first review', '⭐', 10),
('review_writer_5', 'Review Expert', 'Write 5 reviews', '⭐', 30),
('review_writer_10', 'Review Master', 'Write 10 reviews', '⭐', 60),
('tip_giver_1', 'Tip Starter', 'Share your first tip', '💡', 8),
('tip_giver_5', 'Tip Enthusiast', 'Share 5 tips', '💡', 20),
('tip_giver_10', 'Tip Expert', 'Share 10 tips', '💡', 40),
('tip_giver_25', 'Tip Master', 'Share 25 tips', '💡', 80),
('guide_author_1', 'Guide Beginner', 'Write your first guide', '📚', 15),
('guide_author_5', 'Guide Writer', 'Write 5 guides', '📚', 40),
('guide_author_10', 'Guide Author', 'Write 10 guides', '📚', 80),
('poll_creator_1', 'Poll Starter', 'Create your first poll', '📊', 8),
('poll_creator_5', 'Poll Enthusiast', 'Create 5 polls', '📊', 20),
('poll_creator_10', 'Poll Master', 'Create 10 polls', '📊', 40),
('question_asker_1', 'Curious Mind', 'Ask your first question', '❓', 5),
('question_asker_5', 'Question Seeker', 'Ask 5 questions', '❓', 15),
('question_asker_10', 'Question Master', 'Ask 10 questions', '❓', 30),
('question_asker_25', 'Question Expert', 'Ask 25 questions', '❓', 60),
('answer_giver_1', 'Helper Start', 'Answer your first question', '✅', 8),
('answer_giver_5', 'Helpful User', 'Answer 5 questions', '✅', 20),
('answer_giver_10', 'Knowledge Sharer', 'Answer 10 questions', '✅', 40),
('answer_giver_25', 'Answer Expert', 'Answer 25 questions', '✅', 80),
('answer_giver_50', 'Answer Master', 'Answer 50 questions', '✅', 150),
('link_sharer_1', 'Link Starter', 'Share your first link', '🔗', 5),
('link_sharer_5', 'Link Enthusiast', 'Share 5 links', '🔗', 15),
('link_sharer_10', 'Link Master', 'Share 10 links', '🔗', 30),
('playlist_creator_1', 'Playlist Beginner', 'Create your first playlist', '🎵', 10),
('playlist_creator_5', 'Playlist Curator', 'Create 5 playlists', '🎵', 30),
('collection_builder_1', 'Collector Start', 'Start your first collection', '📦', 10),
('collection_builder_5', 'Collection Builder', 'Create 5 collections', '📦', 30),
('collection_builder_10', 'Collection Master', 'Create 10 collections', '📦', 60),

-- Engagement Series (50)
('reactor_1', 'First Reaction', 'React to your first post', '👍', 5),
('reactor_10', 'Reaction Fan', 'React to 10 posts', '👍', 15),
('reactor_50', 'Reaction Enthusiast', 'React to 50 posts', '👍', 30),
('reactor_100', 'Reaction Master', 'React to 100 posts', '👍', 60),
('reactor_500', 'Reaction Legend', 'React to 500 posts', '👍', 150),
('reactor_1000', 'Reaction God', 'React to 1000 posts', '👍', 300),
('heart_giver_1', 'Heart Starter', 'Give your first heart', '❤️', 5),
('heart_giver_10', 'Heart Giver', 'Give 10 hearts', '❤️', 15),
('heart_giver_50', 'Heart Spreader', 'Give 50 hearts', '❤️', 30),
('heart_giver_100', 'Heart Master', 'Give 100 hearts', '❤️', 60),
('heart_giver_500', 'Heart Legend', 'Give 500 hearts', '❤️', 150),
('applause_giver_1', 'Applause Start', 'Give your first applause', '👏', 5),
('applause_giver_10', 'Applause Fan', 'Give 10 applauses', '👏', 15),
('applause_giver_50', 'Applause Enthusiast', 'Give 50 applauses', '👏', 30),
('laugh_reactor_1', 'Laugh Start', 'Give your first laugh reaction', '😄', 5),
('laugh_reactor_10', 'Laugh Fan', 'Give 10 laugh reactions', '😄', 15),
('laugh_reactor_50', 'Laugh Master', 'Give 50 laugh reactions', '😄', 30),
('wow_reactor_1', 'Wow Start', 'Give your first wow reaction', '😮', 5),
('wow_reactor_10', 'Wow Fan', 'Give 10 wow reactions', '😮', 15),
('wow_reactor_50', 'Wow Master', 'Give 50 wow reactions', '😮', 30),
('sad_reactor_1', 'Empathy Start', 'Give your first sad reaction', '😢', 5),
('sad_reactor_10', 'Empathetic Soul', 'Give 10 sad reactions', '😢', 15),
('angry_reactor_1', 'Passion Start', 'Give your first angry reaction', '😠', 5),
('angry_reactor_10', 'Passionate User', 'Give 10 angry reactions', '😠', 15),
('bookmark_saver_1', 'Bookmark Start', 'Save your first bookmark', '🔖', 5),
('bookmark_saver_10', 'Bookmark Collector', 'Save 10 bookmarks', '🔖', 15),
('bookmark_saver_50', 'Bookmark Hoarder', 'Save 50 bookmarks', '🔖', 30),
('bookmark_saver_100', 'Bookmark Master', 'Save 100 bookmarks', '🔖', 60),
('share_starter_1', 'Share Beginner', 'Share your first content', '📤', 5),
('share_starter_10', 'Share Enthusiast', 'Share 10 times', '📤', 20),
('share_starter_50', 'Share Expert', 'Share 50 times', '📤', 50),
('share_starter_100', 'Share Master', 'Share 100 times', '📤', 100),
('repost_king_1', 'Repost Start', 'Make your first repost', '🔄', 5),
('repost_king_10', 'Repost Fan', 'Make 10 reposts', '🔄', 20),
('repost_king_50', 'Repost Expert', 'Make 50 reposts', '🔄', 50),
('mention_user_1', 'Mention Start', 'Mention someone for the first time', '📢', 5),
('mention_user_10', 'Mention Friend', 'Mention 10 users', '📢', 15),
('mention_user_50', 'Mention Master', 'Mention 50 users', '📢', 40),
('tag_user_1', 'Tag Beginner', 'Tag someone in a post', '@️', 5),
('tag_user_10', 'Tag Enthusiast', 'Tag 10 users', '@️', 15),
('tag_user_50', 'Tag Master', 'Tag 50 users', '@️', 40),
('emoji_user_1', 'Emoji Starter', 'Use your first emoji', '😊', 3),
('emoji_user_10', 'Emoji Fan', 'Use 10 emojis', '😊', 10),
('emoji_user_50', 'Emoji Enthusiast', 'Use 50 emojis', '😊', 25),
('emoji_user_100', 'Emoji Master', 'Use 100 emojis', '😊', 50),
('gif_user_1', 'GIF Starter', 'Use your first GIF', '🎬', 5),
('gif_user_10', 'GIF Fan', 'Use 10 GIFs', '🎬', 15),
('gif_user_50', 'GIF Master', 'Use 50 GIFs', '🎬', 40),
('sticker_user_1', 'Sticker Start', 'Use your first sticker', '🏷️', 5),
('sticker_user_10', 'Sticker Fan', 'Use 10 stickers', '🏷️', 15),
('sticker_user_50', 'Sticker Master', 'Use 50 stickers', '🏷️', 40),

-- Social Connection Series (50)
('friend_maker_1', 'First Friend', 'Make your first friend', '🤝', 10),
('friend_maker_5', 'Friend Builder', 'Make 5 friends', '🤝', 25),
('friend_maker_10', 'Friend Collector', 'Make 10 friends', '🤝', 50),
('friend_maker_25', 'Friend Master', 'Make 25 friends', '🤝', 100),
('friend_maker_50', 'Friend Legend', 'Make 50 friends', '🤝', 200),
('friend_maker_100', 'Social Butterfly', 'Make 100 friends', '🤝', 400),
('follower_1', 'First Follower', 'Get your first follower', '👤', 10),
('follower_10', 'Growing Audience', 'Get 10 followers', '👤', 30),
('follower_50', 'Popular User', 'Get 50 followers', '👤', 80),
('follower_100', 'Rising Star', 'Get 100 followers', '👤', 150),
('follower_500', 'Influencer', 'Get 500 followers', '👤', 400),
('follower_1000', 'Celebrity', 'Get 1000 followers', '👤', 800),
('following_1', 'First Follow', 'Follow your first user', '➕', 5),
('following_10', 'Active Follower', 'Follow 10 users', '➕', 15),
('following_50', 'Community Member', 'Follow 50 users', '➕', 40),
('following_100', 'Connected User', 'Follow 100 users', '➕', 80),
('mutual_friend_1', 'Mutual Start', 'Make your first mutual friend', '🔗', 15),
('mutual_friend_5', 'Mutual Builder', 'Make 5 mutual friends', '🔗', 40),
('mutual_friend_10', 'Mutual Collector', 'Make 10 mutual friends', '🔗', 80),
('mutual_friend_25', 'Mutual Master', 'Make 25 mutual friends', '🔗', 150),
('group_joiner_1', 'Group Starter', 'Join your first group', '👥', 10),
('group_joiner_5', 'Group Member', 'Join 5 groups', '👥', 25),
('group_joiner_10', 'Group Enthusiast', 'Join 10 groups', '👥', 50),
('group_creator_1', 'Group Founder', 'Create your first group', '🏛️', 25),
('group_creator_3', 'Group Builder', 'Create 3 groups', '🏛️', 60),
('group_creator_5', 'Group Master', 'Create 5 groups', '🏛️', 100),
('event_joiner_1', 'Event Starter', 'Join your first event', '📅', 10),
('event_joiner_5', 'Event Goer', 'Join 5 events', '📅', 25),
('event_joiner_10', 'Event Enthusiast', 'Join 10 events', '📅', 50),
('event_creator_1', 'Event Host', 'Create your first event', '🎉', 25),
('event_creator_3', 'Event Planner', 'Create 3 events', '🎉', 60),
('event_creator_5', 'Event Master', 'Create 5 events', '🎉', 100),
('chat_starter_1', 'Chat Beginner', 'Start your first chat', '💬', 5),
('chat_starter_10', 'Chat Fan', 'Start 10 chats', '💬', 20),
('chat_starter_50', 'Chat Master', 'Start 50 chats', '💬', 60),
('message_sender_1', 'Message Start', 'Send your first message', '✉️', 5),
('message_sender_10', 'Messenger', 'Send 10 messages', '✉️', 15),
('message_sender_50', 'Active Messenger', 'Send 50 messages', '✉️', 40),
('message_sender_100', 'Message Expert', 'Send 100 messages', '✉️', 80),
('message_sender_500', 'Message Master', 'Send 500 messages', '✉️', 200),
('voice_caller_1', 'Voice Start', 'Make your first voice call', '📞', 15),
('voice_caller_5', 'Voice User', 'Make 5 voice calls', '📞', 40),
('voice_caller_10', 'Voice Expert', 'Make 10 voice calls', '📞', 80),
('video_caller_1', 'Video Start', 'Make your first video call', '📹', 20),
('video_caller_5', 'Video User', 'Make 5 video calls', '📹', 50),
('video_caller_10', 'Video Expert', 'Make 10 video calls', '📹', 100),
('collab_starter_1', 'Collab Beginner', 'Start your first collaboration', '🤲', 20),
('collab_starter_5', 'Collaborator', 'Complete 5 collaborations', '🤲', 50),
('collab_starter_10', 'Collab Master', 'Complete 10 collaborations', '🤲', 100),
('referral_maker_1', 'Referral Start', 'Make your first referral', '🎁', 25),

-- Time & Streak Series (50)
('daily_active_1', 'Active Day', 'Be active for 1 day', '📆', 5),
('daily_active_3', 'Three Day Streak', 'Be active for 3 days', '📆', 15),
('daily_active_7', 'Week Warrior', 'Be active for 7 days', '📆', 35),
('daily_active_14', 'Two Week Champion', 'Be active for 14 days', '📆', 70),
('daily_active_30', 'Month Master', 'Be active for 30 days', '📆', 150),
('daily_active_60', 'Two Month Legend', 'Be active for 60 days', '📆', 300),
('daily_active_90', 'Quarter King', 'Be active for 90 days', '📆', 450),
('daily_active_180', 'Half Year Hero', 'Be active for 180 days', '📆', 900),
('daily_active_365', 'Year Champion', 'Be active for 365 days', '📆', 1825),
('login_streak_3', 'Login Streak 3', 'Login 3 days in a row', '🔥', 15),
('login_streak_7', 'Login Streak 7', 'Login 7 days in a row', '🔥', 35),
('login_streak_14', 'Login Streak 14', 'Login 14 days in a row', '🔥', 70),
('login_streak_30', 'Login Streak 30', 'Login 30 days in a row', '🔥', 150),
('login_streak_60', 'Login Streak 60', 'Login 60 days in a row', '🔥', 300),
('login_streak_100', 'Login Streak 100', 'Login 100 days in a row', '🔥', 500),
('morning_user_1', 'Early Riser', 'Login before 6 AM', '🌅', 10),
('morning_user_7', 'Morning Person', 'Login before 6 AM for 7 days', '🌅', 35),
('night_user_1', 'Night Owl', 'Login after midnight', '🌙', 10),
('night_user_7', 'Night Hunter', 'Login after midnight for 7 days', '🌙', 35),
('weekend_warrior_1', 'Weekend Start', 'Be active on a weekend', '🎊', 10),
('weekend_warrior_4', 'Weekend Regular', 'Be active on 4 weekends', '🎊', 30),
('weekend_warrior_12', 'Weekend Master', 'Be active on 12 weekends', '🎊', 80),
('monday_motivation_1', 'Monday Start', 'Be active on a Monday', '💪', 10),
('monday_motivation_4', 'Monday Regular', 'Be active on 4 Mondays', '💪', 30),
('friday_fun_1', 'Friday Start', 'Be active on a Friday', '🎉', 10),
('friday_fun_4', 'TGIF Regular', 'Be active on 4 Fridays', '🎉', 30),
('new_year_user', 'New Year User', 'Be active on New Year', '🎆', 50),
('valentine_user', 'Valentine Active', 'Be active on Valentine Day', '💘', 30),
('halloween_user', 'Halloween Active', 'Be active on Halloween', '🎃', 30),
('christmas_user', 'Christmas Active', 'Be active on Christmas', '🎄', 40),
('birthday_poster', 'Birthday Poster', 'Post on your birthday', '🎂', 50),
('anniversary_1', 'First Anniversary', '1 year on the platform', '🎊', 200),
('anniversary_2', 'Second Anniversary', '2 years on the platform', '🎊', 400),
('anniversary_3', 'Third Anniversary', '3 years on the platform', '🎊', 600),
('fast_responder_1', 'Quick Reply', 'Reply within 1 minute', '⚡', 10),
('fast_responder_10', 'Speed Typer', 'Quick reply 10 times', '⚡', 30),
('fast_responder_50', 'Lightning Fast', 'Quick reply 50 times', '⚡', 80),
('consistent_poster_7', 'Week Poster', 'Post every day for a week', '📝', 35),
('consistent_poster_14', 'Fortnight Poster', 'Post every day for 2 weeks', '📝', 70),
('consistent_poster_30', 'Month Poster', 'Post every day for a month', '📝', 150),
('hourly_active_1', 'Hour Active', 'Be active for an hour', '⏰', 5),
('hourly_active_5', 'Five Hours', 'Be active for 5 hours total', '⏰', 15),
('hourly_active_24', 'Full Day', 'Be active for 24 hours total', '⏰', 50),
('hourly_active_100', 'Century Hours', 'Be active for 100 hours', '⏰', 200),
('session_length_30', 'Long Session', '30 minute session', '⌛', 10),
('session_length_60', 'Hour Session', '1 hour session', '⌛', 20),
('comeback_user', 'Welcome Back', 'Return after 30 days away', '👋', 25),
('daily_goal_achiever', 'Goal Achiever', 'Complete daily goal', '🎯', 15),
('weekly_goal_achiever', 'Weekly Winner', 'Complete weekly goal', '🏆', 50),

-- Media & Content Series (50)
('photo_uploader_1', 'Photo Start', 'Upload your first photo', '📷', 5),
('photo_uploader_10', 'Photo Fan', 'Upload 10 photos', '📷', 20),
('photo_uploader_50', 'Photo Enthusiast', 'Upload 50 photos', '📷', 60),
('photo_uploader_100', 'Photo Expert', 'Upload 100 photos', '📷', 120),
('photo_uploader_500', 'Photo Master', 'Upload 500 photos', '📷', 300),
('video_uploader_1', 'Video Start', 'Upload your first video', '🎥', 10),
('video_uploader_10', 'Video Fan', 'Upload 10 videos', '🎥', 40),
('video_uploader_50', 'Video Expert', 'Upload 50 videos', '🎥', 120),
('video_uploader_100', 'Video Master', 'Upload 100 videos', '🎥', 250),
('audio_uploader_1', 'Audio Start', 'Upload your first audio', '🎙️', 10),
('audio_uploader_10', 'Audio Fan', 'Upload 10 audios', '🎙️', 40),
('audio_uploader_50', 'Audio Expert', 'Upload 50 audios', '🎙️', 120),
('document_sharer_1', 'Doc Starter', 'Share your first document', '📄', 10),
('document_sharer_10', 'Doc Sharer', 'Share 10 documents', '📄', 40),
('document_sharer_50', 'Doc Expert', 'Share 50 documents', '📄', 120),
('album_creator_1', 'Album Start', 'Create your first album', '📸', 15),
('album_creator_5', 'Album Builder', 'Create 5 albums', '📸', 40),
('album_creator_10', 'Album Master', 'Create 10 albums', '📸', 80),
('cover_changer_1', 'Cover Start', 'Change your cover photo', '🖼️', 10),
('cover_changer_5', 'Cover Changer', 'Change cover 5 times', '🖼️', 25),
('avatar_changer_1', 'Avatar Start', 'Change your avatar', '👤', 5),
('avatar_changer_5', 'Avatar Fan', 'Change avatar 5 times', '👤', 15),
('avatar_changer_10', 'Avatar Master', 'Change avatar 10 times', '👤', 30),
('filter_user_1', 'Filter Start', 'Use your first filter', '✨', 5),
('filter_user_10', 'Filter Fan', 'Use 10 filters', '✨', 15),
('filter_user_50', 'Filter Master', 'Use 50 filters', '✨', 40),
('edit_master_1', 'Edit Start', 'Edit your first photo', '🎨', 10),
('edit_master_10', 'Edit Fan', 'Edit 10 photos', '🎨', 30),
('edit_master_50', 'Edit Expert', 'Edit 50 photos', '🎨', 80),
('livestream_starter_1', 'Live Beginner', 'Start your first livestream', '🔴', 25),
('livestream_starter_5', 'Live Regular', 'Do 5 livestreams', '🔴', 60),
('livestream_starter_10', 'Live Expert', 'Do 10 livestreams', '🔴', 120),
('livestream_viewer_1', 'Viewer Start', 'Watch your first livestream', '👁️', 10),
('livestream_viewer_10', 'Viewer Fan', 'Watch 10 livestreams', '👁️', 30),
('livestream_viewer_50', 'Viewer Expert', 'Watch 50 livestreams', '👁️', 80),
('reel_creator_1', 'Reel Starter', 'Create your first reel', '🎞️', 15),
('reel_creator_10', 'Reel Fan', 'Create 10 reels', '🎞️', 50),
('reel_creator_50', 'Reel Master', 'Create 50 reels', '🎞️', 150),
('short_video_1', 'Short Start', 'Create your first short video', '📱', 10),
('short_video_10', 'Short Creator', 'Create 10 short videos', '📱', 40),
('short_video_50', 'Short Expert', 'Create 50 short videos', '📱', 120),
('panorama_1', 'Panorama Start', 'Upload your first panorama', '🌄', 15),
('panorama_5', 'Panorama Fan', 'Upload 5 panoramas', '🌄', 40),
('360_photo_1', '360 Starter', 'Upload your first 360 photo', '🔮', 20),
('360_photo_5', '360 Expert', 'Upload 5 360 photos', '🔮', 60),
('timelapse_1', 'Timelapse Start', 'Create your first timelapse', '⏱️', 20),
('timelapse_5', 'Timelapse Fan', 'Create 5 timelapses', '⏱️', 60),
('slowmo_1', 'SlowMo Start', 'Create your first slow-motion', '🐌', 15),
('slowmo_5', 'SlowMo Fan', 'Create 5 slow-motions', '🐌', 45),
('boomerang_1', 'Boomerang Start', 'Create your first boomerang', '🪃', 10),
('boomerang_5', 'Boomerang Fan', 'Create 5 boomerangs', '🪃', 30),

-- Achievement & XP Series (50)
('xp_earner_100', 'XP Starter', 'Earn 100 XP', '⭐', 10),
('xp_earner_500', 'XP Collector', 'Earn 500 XP', '⭐', 25),
('xp_earner_1000', 'XP Enthusiast', 'Earn 1000 XP', '⭐', 50),
('xp_earner_5000', 'XP Expert', 'Earn 5000 XP', '⭐', 150),
('xp_earner_10000', 'XP Master', 'Earn 10000 XP', '⭐', 300),
('xp_earner_50000', 'XP Legend', 'Earn 50000 XP', '⭐', 750),
('xp_earner_100000', 'XP God', 'Earn 100000 XP', '⭐', 1500),
('level_up_5', 'Level 5', 'Reach level 5', '📈', 25),
('level_up_10', 'Level 10', 'Reach level 10', '📈', 50),
('level_up_25', 'Level 25', 'Reach level 25', '📈', 125),
('level_up_50', 'Level 50', 'Reach level 50', '📈', 250),
('level_up_75', 'Level 75', 'Reach level 75', '📈', 375),
('level_up_100', 'Level 100', 'Reach level 100', '📈', 500),
('badge_collector_5', 'Badge Start', 'Collect 5 badges', '🏅', 25),
('badge_collector_10', 'Badge Fan', 'Collect 10 badges', '🏅', 50),
('badge_collector_25', 'Badge Enthusiast', 'Collect 25 badges', '🏅', 125),
('badge_collector_50', 'Badge Expert', 'Collect 50 badges', '🏅', 250),
('badge_collector_100', 'Badge Master', 'Collect 100 badges', '🏅', 500),
('achievement_hunter_10', 'Achievement Start', 'Unlock 10 achievements', '🎖️', 50),
('achievement_hunter_25', 'Achievement Fan', 'Unlock 25 achievements', '🎖️', 125),
('achievement_hunter_50', 'Achievement Expert', 'Unlock 50 achievements', '🎖️', 250),
('achievement_hunter_100', 'Achievement Master', 'Unlock 100 achievements', '🎖️', 500),
('achievement_hunter_200', 'Achievement Legend', 'Unlock 200 achievements', '🎖️', 1000),
('point_scorer_100', 'Points Start', 'Score 100 points', '💯', 10),
('point_scorer_500', 'Points Fan', 'Score 500 points', '💯', 30),
('point_scorer_1000', 'Points Expert', 'Score 1000 points', '💯', 60),
('point_scorer_5000', 'Points Master', 'Score 5000 points', '💯', 200),
('point_scorer_10000', 'Points Legend', 'Score 10000 points', '💯', 400),
('daily_reward_1', 'First Daily', 'Claim your first daily reward', '🎁', 5),
('daily_reward_7', 'Week Rewards', 'Claim 7 daily rewards', '🎁', 20),
('daily_reward_30', 'Month Rewards', 'Claim 30 daily rewards', '🎁', 60),
('daily_reward_100', 'Reward Master', 'Claim 100 daily rewards', '🎁', 150),
('bonus_claimer_1', 'Bonus Start', 'Claim your first bonus', '💰', 10),
('bonus_claimer_10', 'Bonus Fan', 'Claim 10 bonuses', '💰', 40),
('bonus_claimer_50', 'Bonus Expert', 'Claim 50 bonuses', '💰', 120),
('streak_bonus_3', 'Streak Bonus 3', 'Get 3-day streak bonus', '🔥', 15),
('streak_bonus_7', 'Streak Bonus 7', 'Get 7-day streak bonus', '🔥', 35),
('streak_bonus_30', 'Streak Bonus 30', 'Get 30-day streak bonus', '🔥', 150),
('mystery_box_1', 'Mystery Start', 'Open your first mystery box', '🎁', 15),
('mystery_box_10', 'Mystery Fan', 'Open 10 mystery boxes', '🎁', 50),
('mystery_box_50', 'Mystery Expert', 'Open 50 mystery boxes', '🎁', 150),
('spin_wheel_1', 'Spin Start', 'Spin the wheel once', '🎰', 5),
('spin_wheel_10', 'Spin Fan', 'Spin the wheel 10 times', '🎰', 20),
('spin_wheel_50', 'Spin Expert', 'Spin the wheel 50 times', '🎰', 60),
('jackpot_winner', 'Jackpot Winner', 'Win the jackpot', '🎰', 500),
('lucky_draw_1', 'Lucky Start', 'Enter your first lucky draw', '🍀', 10),
('lucky_draw_10', 'Lucky Fan', 'Enter 10 lucky draws', '🍀', 40),
('contest_winner', 'Contest Winner', 'Win a contest', '🏆', 200),
('leaderboard_1', 'Top 100', 'Reach top 100 on leaderboard', '📊', 50),
('leaderboard_top_10', 'Top 10', 'Reach top 10 on leaderboard', '📊', 200),

-- Special & Rare Series (50)
('beta_tester', 'Beta Tester', 'Participated in beta testing', '🧪', 100),
('early_adopter', 'Early Adopter', 'Joined in the first month', '🌟', 150),
('founder_member', 'Founder Member', 'One of the first 100 users', '👑', 500),
('bug_reporter', 'Bug Hunter', 'Report a bug', '🐛', 50),
('feature_suggester', 'Idea Maker', 'Suggest a feature', '💡', 30),
('verified_user', 'Verified', 'Get verified', '✓', 200),
('premium_member', 'Premium Member', 'Become a premium member', '💎', 100),
('vip_member', 'VIP Member', 'Become a VIP member', '👑', 250),
('influencer_badge', 'Influencer', 'Recognized as an influencer', '🌟', 300),
('creator_badge', 'Creator', 'Recognized as a creator', '🎨', 200),
('expert_badge', 'Expert', 'Recognized as an expert', '🎓', 250),
('mentor_badge', 'Mentor', 'Recognized as a mentor', '🧙', 300),
('helper_badge', 'Helper', 'Recognized as a helper', '🤝', 150),
('community_leader', 'Community Leader', 'Lead a community', '👥', 400),
('moderator_badge', 'Moderator', 'Become a moderator', '🛡️', 500),
('ambassador_badge', 'Ambassador', 'Become an ambassador', '🎖️', 600),
('partner_badge', 'Partner', 'Become a partner', '🤝', 700),
('sponsor_badge', 'Sponsor', 'Become a sponsor', '💰', 800),
('charity_donor', 'Charity Donor', 'Donate to charity', '❤️', 100),
('eco_warrior', 'Eco Warrior', 'Support eco initiatives', '🌱', 75),
('trendsetter', 'Trendsetter', 'Start a trend', '🔥', 200),
('viral_hit', 'Viral Hit', 'Create viral content', '📈', 300),
('million_views', 'Million Views', 'Get 1 million views', '👁️', 1000),
('top_creator', 'Top Creator', 'Become a top creator', '⭐', 500),
('hall_of_fame', 'Hall of Fame', 'Enter the hall of fame', '🏛️', 1000),
('legend_status', 'Legend', 'Achieve legend status', '🦸', 2000),
('mythic_status', 'Mythic', 'Achieve mythic status', '🐉', 3000),
('immortal_status', 'Immortal', 'Achieve immortal status', '👼', 5000),
('first_blood', 'First Blood', 'First to do something', '🩸', 100),
('perfectionist', 'Perfectionist', 'Complete profile 100%', '💯', 50),
('multi_talented', 'Multi-Talented', 'Excel in multiple areas', '🎭', 150),
('jack_of_all', 'Jack of All Trades', 'Try everything', '🃏', 100),
('master_of_one', 'Master of One', 'Master one skill', '🎯', 200),
('secret_finder', 'Secret Finder', 'Find a secret feature', '🔐', 75),
('easter_egg_hunter', 'Easter Egg Hunter', 'Find an easter egg', '🥚', 50),
('night_explorer', 'Night Explorer', 'Use dark mode for a week', '🌑', 25),
('theme_collector', 'Theme Collector', 'Try all themes', '🎨', 30),
('language_learner', 'Language Learner', 'Use multiple languages', '🌍', 40),
('global_citizen', 'Global Citizen', 'Connect with 10 countries', '🌐', 100),
('time_traveler', 'Time Traveler', 'View old posts', '⏰', 20),
('memory_keeper', 'Memory Keeper', 'Use memories feature', '📚', 25),
('throwback_poster', 'Throwback', 'Post a throwback', '📅', 15),
('nostalgia_trip', 'Nostalgia Trip', 'View 1 year old content', '🕰️', 30),
('data_lover', 'Data Lover', 'Check your statistics', '📊', 15),
('analytics_pro', 'Analytics Pro', 'Master analytics', '📈', 50),
('privacy_guardian', 'Privacy Guardian', 'Set up privacy settings', '🔒', 20),
('security_expert', 'Security Expert', 'Enable all security features', '🛡️', 40),
('backup_master', 'Backup Master', 'Backup your data', '💾', 25),
('clean_slate', 'Clean Slate', 'Clean up old posts', '🧹', 20),
('organizer', 'Organizer', 'Organize your content', '📁', 30)
ON CONFLICT (code) DO NOTHING;