// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { resolveProxy } from './proxyMap';

const SUPABASE_URL = "https://jufrdzeonywluwutvyxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1ZnJkemVvbnl3bHV3dXR2eXh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMzU0MTgsImV4cCI6MjA3NDcxMTQxOH0.UOe-_WQoTeBGFmnezRHRcjFJaJd71a7rYlurDkI6h4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, { auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Disable navigator.locks-based locking which causes spurious
    // "Lock broken by another request with the 'steal' option" AbortErrors
    // when many parallel queries fetch the session at once on mobile.
    lock: async (_name: string, _acquireTimeout: number, fn: () => Promise<any>) => fn() }
});

// ---------------------------------------------------------------------------
// Safety wrapper around removeChannel: an upstream recursion in
// @supabase/phoenix can throw "Maximum call stack size exceeded" during
// rapid unsubscribe (see Sentry). Swallow it so it doesn't bubble up as
// an unhandled rejection and spam error logs / Sentry.
// ---------------------------------------------------------------------------
const _origRemoveChannel = supabase.removeChannel.bind(supabase);
(supabase as any).removeChannel = (channel: any) => {
  try {
    return _origRemoveChannel(channel);
  } catch (e: any) {
    if (e && /Maximum call stack size exceeded/i.test(String(e?.message))) {
      return Promise.resolve("ok" as const);
    }
    throw e;
  }
};

// ---------------------------------------------------------------------------
// Safety wrapper around channel(): supabase-js returns an *existing* channel
// when the same topic is requested twice. If that channel was already
// subscribed (e.g. a component remounted before its cleanup ran, or two
// components share a topic), calling .on('postgres_changes', ...) throws
// "cannot add `postgres_changes` callbacks ... after `subscribe()`" and the
// whole page crashes for that user. Always hand back a fresh channel.
// ---------------------------------------------------------------------------
const _origChannel = supabase.channel.bind(supabase);
(supabase as any).channel = (topic: string, params?: any) => {
  try {
    const existing = supabase.getChannels().find((c: any) => c.topic === `realtime:${topic}` || c.topic === topic);
    if (existing) {
      try { void (supabase as any).removeChannel(existing); } catch { /* noop */ }
    }
  } catch { /* noop */ }
  return params ? _origChannel(topic, params) : _origChannel(topic);
};


// ---------------------------------------------------------------------------
// Edge function consolidation: transparently rewrites legacy proxy function
// names to their universal router equivalents (generate-gift-message,
// create-checkout, verify-payment). The 179 proxy functions previously hosted
// in supabase/functions/ have been deleted to stay under Supabase's edge
// function limit; this wrapper keeps every existing supabase.functions.invoke
// call across the codebase working without changes.
// ---------------------------------------------------------------------------
const _originalInvoke = supabase.functions.invoke.bind(supabase.functions);

// Sampling for successful calls to keep write volume bounded — errors always logged.
const METRIC_SAMPLE_RATE = 0.1;

async function recordMetric(fn: string, startedAt: number, ok: boolean, statusCode: number | null, errorMessage: string | null) { try {
    if (ok && Math.random() > METRIC_SAMPLE_RATE) return;
    const duration_ms = Math.min(Math.max(Math.round(performance.now() - startedAt), 0), 599999);
    await (supabase.from("edge_function_metrics") as any).insert({
      function_name: fn.slice(0, 199),
      duration_ms,
      ok,
      status_code: statusCode,
      error_message: errorMessage ? errorMessage.slice(0, 999) : null });
  } catch {
    /* swallow — telemetry must never break the app */
  }
}

(supabase.functions as any).invoke = async (functionName: string, options?: any) => {
  const resolved = resolveProxy(functionName, options?.body);
  const target = resolved ? resolved.target : functionName;
  const body = resolved ? resolved.body : options?.body;
  const startedAt = performance.now();
  try {
    const res = await _originalInvoke(target, { ...(options ?? {}), body });
    const errObj = (res as any)?.error;
    const ctx = errObj?.context;
    const status = typeof ctx?.status === "number" ? ctx.status : errObj ? 500 : 200;
    void recordMetric(target, startedAt, !errObj, status, errObj?.message ?? null);
    return res;
  } catch (e: any) {
    void recordMetric(target, startedAt, false, null, e?.message ?? "invoke_threw");
    throw e;
  }
};

// ---------------------------------------------------------------------------
// getUser() de-duplication.
//
// Hundreds of hooks call `supabase.auth.getUser()` on mount. Each call is a
// network round-trip to /auth/v1/user, so heavy pages (Safety, Wellness, AI
// chats) fire dozens of them at once on mobile. Under that burst the auth
// endpoint can rate-limit / time out, supabase-js treats the reply as an
// invalid session and emits SIGNED_OUT — the user sees a brief "logged out"
// flash before the session is restored.
//
// Fix: coalesce concurrent calls, cache the result briefly, and short-circuit
// to the locally stored session when there is none. The cache is invalidated
// on every auth state change, so sign-in/sign-out stay instant.
// ---------------------------------------------------------------------------
const _origGetUser = supabase.auth.getUser.bind(supabase.auth);
const GET_USER_TTL_MS = 30_000;
let _userCache: { at: number; res: any } | null = null;
let _userInflight: Promise<any> | null = null;

(supabase.auth as any).getUser = async (jwt?: string) => {
  // Explicit-token checks must always hit the server.
  if (jwt) return _origGetUser(jwt);

  const now = Date.now();
  if (_userCache && now - _userCache.at < GET_USER_TTL_MS) return _userCache.res;
  if (_userInflight) return _userInflight;

  _userInflight = (async () => {
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        const res = { data: { user: null }, error: null };
        _userCache = { at: Date.now(), res };
        return res;
      }
      const res = await _origGetUser();
      if (!res?.error) _userCache = { at: Date.now(), res };
      return res;
    } finally {
      _userInflight = null;
    }
  })();

  return _userInflight;
};

supabase.auth.onAuthStateChange(() => {
  _userCache = null;
});
