// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { resolveProxy } from './proxyMap';

const SUPABASE_URL = "https://jufrdzeonywluwutvyxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1ZnJkemVvbnl3bHV3dXR2eXh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMzU0MTgsImV4cCI6MjA3NDcxMTQxOH0.UOe-_WQoTeBGFmnezRHRcjFJaJd71a7rYlurDkI6h4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Disable navigator.locks-based locking which causes spurious
    // "Lock broken by another request with the 'steal' option" AbortErrors
    // when many parallel queries fetch the session at once on mobile.
    lock: async (_name: string, _acquireTimeout: number, fn: () => Promise<any>) => fn(),
  }
});

// ---------------------------------------------------------------------------
// Edge function consolidation: transparently rewrites legacy proxy function
// names to their universal router equivalents (generate-gift-message,
// create-checkout, verify-payment). The 179 proxy functions previously hosted
// in supabase/functions/ have been deleted to stay under Supabase's edge
// function limit; this wrapper keeps every existing supabase.functions.invoke
// call across the codebase working without changes.
// ---------------------------------------------------------------------------
const _originalInvoke = supabase.functions.invoke.bind(supabase.functions);
(supabase.functions as any).invoke = async (functionName: string, options?: any) => {
  const resolved = resolveProxy(functionName, options?.body);
  if (resolved) {
    return _originalInvoke(resolved.target, { ...(options ?? {}), body: resolved.body });
  }
  return _originalInvoke(functionName, options);
};
