// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { resolveProxy } from './proxyMap';

const SUPABASE_URL = "https://jufrdzeonywluwutvyxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1ZnJkemVvbnl3bHV3dXR2eXh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMzU0MTgsImV4cCI6MjA3NDcxMTQxOH0.UOe-_WQoTeBGFmnezRHRcjFJaJd71a7rYlurDkI6h4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Disable navigator.locks-based locking which causes spurious
    // "Lock broken by another request with the 'steal' option" AbortErrors
    // when many parallel queries fetch the session at once on mobile.
    lock: async (_name: string, _acquireTimeout: number, fn: () => Promise<any>) => fn(),
  }
});

// ---------------------------------------------------------------------------
// Edge function consolidation: transparently rewrites legacy proxy function
// names to their universal router equivalents (generate-gift-message,
// create-checkout, verify-payment). The 179 proxy functions previously hosted
// in supabase/functions/ have been deleted to stay under Supabase's edge
// function limit; this wrapper keeps every existing supabase.functions.invoke
// call across the codebase working without changes.
// ---------------------------------------------------------------------------
const _originalInvoke = supabase.functions.invoke.bind(supabase.functions);

// Sampling for successful calls to keep write volume bounded — errors always logged.
const METRIC_SAMPLE_RATE = 0.1;

async function recordMetric(fn: string, startedAt: number, ok: boolean, statusCode: number | null, errorMessage: string | null) {
  try {
    if (ok && Math.random() > METRIC_SAMPLE_RATE) return;
    const duration_ms = Math.min(Math.max(Math.round(performance.now() - startedAt), 0), 599999);
    await (supabase.from("edge_function_metrics") as any).insert({
      function_name: fn.slice(0, 199),
      duration_ms,
      ok,
      status_code: statusCode,
      error_message: errorMessage ? errorMessage.slice(0, 999) : null,
    });
  } catch {
    /* swallow — telemetry must never break the app */
  }
}

(supabase.functions as any).invoke = async (functionName: string, options?: any) => {
  const resolved = resolveProxy(functionName, options?.body);
  const target = resolved ? resolved.target : functionName;
  const body = resolved ? resolved.body : options?.body;
  const startedAt = performance.now();
  try {
    const res = await _originalInvoke(target, { ...(options ?? {}), body });
    const errObj = (res as any)?.error;
    const ctx = errObj?.context;
    const status = typeof ctx?.status === "number" ? ctx.status : errObj ? 500 : 200;
    void recordMetric(target, startedAt, !errObj, status, errObj?.message ?? null);
    return res;
  } catch (e: any) {
    void recordMetric(target, startedAt, false, null, e?.message ?? "invoke_threw");
    throw e;
  }
};
